usegalaxy-au/infrastructure

dev_playbook.yml, group_vars/all.yml, group_vars/dev_slurm.yml, group_vars/rabbitservers.yml, host_vars/dev.usegalaxy.org.au.yml, hosts
- As per Simon's work with rabbit, have `hostname: "{{ ansible_hostname }}.usegalaxy.org.au"` in all.yml
- Replace hyphens in group names with underscores.  Ansible gives a warning  `Invalid characters were found in group names but not replaced, use -vvvv to see details'.  It probably doesn't matter but it's difficult to tell.
- add vars_files to dev_playbook
=> host file and variable path updates

group_vars/galaxyservers.yml, requirements.yml
Use galaxyproject.galaxy role 0.96.  Remove config paths for cache directories as there are sensible defaults set in 0.9.6. 
Also remove conda_auto_install: true from galaxy config.
=> update ansible-galaxy role requirement to 0.9.6

group_vars/galaxyservers.yml
tool_data_path was set `{{ galaxy_server_dir }}/tool-data` instead of `{{ galaxy_mutable_data_dir }}/tool-data` by mistake
=> fix tool_data_path

terraform/dev/dev-initial.tf, terraform/dev/dev-secgroups.tf, terraform/one-offs/rabbitmq/rabbitmq.tf, terraform/staging/backends.tf, terraform/staging/staging-initial.tf, terraform/staging/staging-secgroups.tf
Non-default rules for custom security groups have been imported and the security group configs are in dev-secgroups.tf and staging-secgroups.tf.
Due to changes in naming of images, the dev images now correspond to slightly different names in nectar ("NeCTAR Ubuntu 20.04 LTS (Focal) amd64 [v3]" instead of "NeCTAR Ubuntu 20.04 LTS (Focal) amd64".  We should probably store the image_id instead of image_name in our terraform configuration.
The is also `terraform/one-offs/rabbitmq` for the rabbitmq security group.  As a one-off, this does not need backends.tf, it's just for adding rabbitmq to a tenancy that does not have it yet.
=> Update staging terraform, add security groups

group_vars/galaxyservers.yml, host_vars/staging.usegalaxy.org.au.yml, staging_playbook.yml
This is a WIP, there is an assumption of a file called `group_vars/staging_slurm.yml` and I couldn't remember whether we needed the group vars for slurm to be divided into dev/staging/prod
There are opportunities to refactor things in galaxyservers.yml that will not be the same for all servers, i.e. uwsgi settings but am leaving it as is for now
This is mostly copy/paste with 'staging' in place of 'dev'.  The job_conf is the same but with the tools section removed.
=> create staging playbook from dev playbook and add staging host_vars file

group_vars/pulsarservers.yml
On dev pulsar jobs were not running because 'import pycurl' threw an exception.  Using this variable sets the pycurl backend correctly (the default from the role is gnutls for Debian)
=> set pulsar_pycurl_ssl_library to openssl

files/galaxy/dynamic_job_rules/dev/dynamic_rules/destination_mapper.py, files/galaxy/dynamic_job_rules/dev/dynamic_rules/tool_destinations.yml, files/galaxy/dynamic_job_rules/dev/readme.txt, files/galaxy/dynamic_job_rules/staging/dynamic_rules/destination_mapper.py, files/galaxy/dynamic_job_rules/staging/dynamic_rules/tool_destinations.yml, files/galaxy/dynamic_job_rules/staging/readme.txt, files/galaxyservers/static/welcome.html, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
Modules with functions that call galaxy's `map_tool_to_destination` using a tool_destinations.yml file.  These are equivalent to using dynamic_dtd with the tool_destionations.yml file but can be extended to do things like limiting resources to a group or choosing destinations based on queue sizes while still defaulting to the destination chosen by `map_tool_to_destination`.
This has the [WIP] label - it still needs to be tested on staging.
=> Dynamic job rules for dev and staging

files/galaxy/config/tool_sheds_conf.xml, group_vars/galaxyservers.yml
A few of the tools on production are from the test toolshed.  To allow these on the new galaxy we need to allow installations from testtoolshed.
=> add tool_sheds_conf.xml allowing tools from test toolshed

group_vars/galaxyservers.yml
If `enable_tool_recommendations` is true, galaxy detects extra dependencies that need to be installed but these cannot be installed.   It's not clear whether this is a bug in ansible-galaxy, galaxy or our setup.  Leave out this config option for now.
=> comment out enable_tool_recommendations

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
File size rules for unicycler and spades from production tool_destinations.  I've substituted slurm destinations where pulsar_mel3 destinations were specified.  The list has been sorted alphabetically by tool name.
TODO:
- Linting for tool_destinations pull requests
- Automation of updating when these PRs are merged
=> add pawsey tool destinations for unicycler and spades as per galaxy prod

group_vars/galaxyservers.yml
Put shed_tool_data_table_conf.xml before the cvmfs data tables in tool_data_table_config_path so that Minikraken will be first on the list for kraken_databases.
=> fix data table loading order

host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
dev and staging had the db_address variable for pgpass set to something weird.  The equivalent variable for pawsey will be OK.
=> fix the db_address variable for dev and staging

.ci/test_vars/job_conf_test_vars.yml, .github/workflows/check_tool_destinations.yml
The watched files included pawsey_job_conf.xml instead of pawsey_job_conf.yml.  Any variables not defined in the job conf need to exist for ansible to template the file, so fake passwords are added to test_vars
=> fix tool dest linting

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
This is a WIP.  The tools need to be in order.  This is all from galaxy prod except that user-specific rules have been removed, some blocks refactored,
Rules for and tool destinations for SRA tools have been changed from
```
fasterq_dump:
default_destination: slurm_1slot
fastq_dump:
default_destination: slurm_1slot
sam_dump:
default_destination: slurm_1slot_upload
```
to `slurm_3slots` for each of them.
=>  tool destination rules from galaxy production

group_vars/pulsarservers.yml
Tested on dev.  New conda environments belong to ubuntu.
=> set pulsar_user: ubuntu in pulsar group vars

group_vars/galaxyservers.yml, templates/nginx/galaxy.j2
changed
```
tool_data_table_config_path:
- file1
- file2
```
to `tool_data_table_config_path: file1,file2`
and added route to nginx conf for GTN in galaxy
This will be compatible with the the 20.05 branch
=> changes for 20.09 to galaxyservers.yml and templates/nginx/galaxy.j2

group_vars/galaxyservers.yml
From testing legacy tools on dev... apparently this file is not being used by default
=> include path to dependency resolvers sample file in galaxyservers.yml

files/galaxy/dynamic_job_rules/dev/dynamic_rules/destination_mapper.py, files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/destination_mapper.py
Pulsar destinations for users whose shed-tool jobs will always go to various pulsars depending on the user email.
This is working on dev.
These accounts can be used to test any shed tool to see if it will work at the pulsar destinations.  Anything that is not a toolshed tool will run at its regular slurm destination (upload1, converters etc)
=> Dynamic pulsar destinations

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml, host_vars/pawsey_job_conf.yml, pawsey-workers_playbook.yml
This is for jobs that will use a lot of disk space. We can assign them 9 slots but ensure that only one of them runs at a time.
=> Added a 9slot_1off destination to the job_conf

group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
The galaxy_infrastructure_url is included in job completion emails and defaults to localhost
=> add galaxy_infrastructure_url to galaxyservers.yml

pawsey-workers_playbook.yml
A few tools are failing with permission errors.  This could be due to permissions on the tmpdisks being slightly different since these were added to the ansible.
=> change mode of worker tmpdisk to '1777'

files/galaxy/gxadmin/gxadmin-local.sh, roles/pg-post-tasks/tasks/main.yml
Replace gxadmin-local.sh when it is updated here (this was previously not the case).  Any gxadmin commands can be added in this repo or to gxadmin-local-extra.sh in the same dir as gxadmin-local.sh.
Addresses https://github.com/usegalaxy-au/infrastructure/issues/118
There are also some new functions around job input file size using pg_pretty_size.
```
$ gxadmin local query-job-input-datasets 4092986755
hda_id  |            hda_name             |  d_id   | d_state | d_file_size | d_total_size
---------+---------------------------------+---------+---------+-------------+--------------
91237625 | SRR7692603:forward uncompressed | 3545195 | ok      | 4810 MB     | 4810 MB
91237627 | SRR7692603:reverse uncompressed | 3545196 | ok      | 4845 MB     | 4845 MB
```
```
$ gxadmin local …
```
=> add gxadmin-local.sh to each user's home dir and add some functions

group_vars/galaxyservers.yml, requirements.yml
add `data_dir: "{{ galaxy_root }}/cache"` because otherwise all of the cache directories spawn within `/mnt/galaxy`
Addresses #156
=> upgrade galaxyproject roles to current versions

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
This could ease slurm bottlenecks but there is also a risk that it could create bottlenecks on pulsar-mel3, it's difficult to tell.
=> Send larger bwa_mem jobs to pulsar-mel3

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
This will put pressure on the slurm queue but every single job with input size > 10G is failing
=> set default_destination for bwa_mem back to slurm_7slots

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
bwa_mem 1-2G stays on pulsar-mel3, 2-10G goes back to slurm_5slots, 10G+ goes to slurm_7slots
bwa 250M-1G goes to pulsar-mel_mid
spades 15M-2G goes to pulsar-mel3_small
trimmomatic 15M-3G goes to pulsar-mel3_small
=> bwa_mem back to slurm, various size spades, trimmomatic and bwa jobs to pulsar

files/galaxy/gxadmin/gxadmin-local.sh
Add a gxadmin local function that lists all recent jobs regardless of state.  By default it lists 50 jobs but there is an optional argument for limit.
=> add gxadmin local query-all-jobs

files/galaxy/config/tool_conf.xml
this should be under the METAGENOMICS header
once this is in place it can be deleted where it currently is in integrated_tool_panel and it will reappear in the right spot
=> dna metabarcoding was in the wrong place

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
@Slugger70 these went to pulsar-mel3_small by mistake, I must have been thinking that it was half the size of mel3_mid rather than a quarter
=> send medium sized bowtie2 jobs to pulsar-mel3_mid

group_vars/galaxyservers.yml
This was at 30g but pawsey does not have enough space
=> set client_max_body_size to 25g

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
large fastqc job are split between pulsar-mel2 and pulsar-mel3 but more of these could run on mel2
=> send more large fastqc jobs to pulsar-mel2

aarnet-dev_playbook.yml, dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/aarnet-dev.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, roles/nginx-upload-module/README.md, roles/nginx-upload-module/defaults/main.yml, roles/nginx-upload-module/tasks/build_module.yml, roles/nginx-upload-module/tasks/main.yml, roles/set-up-volume/tasks/main.yml, templates/nginx/galaxy.j2, terraform/dev/dev-initial.tf
This adds a role to install official nginx and add a task for building the module.  The build_module task is standalone and should be run on a non-production server.
Because nginx is installed in this role we need to skip the installation in the galaxyproject.nginx role so the requirement for the role has switched to a galaxy-au fork of the ansible-nginx.
Marking this as a draft for now.
=> Dev upload store working branch

files/galaxy/dynamic_job_rules/aarnet-dev/dynamic_rules/tool_destinations.yml, host_vars/aarnet-dev.usegalaxy.org.au.yml
give aarnet-dev job conf some slurm destinations to parallel slurm dests on production.  8 slots is as high as we can go.  This could help with with a recent user tool issue with pilon.
=> aarnet dev slurm dests to parallel production dests

host_vars/pawsey.usegalaxy.org.au.yml, pawsey_playbook.yml
@Slugger70 this puts the upload store in /mnt/user-data because of the recommendation in https://docs.galaxyproject.org/en/master/admin/nginx.html#receiving-files-with-nginx "create a directory in which to store uploads (ideally, for performance reasons, on the same filesystem as Galaxy’s datasets)" but we could potentially be putting this somewhere else.  Initially when I was trying this out on dev I was using another volume mounted from the galaxy server.
=> upload module for pawsey

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
Due to queues for pulsar-mel3_big..
Up to 500Mb to pulsar-mel_mid, 500Mb to 5G to pulsar-mel_big, default dest slurm_9slots
=> send minimap to pulsar-mel2 and slurm9

terraform/dev/dev-initial.tf
The new flavours we can use have 1 vcpu for every 4G of RAM.  The previous ones had 2 vcpus for 4G.  In each case we are doubling the RAM and staying with the same number of VCPUs as before.  The dev volume is 1000G (previously 200) and the dev-ftp volume is 300G.
=> update dev terraform

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
currently running on slurm1slot and possibly running out of memory with inputs bigger than 3G
passes 2/2 tests on pulsar
=> send khmer_abundance_distribution_single to pulsar-mel3 small and mid

files/galaxy/config/tool_conf.xml
The UI is broken for this.  Based on https://github.com/galaxyproject/galaxy/issues/11729: keep the tool in the tool_conf.xml but hide it
=> hide old uploader in tool panel

aarnet_playbook.yml
lsync was quitting because it couldn't create its log file, then it was quitting saying it didn't have enough watches.  Set max_user_watches to 524288, same as pawsey.
=> create log folder and set max watchers for lsync

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
Of the 5 tools only trycyler_consensus can run on pulsar.  trycycler_cluster, trycycler_partition and trycycler_subsample return collections.  trycycler_reconcile_msa has an extra script in the tool directory that is not transferred to pulsar.
=> tool destinations for trycyler

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
meryl can run on pulsar.
eu sets mem at 12 for merqury and 110 for meryl.
=> set destinations for meryl and merqury

files/galaxy/config/object_store_conf.xml, group_vars/pawsey_workers.yml, host_vars/pawsey.usegalaxy.org.au.yml
Switch to using /mnt/user-data-2 on pawsey
Before merging:
Run the pawsey-user-nfs playbook
Delete or modify the normal and noqld object store copies in /mnt/galaxy/config
Immediately after running this, reload nginx on pawsey.
=> switch to new volume in object store when user-data reaches 95%

files/galaxy/config/aarnet_test_object_store_conf.xml, group_vars/aarnet_workers.yml, host_vars/aarnet.usegalaxy.org.au.yml
Uncomment variables to mount qld filesystems at aarent.
At pawsey /mnt/files has been symlinked to /mnt/galaxy/files because that was the file path in qld.  The database does not store file paths, only dataset ids so setting the path as /mnt/files in object store should be OK.  This is commented out in the object store.  If we wanted to test file access from the galaxy application we'd need to load a backup of the database and uncomment this.
=> uncomment qld mounts and add to aarnet test object store

roles/remote-pulsar-cron/templates/remove_pulsar_jwds.py.j2
`-e X` delete error jwds more than X days old if X >=0 or none of them if X < 0
=> allow pulsar cron script to delete all error job working directies if `-e 0` in command

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
based on eu's tool destinations: they use 12G memory for jellyfish
=> send jellyfish to pulsar-mel2

build-machines_playbook.yml, group_vars/pulsar-nci-test/pulsar-nci-test_slurm.yml, group_vars/pulsar_mel2/pulsar-mel2_slurm.yml, group_vars/pulsar_mel3/pulsar-mel3_slurm.yml, group_vars/pulsar_paw/pulsar-paw_slurm.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, hosts, pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml, pulsar-mel2_worker_playbook.yml, pulsar-mel3_worker_playbook.yml, pulsar-nci-test_workers_playbook.yml, pulsar-paw_worker_playbook.yml
Address deprecation warning about group names.
Alternatively we could be setting `force_valid_group_names = ignore` in ansible.cfg.  I'm in favour of changing the group names because it's easy to do and we don't have to override the (new) default.
=> Make all group names valid (use _ instead of -)

.gitignore, aarnet_playbook.yml, dev_playbook.yml, pawsey_playbook.yml, requirements.yml, staging_playbook.yml
Update galaxyproject roles to their latest version.  The latest ansible-pulsar role requires ansible version 2.10 or later.  This will not be ready to merge ansible users (and the build server) have updated ansible.
I haven't seen any changes that I think will affect the current playbooks except the ansible 2.10 requirement of ansible-pulsar
links to diffs between versions.
https://github.com/galaxyproject/ansible-galaxy/compare/0.9.11...galaxyproject:0.9.16
https://github.com/galaxyproject/ansible-pulsar/compare/1.0.6...galaxyproject:1.0.8
https://github.com/galaxyproject/ansible-nginx/compare/0.6.4...galaxyproject:0.7.0
https://github.com/galaxyproject/ansible-gxadmin/compare/0.0.5...galaxyproject:0.0.8
=> update roles for galaxy, pulsar, gxadmin and nginx

host_vars/aarnet-db.usegalaxy.org.au.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev-db.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey-db.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, requirements.yml
It asks for fewer select permissions for the tiaas db user and an additional delete permission for group_role_association.  There is also `tiaas_disassociate_training_roles`:
```
tiaas_disassociate_training_roles:
hour: 0      # optional, defaults to 0
minute: 0    # optional, defaults to 0
```
Looks like sets a daily cron job to delete sessions that have finished at an hour and minute that we can set, or have `tiaas_disassociate_training_roles: false` to not set the cron.
I've tentatively set these to `hour: 9` so that they clean up at 7pm
=> upgrade tiaas role

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
- Revert commits to send pulsar-mel3 jobs to pulsar-mel2 and pulsar-high-mem1
- Send rseqc_geneBody_coverage to pulsar-mel3_mid for inputs above 500M
- Adjust rules to send some smaller large bowtie2, hisat2 to mel2 instead of mel3
=> send things back to pulsar-mel3

group_vars/pulsar_mel3/pulsar-mel3_slurm.yml, hosts, terraform/pulsar-mel3/pulsar-mel3-initial.tf
the image names of the existing VMs needed to be changed to match their image ids, otherwise terraform wanted to replace them
=> add another worker to mel3

group_vars/dev_slurm.yml
This should fix the mem env var problem. Can you run this on dev, dev workers and queue please?
=> added CR_CPU_Memory to dev slurm so galaxy mem env works

jenkins/update_labels/hidden_tools.yml, jenkins/update_labels/update_labels.py
Set hidden="True" in the update_labels process from a list of tool ids so that shed_tool_conf.xml never has to be manually edited
=> Add setting hidden tools to the automatic editing of shed_tool_conf

files/galaxy/gxadmin/gxadmin-local.sh
- `local_query-1slot-jobs-by-walltime`: to find jobs that have taken more than X seconds running on slurm_1slot
- `local_query-walltime-size-by-tool`: to see walltime and input for recent jobs by tool
=> local gxadmin queries to see runtime vs input size

roles/remote-pulsar-cron/templates/remove_pulsar_jwds.py.j2
The script throws an error when there is nothing to remove.  Exit early and log 'nothing to remove' instead.
=> fix pulsar cron job for empty lists

roles/pg-post-tasks/tasks/main.yml
/home/<username/.config is owned by root which is a bug
=> .config folder in home directories should be owned by users

aarnet-db_playbook.yml
Update aarnet-db playbook with a block of post-tasks that will create and initialise the data_directory after the galaxyproject.postgresql task has run, when it does not exist yet.
=> update aarnet-db playbook

files/galaxy/gxadmin/gxadmin-local.sh
Local gxadmin query to find jobs created before and finished after a given datetime, to find jobs that might have two sets of dataset files after the object store changes.
=> add query for jobs running at a given datetime

files/galaxy/config/aarnet_object_store_conf.xml, files/galaxy/dynamic_job_rules/aarnet/dynamic_rules/tool_destinations.yml, group_vars/aarnet_workers.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/aarnet_job_conf.yml
`galaxy_file_path: /mnt/user-data-3/test` + separate object store file for aarnet.
job_conf has all pulsars commented out.  pulsar-nci-test could be enabled but there seems no need to switch it away from dev before Monday.
Maybe leave this open for now.
=> aarnet testing object store and var changes

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
TPV tags were renamed as follows:
required -> require
preferred -> prefer
tolerated -> accept
rejected -> reject
Less typing and hopefully less ambiguity in the case of `tolerated`.
=> Update dev tpv rules to match renamed tags

group_vars/pulsarservers.yml, pulsar-mel2_playbook.yml, pulsar-mel3_playbook.yml, pulsar-nci-test_playbook.yml, pulsar-nci-training_playbook.yml, pulsar-paw_playbook.yml, roles/pulsar-post-tasks/tasks/main.yml, staging-pulsar_playbook.yml
remove exportfs command from pulsar-post-tasks because not all pulsars need it and it breaks on the high-mems
=> update pulsar-post-tasks to set permissions on new folder

host_vars/pawsey-db.usegalaxy.org.au.yml
this could also be done by hand rather than through the playbook.  It requires a restart for logs to go the the right file.  I've included changes from the config on pawsey-db
=> make pawsey-db log queries

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
The native specification only has to be defined for the default tool and for anything that uses a different partition, i.e. the training role or maxquant.
Neither pulsar nor slurm has a problem with the extra parameter
=> define the native spec twice so that wherever it goes, one of the keys is correct

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
the abricate env is broken on pulsar-mel3, it can't be rebuilt at the moment because of bioconda
=> send abricate to pulsar-mel2

files/galaxy/gxadmin/gxadmin-local.sh
This is copied from`gxadmin query queue-detail` with runner_id and count removed and cores, mem and partition columns added.  
```
$ gxadmin local query-queue
state  |  id  | extid |                          tool_id                          | username | time_since_creation |       handler       | cores | mem  | partition | destination_id
---------+------+-------+-----------------------------------------------------------+----------+---------------------+---------------------+-------+------+-----------+-----------------
running | 4385 | 4011  | upload1                                                   | cat      | 00:01:01.518932     | main.job-handlers.2 | 2     | 6144 |           | slurm
queued  | 4387 | 4012  | toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa_mem/0.7.17.2 | cat      | …
```
=> Add local queue function that displays cores/mem/partition info for jobs

group_vars/pulsar-nci-test/pulsar-nci-test_slurm.yml, group_vars/pulsar_mel2/pulsar-mel2_slurm.yml, group_vars/pulsar_mel3/pulsar-mel3_slurm.yml, group_vars/pulsar_paw/pulsar-paw_slurm.yml, group_vars/staging_pulsar_slurm.yml, group_vars/staging_slurm.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/pulsar_eu_gpu.yml
CR_CPU_Memory is already being used for the main cluster and qld high mems.
Add it to remaining slurm configs:
```
group_vars/pulsar-nci-test/pulsar-nci-test_slurm.yml
group_vars/pulsar_mel2/pulsar-mel2_slurm.yml
group_vars/pulsar_mel3/pulsar-mel3_slurm.yml
group_vars/pulsar_paw/pulsar-paw_slurm.yml
group_vars/staging_pulsar_slurm.yml
group_vars/staging_slurm.yml
host_vars/pulsar-high-mem1/pulsar-high-mem1.yml
host_vars/pulsar-high-mem2/pulsar-high-mem2.yml
host_vars/pulsar_eu_gpu.yml
```
=> add CR_CPU_Memory to all slurm configs

dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/DR.usegalaxy.org.au.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, pawsey_playbook.yml, staging_playbook.yml
move staging and production to 21.09, move dependency_resolvers configuration from host_vars/dev into group_vars/galaxyservers.
Not having cloudstor conf simplifies tool_config a fair bit.  We can use the list variable from ansible_galaxy:
```
galaxy_tool_config_files:
- "{{ galaxy_config_dir }}/tool_conf.xml"
- "{{ galaxy_config_dir }}/nagios_tool_conf.xml"
- "{{ galaxy_config_dir }}/local_tool_conf.xml"
- "{{ galaxy_config_dir }}/tool_conf_interactive.xml"
```
which is comma-joined into the `tool_config_file` setting in galaxy.yml
=> Update to release 21.09

pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml, pulsar-qld-high-mem_playbook.yml
A bwa_mem job has failed with 'no space left on device' on qld high mem pulsar 2.  I've copied the code to make symlinks between /tmp and /mnt/tmpdisk on the high mem pulsars
=> add symlink from /tmp to /mnt/tmpdisk on high-mem pulsars

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
There is a bug where some tools are getting mem values for a different rule.  This change sets mem for all of the lesser rules where there is a high-mem rule in the list of rules.  It may or may not patch it from our end.
=> put mem in all rules for tools with high mem rules

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
Test whether the vortex will reload
If it reloads, test the change that NG made to tpv yesterday that should save us from having to explicitly set mem of every rule for quast and other tools that have high mem rules.
=> test tpv changes: remove default mem for quast

host_vars/pawsey-job-nfs.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/pulsar-mel2/pulsar-mel2.genome.edu.au.yml, host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au.yml, host_vars/pulsar-nci-training/pulsar-nci-training.usegalaxy.org.au.yml, host_vars/pulsar-paw/pulsar-paw.genome.edu.au.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml, pawsey_playbook.yml
Pulsars would have a public key that would only accept ssh connections from pawsey.  pawsey would have the corresponding private key and this can replace the need for the more powerful keys to be used in maintenance tasks.  This also adds the public key to pawsey-job-nfs as this could be connected to for routine clearing of /mnt/tmp.
=> add internal ssh keys to production pulsars and job-nfs

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
8-core jobs on pulsar-paw are failing.  The native specification is asking for more memory than the 30500MB allowed per node.  This value could probably be higher in the slurm config but for now this is a quicker fix.
=> reduce mem per core for tools that go to pulsar-paw

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
In the end I did get rid of conda on the machine and reinstall it.  This is now running with mamba as the conda exec file but it would be easy to switch this back to conda.  The envs for high mem tools are installed and tool test results look fine.
=> remove offline tag for pulsar-high-mem1

files/galaxy/config/local_tool_conf_dev.xml
It's in `/mnt/galaxy/local_tools`, which is owned by root but if it had 777 permissions then non-sudo users could copy things to this.
=> add ipa to dev local tool conf

.github/workflows/check_tpv_config.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
There's a long standing bug with circos on slurm.  Before tpv it was running on pulsar-mel2 to avoid this.  It's ok on pulsar-mel3 as well.
=> change circos scheduling to require pulsar

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
Test jobs are all failing.  The trinity log has
```
Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 541: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
```
which might be a system problem rather than a conda problem.
=> set phm1 to offline again

dev-pulsar_playbook.yml, group_vars/pulsar_nci_training/pulsar-nci-training.yml, group_vars/pulsarservers.yml, host_vars/dev-pulsar.usegalaxy.org.au.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/pulsar-mel2/pulsar-mel2.genome.edu.au.yml, host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au.yml, host_vars/pulsar-nci-test/pulsar-nci-test.usegalaxy.org.au.yml, host_vars/pulsar-paw/pulsar-paw.genome.edu.au.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml, host_vars/staging-pulsar.usegalaxy.org.au.yml, pulsar-high-mem2_playbook.yml, pulsar-mel2_playbook.yml, pulsar-mel3_playbook.yml, pulsar-nci-training_playbook.yml, pulsar-paw_playbook.yml, pulsar-qld-high-mem_playbook.yml, requirements.yml, staging-pulsar_playbook.yml
Add miniconda to all conda playbooks and the option of using mamba instead of conda.  This is opt-in: `pulsar_conda_exec: mamba` must be set somewhere or conda will be used.
=> Add miniconda to pulsar playbooks, run with mamba if pulsar_conda_exec: mamba is set

group_vars/all.yml, group_vars/galaxyservers.yml, group_vars/pulsarservers.yml, pawsey_playbook.yml, staging_playbook.yml
I've tried this out on my VM.  cuffdiff does not resolve with conda but installs in a minute and a half with mamba.
In the past I've been setting the miniconda_version variable to anchor the conda version but this will not work when installing mamba into the base environment.  conda is in mamba's recipe so the latest conda is installed when mamba is installed.
=> Miniconda and mamba for galaxy

files/galaxy/config/object_store_conf.xml, host_vars/pawsey.usegalaxy.org.au.yml
`sudo systemctl reload nginx` needs to be run when this change is made, then once again after galaxy has restarted.  Test a pulsar job to check that it's returning files properly.
=> update file path and object store to use user-data-4

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
repenrich should be ok on mel2 and mel3 pulsars.  The environment was pre-installed with tbb=2020.2 and all of the tests pass.
TODO: make a pr to fix the conda recipe for bowtie=1.2.0 in bioconda to use tbb <= 2020.2
=> prefer pulsar for repenrich

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
mafft has been moved to high-mem but it doesn't seem scale.
=> send all mafft jobs to 2-core destinations

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
The default tool code uses the dict 'grafana_destinations' to map each destination id to the id that will come from the stats api. This is usually the same as the destination id. Because pulsar-qld-blast was not added to this dict there was an error in the ranking function. This change means it will default to the destination id if the key is not in the 'grafana_destinations' dict and new destinations can be added to destinations.yml without breaking anything.
=> default tool: only map destination ids when they are different from stats api + set pulsar-high-mem2 to offline

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
Some larger cdhit jobs have been failing with the error
```
Fatal Error:
not enough memory, please set -M option greater than 1266
Program halted !
```
=> more mem for cdhit_est

dev-workers_playbook.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml, group_vars/dev_workers.yml, group_vars/pawsey_workers.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, pawsey-workers_playbook.yml, requirements.yml, roles/acl-on-startup/README.md, roles/acl-on-startup/defaults/main.yml, roles/acl-on-startup/tasks/main.yml, roles/acl-on-startup/templates/start-acl.service.j2, staging-workers_playbook.yml
Update the geerlingguy.docker version from 2.6.0 to 4.1.3.  The new one has an option `docker_daemon_options` that we can use to move the images/containers/docker things off the root disk.
Add `enable_mulled_containers: true` and `enable_beta_containers_interface: true` to galaxy.yml on staging and production
Add a role acl-on-startup that copies start-acl.service to /etc/systemd/system and enables it.  This is a "hack" thanks to stackoverflow user Q23 https://unix.stackexchange.com/questions/372244/how-can-i-make-acl-settings-on-run-media-persistent
Add bionano_scaffold to vortex config to run on 16 cores on slurm
=> Docker and galaxy updates for docker enabled tools

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
multiple versions of busco are failing on pulsar-mel3.  Set scheduling for busco to reject the pulsar-mel3 tag for the time being
=> do not send busco jobs to mel3

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
using 3.3 means that each job gets slightly more than a quarter of the RAM and only three jobs can run at a time.  Reduce it to 3.1 so that a 4th job can fit.
=> reduce mem multiplier for blast pulsar jobs

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
send old busco versions to slurm.
TODO: there is probably a way to fix this in galaxy https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L219 because it seems to be broken because of a missing file in the working directory on pulsar
=> send busco v3 jobs to slurm only

files/galaxy/config/local_tool_conf_dev.xml
Singularity doesn't seem to like the symlink
```bash
FATAL:   container creation failed: mount /mnt/galaxy/local_tools/links->/mnt/galaxy/local_tools/links error: while mounting /mnt/galaxy/local_tools/links: mount source /mnt/galaxy/local_tools/links doesn't exist
```
=> use real path to links.xml

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
A user reported bugs with raven jobs: `[bioparser::Parser::Store] error: buffer overflow`.  Identical raven jobs have completed successfully on other high mem pulsars with identical conda environments.  The syslog contains I/O errors and the majority of jobs are failing, needs investigation.
=> set pulsar-high-mem1 offline due to disk errors

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
these settings are from when we were sending all high-mem jobs to _mid or _big destinations.  Switch these to 1/4 of a high mem machine each.
=> switch from 120 cores to 60 cores for busco, bwa_mem and quast

group_vars/pawsey_workers.yml, host_vars/pawsey.usegalaxy.org.au.yml
have custom-indices as a separate volume next to tools-indices on pawsey and the workers.
The next step is to refactor the pulsar mounts, find/replace text in /mnt/tools-indices/tool-data and change the custom-indices path in galaxyservers.yml.
=> mount custom-indices at /mnt/custom-indices on pawsey and workers

group_vars/galaxyservers.yml, group_vars/pulsar-nci-test/pulsar-nci-test_workers.yml, group_vars/pulsar_QLD/pulsar-QLD_workers.yml, group_vars/pulsar_mel2/pulsar-mel2_workers.yml, group_vars/pulsar_mel3/pulsar-mel3_workers.yml, group_vars/pulsar_nci_training/pulsar-nci-training_workers.yml, group_vars/pulsar_paw/pulsar-paw_workers.yml, group_vars/pulsarservers.yml, host_vars/DR.usegalaxy.org.au.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, one-offs/move_pulsar_custom_indices.yml, roles/pulsar-post-tasks/tasks/main.yml
- one-off playbook to move custom-indices down one level on pulsars
- mount custom-indices instead of tools-indices on pulsar workers
- galaxy_custom_indices_dir in galaxyservers for each galaxy host_vars file
staging and dev are not affected because they do not have any ref data
This depends on #658 being merged.
When switching over, before running the pawsey playbook I will need to run `find /mnt/galaxy/tools-indices/tool-data -type f -exec sed -i -e 's/tools-indices\/custom-indices/custom-indices/g' {} \;` to update the loc files
=> Change custom indices path on pulsars and in galaxyservers.yml

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
Add entries for funannotate_predict, eggnog_mapper and interproscan.  For now these are slurm-only because the reference data has not been copied to pulsars.
Update hyphy_gard to run on 1/2 a qld high mem pulsar
Set mafft back to 16 cores, add a rule that a user can only run 2 mafft jobs at a time
=> Add funnanotate tut tools and update destinations for mafft and hyphy_gard

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, templates/galaxy/config/dev_job_conf.yml.j2
draft rules for pulsar_azure_0 on dev:
placeholders ('???') for cores, mem and partition for bwa_mem, flye and trinity
all docker parameters set in tpv for alphafold
I did not want to delete the work done on singularity so there is a new destination pulsar-azure-0-singularity though no tools/users are mapping to it at the moment
=> tpv configuration for azure testing with multiple tools

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
the small, medium, large and special partitions need --nodes=2 --ntasks=X --ntasks-per-node=X/2 in the native specification.  They also have slightly less mem available than on the spreadsheet.
=> update rules for non-alphafold azure tools

host_vars/pawsey.usegalaxy.org.au.yml
once a week is better for capturing terminal job states
=> send grt data from pawsey once a week

terraform/aarnet-prod-pulumi/__main__.py
This is 1200 GB more than we previously had.  We have only been using the 1000 volume for /mnt/tools-indices and /mnt/ghost-galaxy-app.
This would be 1000 for shed_tools, tool_dependencies and singularity_cache
and 2000 for custom-indices (currently this size and half full on pawsey-misc-nfs)
=> change aarnet-misc volumes from 200 300 300 1000 to 1000 2000

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Hi @cat-bro 
This was [suggested by the developers](https://github.com/ComparativeGenomicsToolkit/cactus/issues/677#issuecomment-1063211195) as a workaround to the issue running Cactus with docker on dev.
I *think* Singularity mounts `/etc/passwd` by default but Docker doesn't.
Not sure if this is the right way to do it in TPV.
Thanks!
=> bind /etc/passwd in docker

templates/galaxy/config/pawsey_job_conf.yml.j2
@Slugger70 I'm 90% sure that this is the problem.  There are >40 jobs in queued+running and other jobs get assigned to slurm and remain in new state
=> allow more jobs to queue on slurm so that tiaas jobs do not bounce

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
kraken2 can go to pulsar but not pulsar-QLD yet because it needs ref data
pulsar-friendly tools such as rna_star can go to 8-core training destinations (pulsar-training-large tag)
=> kraken2 and shovill to pulsar, pulsar-training-large tags for some tools

group_vars/pulsar_paw/pulsar-paw_slurm.yml
pulsar-paw worker VMs have the same MemTotal values as pulsar-mel2 workers so they could have the same RealMemory value in slurm.  At the moment pulsar-paw jobs have `cores: mem * 3.7` instead of 3.8 but they could be using 3.8, same as everywhere else.
=> raise RealMemory on pulsar-paw workers

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
also fix pilon's java env variable so it's a function of available memory
=> let pulsar-paw tools use default mem ratio, coronaspades can run there too

dev-pulsar_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, group_vars/pulsar-nci-test/pulsar-nci-test_workers.yml, group_vars/pulsarservers.yml, host_vars/dev-pulsar.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pulsar-nci-test/pulsar-nci-test.usegalaxy.org.au.yml, pulsar-nci-test_playbook.yml, pulsar-nci-test_workers_playbook.yml
- Add container_resolvers to host_vars/dev
- Add docker and singularity roles to dev-pulsar and pulsar-nci-test
- Set bionano_scaffold to run with docker on pulsar and links to run on singularity with pulsar
The tools set to run on pulsar with singularity or docker have `require: ['pulsar']` in tpv because the singularity_volumes will be different between slurm and pulsar.  The directory structures are different and jobs will fail on pulsar with '$defaults'.  My idea of a for-now solution is to set tools to run either only on slurm or only on pulsar if they use containers.
There is also a caveat that to run a singularity job on pulsar the container must be deleted from galaxy's local container cache..
=> Docker and singularity for dev pulsars

files/galaxy/config/local_tool_conf.xml
The local canu wrapper is just an old version of canu with hardcoded GALAXY_MEMORY_MB.  There would be no reason for anyone to run it instead of regular canu.
Local tools on production could still be useful in future.  The 'test' label means the tool is hidden from anybody who is not an admin.
=> Comment out local_canu in local_tool_conf.xml

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
gecko jobs are failing on pulsar despite being green. Some hisat2 jobs with 15-20G input are being killed because they need too much memory.
=> tpv changes for hisat2 and gecko

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
This might be enough?  Another possibility would be to have some jobs go to low high-mem allocation such as 15 or 30 cores on high-mem but the current limits are set around the idea of all high-mem jobs being large.
=> 12 cores for rna_star

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
I think I need to bind `/cvmfs` for these tools because the tool uses reference genomes from the `all_fasta` table. Not sure if this is the right way.
Right now I'm getting a "file not found" error which suggests to me that the path isn't mounted when the container runs.
=> specify cvmfs bind

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
I think '$defaults' will only cover the current default data directory (user-data-4) 
I haven't included user-data-4 in docker_volumes here because it might break it.  TODO: test consequences of listing a directory twice on dev
=> bionano docker_volumes

aarnet-job-nfs_playbook.yml, aarnet-misc-nfs_playbook.yml, aarnet-user-nfs_playbook.yml, host_vars/aarnet-job-nfs.usegalaxy.org.au.yml, host_vars/aarnet-misc-nfs.usegalaxy.org.au.yml, host_vars/aarnet-user-nfs.usegalaxy.org.au.yml
Some updates to aarnet nfs playbooks.  For user-nfs there will be one giant volume instead of the smaller ones.  When the existing folders are copied over will they remain separate subfolders: user-data, user-data-2 etc?  I've chosen `/mnt` as the path for that volume on the machine but could change it to `mnt/data` to allow for future volumes at subdirectories of /mnt.
I've also added a 200G volume to the pulumi for misc-nfs.  Will check with aarnet tomorrow whether this will be OK.
=> aarnet nfs playbooks

hosts
aarnet-ftp has been added to this with a note that it is not used.
=> new host ips for aarnet

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Using an "env:" section in tpv will work as long as it's not docker_enabled.  Using the "env:" section in job_conf.yml does not work under any circumstances as far as I can tell.  For docker jobs, each variable can be appended to `docker_run_extra_arguments` i.e.
`docker_run_extra_arguments: "--env X=6 --env TEMP=warm"`
=> Alphafold limits: env vars for docker jobs are set in docker_run_extra_arguments

files/galaxy/config/local_tool_conf_dev.xml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Removing install from /mnt/galaxy/local_tools because cactus_cactus and cactus_export are on the toolshed now (https://toolshed.g2.bx.psu.edu/view/galaxy-australia/suite_cactus/5f4d0fc906ad).
I also updated the rules in vortex_config but maybe we don't need those any more?
=> Cactus on toolshed

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml, templates/galaxy/config/pawsey_job_conf.yml.j2
I thought it might be a better idea in terms of limits to have a separate destination for gpu work than normal work on azure. That way we can control the limits in a more fine grained manner.
=> Added a separate gpu destination with separate limits

aarnet-user-nfs_playbook.yml, group_vars/aarnet_workers.yml, host_vars/aarnet-user-nfs.usegalaxy.org.au.yml, host_vars/aarnet.usegalaxy.org.au.yml
This isn't ready until the `device` for /user-data-test is double checked
=> user-data-test on separate volume

dev_playbook.yml, group_vars/dev.yml
this is a hacky solution to something will need more thought when there is time.  Tool devs need sudo on dev, so this overrides `machine_users` in dev.yml.
=> sudo permissions for tool devs on dev

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Hi @cat-bro ! I'm not sure if this will work.
These protk tools have multiple entries in the `requirements` field, e.g.
```xml
<requirements>
<container type="docker">iracooke/protk-1.4.3</container>
<requirement type="package" version="1.4.3">protk</requirement>
</requirements>
```
**Only** the docker container works - the conda package and the biocontainer are broken.
I want to see if setting `use_singularity` in the vortex config will pull the container off docker hub or biocontainers... of if there's another way to do this without changing the wrapper
Also, one of the tools writes to its own installation directory in the container, hence the need for `'--writable-tmpfs'`
cc @mthang
=> try to force protk tools to use their docker container

host_vars/pawsey.usegalaxy.org.au.yml
I've commented out the cron job in ubuntu crontab on pawsey, this is to stop it setting it up again while pulsar-qld is connected to aaarnet
=> comment out pulsar-QLD cron job from pawsey config

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
pulsar-high-mem1 is offline in the tpv because the disk became read-only at some point today.  The disk is rw now but there has been a high rate of errors over the past few weeks compared to the qld high mem pulsars. I can look at the syslog tomorrow.
=> take pulsar-high-mem1 offline

group_vars/all.yml
The machines that need this are the galaxy head nodes because `gxadmin report job-info X` uses jq to unpack json fields
=> add jq to common packages

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml, templates/galaxy/config/pawsey_job_conf.yml.j2
bwa-mem2 needs more memory than would be allowed with a 16 core/ 62Gb.  It doesn't need 1Tb, more like 100GB
Also increase the number of queued jobs allowed at qld high mem pulsars from 4 to 6.
=> Give bwa-mem2 one eighth of a high-mem, switch pulsar-high-mem1 to online

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
xtandem has the same problem as protk_proteogenomics (https://github.com/usegalaxy-au/infrastructure/pull/770) - only the Docker container works.
=> use singularity for xtandem

files/galaxy/config/object_store_conf.xml, group_vars/galaxyservers.yml, host_vars/pawsey.usegalaxy.org.au.yml
Set uwsgi.processes to 5 (already in production config)
This needs a full playbook run because the location of the upload_store moves with the file path and nginx conf etc gets updated.  nginx needs to be reloaded from the pawsey machine command line after galaxy has restarted.
=> Switch galaxy file path to user-data-3

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/users.yml
I forgot to limit the count to queued and running jobs
=> fix high-mem rule for CB

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
bionano_scaffold docker_volumes uses $defaults and paths to user data volumes.  When the file path is changed this causes it to try to bind the same volume twice and the tool fails.
=> do not use $defaults in docker_volumes for bionano

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
chemfp worked on my machine using the biocontainer. Can I try it on dev to see if that bypasses the conda "PaddingError" issue? TBH I'm scared to go near that :)
ping @mthang
=> try chemfp using biocontainer

dev_playbook.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, roles/install-tpv/defaults/main.yml, roles/install-tpv/tasks/main.yml, staging_playbook.yml
install `total-perspective-vortex=={{ tpv_version }}` so no need to use `state: forcereinstall` anymore
This update is needed for #784 .  Once this is updated on dev, staging, and whatever production galaxy that can be rebased and merged.  The match -> if change is backwards compatible.
=> upgrade tpv and use versions instead of git commits

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/default_tool.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml, group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, templates/galaxy/config/pawsey_job_conf.yml.j2, templates/galaxy/config/staging_job_conf.yml.j2
Updated job conf to have destination parameters for docker and singularity.  In this setup a job destination could be pulsar-mel3 but would run with singularity only if the param `singularity_enabled: true` were set for the tool in the TPV.  The only parameter required would be `singularity_enabled`, everything else (`singularity_volumes` etc) lives on the job conf.  This has already been done on dev.
Every job will have in their destination parameters `singularity_enabled: False` or `singularity_enabled: True` and `docker_volumes` and `singularity_volumes`.  There is enough room on the destination_params field to have all of this data, and it's nothing in size compared to stdout/stderr for some jobs. 
An alternative design choice would be to have multiple destinations per cluster, i.e. …
=> Production singularity

templates/galaxy/config/pawsey_job_conf.yml.j2
only the files are on /mnt/tmp, singularity cache belongs in /mnt/pulsar
=> fix singularity cache dir on pulsar qld

group_vars/all.yml, host_vars/pawsey.usegalaxy.org.au.yml, pawsey_playbook.yml
Stick to conda=4.12.0 and mamba=0.23.3 and no longer automatically update conda with playbook runs.  This will have the advantage of making the playbooks run quicker.  pawsey already has conda version 4.13.0 so instead of downgrading this it can use conda instead of mamba.  aarnet and production pulsars still have conda version 4.12.0.   dev and staging have conda 4.13.0 so this will downgrade conda for them but hopefully it will be OK.  dev-pulsar was downgraded from 4.13.0 to 4.12.0 with no apparent ill-effects.
=> Exact conda and mamba versions in all.yml

host_vars/aarnet.usegalaxy.org.au.yml
singularity and docker volumes for aarnet.  These variables will be needed when the job conf is copied from pawsey.
=> context for aarnet job conf

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/users.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_job_conf.yml.j2, templates/galaxy/config/pawsey_job_conf.yml.j2, templates/galaxy/config/staging_job_conf.yml.j2
Set tpv version to 1.2.0 on staging, pawsey and aarnet.  Update rules that will now import from tpv instead of from vortex, temporarily comment these out until pawsey tpv has been upgraded.
=> Tpv upgrade 120 production

host_vars/aarnet.usegalaxy.org.au.yml
From side-by-side comparison of pawsey and aarnet host_vars
- uncommment usegalaxy and www.usegalaxy in certbot domains
- In interactive_tools_server_name and interactive tools certbot_domain, replace aarnet.usegalaxy with usegalaxy
- Set add_daily_stats and add_queue_info to true in stats role variables
- Set galaxy_infrastructure_url to https://usegalaxy.org.au
- Uncomment ga_code in galaxy_config
- Docker and grt-sender variables
=> [DO NOT MERGE UNTIL JUNE 22] Aarnet host vars production ready

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
The picard repository has ~30 tool wrappers and they all pass tests on pulsar.  None of them make use of GALAXY_SLOTS or GALAXY_MEMORY_MB in the wrapper.  This sets the env var `_JAVA_OPTIONS` to `-Xmx{int(mem)}G -Xms1G`
=> Common rule for picard tools

host_vars/dev.usegalaxy.org.au.yml, templates/galaxy/config/dev_job_conf.yml.j2
See if this configuration allows for user-data:ro to be preserved in singularity_volumes while being able to run featurecounts, chemfp etc with singularity
=> set outputs_to_working_directory: True on dev, override for all pulsars

group_vars/galaxyservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_job_conf.yml.j2, templates/galaxy/config/staging_job_conf.yml.j2
true in galaxyservers.yml, false for all pulsars.  This has fixed dev w.r.t read-only file directories for singularity.
=> Outputs to working directory set everywhere

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml
- remove high-mem rule from dev default user (this contains errors fixed in the production rule, besides, dev has no high-mem destinations)
- add test_user with the rule that any toolshed tool will run will run on singularity if the history has a 'singularity' tag.  All test user accounts inherit this rule.
I got this idea from Galaxy Main because testers were encouraged to add a 'training' tag to their histories to have their jobs run on priority resources.  This seems like a neat way to control a job destination from the outside.  I'm not suggesting anything like this for general users, just for test user accounts that only we have access to.
=> Test user jobs run with singularity enabled if history has 'singularity' tag

host_vars/dev-queue.usegalaxy.org.au.yml, templates/galaxy/config/dev_job_conf.yml.j2
update rabbitmq version on dev to 3.10.5-1 because there were erlang clashes when running the playbook.
=> new rabbit for dev-queue, add runner and destination to job conf

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
@Slugger70 When I copied the destination from the original, I included `offline: true` and that's why tpv couldn't find a matching destination earlier.
=> the new pulsar azure on dev  was offline

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/default_tool.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
the native spec parameter becomes
`nativeSpecification: "--nodes=1 --ntasks={cores} --ntasks-per-node={cores} --mem={round(mem*1024)} --partition={partition}"`
on default tool and partition is overridden on alphafold tools to azuregpu1
=> Update default tool on dev to have partition in context

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
Setting pulsar qld high mem 2 to offline so that jobs scheduled there can be restarted.  There is no slurm data for it on grafana and I can't ssh to it.  One of the running jobs is mothur_cluster_split - I won't restart this one.
=> Set pqhm2 to offline

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
If this works as expected, the url_paste* file will be created within a subdirectory of the job working directory and no url_paste* file will be created in the worker temp disk.
=> Set tmp_dir param for dev data fetch

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This will stop url_paste* files accumulating in the worker temp dirs and overflowing onto the workers' root disks.
=> Set parameter for  __DATA_FETCH__ to store its temp files within the jwd

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
phm1 was set offline because the disk was read-only, it must have been remounted or the vm rebooted since then because it is OK now.
=> Revert "set phm1 to offline"

.github/workflows/check_tpv_config.yml
Close to switchover the CI check was looking at both aarnet and pawsey job conf files, this is not needed anymore
=> No need to check tpv against pawsey job conf in CI check

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, templates/galaxy/toolbox/filters/ga_filters.py.j2
Changes for new alphafold pulsar and group 'UoM_Vet_Alphafold'
I believe that if a user is a member of both 'Alphafold' and 'UoM_Vet_Alphafold' then the last matching rule will apply and their jobs will go to the 'UoM_Vet_Alphafold' pulsar.
The toolbox filter will require a playbook run in order to work for members of 'UoM_Vet_Alphafold' that are not already members of 'Alphafold'.
=> Uom vet alphafold tpv rules

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
As a member of both groups I cannot run alphafold
=> Fix alphafold rule for members of both groups

group_vars/staging_workers.yml, staging-workers_playbook.yml, terraform/staging/staging-initial.tf
Add a 100G volume at /dev/vdb on staging-w1
Terraform was not used - I've written a note in staging-initial-tf.  For some reason terraform is not seeing that the VMs exist despite their being in the state file.  I might need to throw it out and repopulate it using `terraform import`.
=> Add volume to staging-w1

templates/galaxy/config/aarnet_job_conf.yml.j2, templates/galaxy/config/dev_job_conf.yml.j2, templates/galaxy/config/staging_job_conf.yml.j2
The container_resolvers overrides in pulsar destination parameters should have entries for `mulled_singularity` instead of `cached_mulled_singularity` now that containers are not being sourced from cvmfs.
=> Fix container_resolvers for pulsars in job conf

templates/galaxy/config/aarnet_job_conf.yml.j2
At the moment this is used for `__DATA_FETCH__` which means that tool no longer causes the worker tmp disks to overflow.
I can't think of what could go wrong with this, however
@Slugger70 would there be a greater overhead for the workers storing temp things on the NFS mounts instead of on the mounted /mnt/tmpdisk disks?
=> Set tmp_dir: True for all destinations, meaning temp files will be in subdirectories of the job working directories

files/galaxy/config/pawsey_object_store_conf.xml
added missing tag in pawsey_object_store_conf.xml
=> fix missing closing tag in object store config

dev_playbook.yml, host_vars/dev.usegalaxy.org.au.yml, templates/galaxy/config/dev_object_store_conf.xml.j2
Replicate the production object store setup on the dev with the aim of migrating this to a distributed object store with new datasets being stored by UUID. The old directories would have weight 0 meaning that nothing would be written to them.
=> Give dev a hierarchical object store

group_vars/galaxyservers.yml
The cached_explicit_singularity resolver is new as of release_22.01. Before this, the explicit singularity containers were not being stored.
=> Add cached_explicit_singularity to container_resolvers

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml
All busco 5 versions can run with singularity containers.  This has been tested on slurm and most of the pulsars with the latest version of busco and the tests are OK.
Add tpv rules for cuffdiff, also singularity_enabled and OK on pulsar.
Reduce rna_star cores from 12 to 8.  It was increased to 12 a few months ago to solve a problem that turned out to be due to squid+cvmfs, so the increase was not necessary.
=> Run busco and cuffdiff with singularity, reduce rnastar cores to 8

aarnet_playbook.yml, aarnet_update_configs_playbook.yml, templates/galaxy/toolbox/filters/ga_filters.py.j2, templates/galaxy/toolbox/filters/test_ga_filters.py
Stop cloning galaxy-local-tools/tools-au because it hasn't been useful.  If needed, individual users can clone it into /mnt/galaxy/local_tools which will be made writable by all machine users.
Extend the test_tool_user filter for allowing non-admin users access to test tools
We can define a list of id/role combinations
```
{
'id': 'maxquant_test',
'role': 'maxquant_test',
},
```
which will extend the visibility of tool with the 'test' label to anyone with a role, for a given tool id.
Add a test file for the toolbox filters.  This is checking the logic but mostly it is checking that the code runs.
=> Extend toolbox filter for test tools

dev_playbook.yml, host_vars/dev.usegalaxy.org.au.yml, scripts/set_object_store_id.py, templates/galaxy/config/dev_job_conf.yml.j2, templates/galaxy/config/dev_object_store_conf.xml.j2
Dev object store has been changed from hierarchical to distributed, with new objects stored by uuid.  There is also a script for updating dataset and metadata_file database objects to have object_store_id values which is needed when migrating to the distributed object store.
=> Dev distributed object store

.gitignore, jenkins/config_backup/config_backup_playbook.yml, jenkins/config_backup/run_backup.sh, jenkins/requirements.txt, jenkins/update_labels/update_tool_labels.sh, jenkins/update_tool_destinations.sh, jenkins/utils.sh
Add config backup playbook to this repo. It has been running in its own gitlab repository but the hosts file goes out of date every time an IP address changes so it's better to use the source-of-truth host file in this repo.  The backed up files still go to the 'configs' gitlab repository.
Every jenkins ansible job can use the same virtual environment (/var/lib/jenkins/jobs_common/.ansible_venv), previously each one had its own venv.
=> Common ansible env for jenkins jobs, add config_backup playbook

templates/galaxy/config/dev_job_conf.yml.j2
`metadata_strategy: 'extended'` is causing pulsar jobs to fail on dev.  Will need to find out more about this setting before it can be used
=> comment out metadata strategy in dev job conf

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, host_vars/dev.usegalaxy.org.au.yml
There are several data directories on dev now that have not been accounted for in the docker/singularity volumes list.  This also adds a rule for hifiadaptorfilt so that I can test it now on slurm without interrupting current users.
=> Fix dev docker/singularity volumes

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There are errors running this on pulsar, it is OK on slurm.
=> schedule bionano_scaffold to slurm only

host_vars/dev.usegalaxy.org.au.yml, templates/galaxy/config/dev_object_store_conf.xml.j2
On dev, the aws storage is causing pulsar jobs with large outputs to fail.  Including the path to it in singularity_volumes causes all singularity jobs on slurm to fail.
There may be workarounds, this PR is just to stop using it as the primary storage for now.  Any singularity jobs using files created in the past two weeks will not work unless the datasets are copied.
=> Stop using AWS as rw dir in object store, omit /mnt/test_mount from singularity volumes

ansible.cfg, dev_update_configs_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/reservation_destinations.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, host_vars/dev-queue.usegalaxy.org.au.yml, templates/galaxy/config/dev_job_conf.yml.j2
dev-queue host_vars was missing the vhosts for the reservation pulsars
dev_update_configs playbook restart handler has been updated to use galaxyctl
reservation destinations in job conf have their singularity variables commented out because the container_resolvers override interacts badly with docker (with a TODO to refactor destinations)
TPV has been updated so that bionano prefers reservation pulsars and there is a user who can test alphafold on the reservation pulsar
=> Fix vhosts and destinations for reservation pulsars

dev-workers_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, group_vars/dev_workers.yml
A user who inherits test_user can select s3fs or cvmfs using history tags.  The cache sizes have been changed so that each worker has 5000Mb
=> Set up TPV for s3fs testing

roles/jasonroyle.rabbitmq/tasks/Debian/install.yml
Configure apt to set erlang version to fixed (hold) so that it doesn't get updated. As per request from @Slugger70
=> configure apt to set erlang version to fixed - no updates

jenkins/update_labels/hidden_tools.yml
Hide jmoleditor from chemical_data_sources, it is an old repo and clicking on this tool from the panel leads to a 404 page.  It is installed because another wrapper from the repo is needed for GTN.
Hide sra_pileup from sra_tools.  This wrapper was dropped from the repository at the beginning of 2020 and hasn't worked on GA since before pawsey.
=> hide two tools that are not working

files/galaxy/config/additional_datatypes_conf.xml, host_vars/dev.usegalaxy.org.au.yml
Add an extra datatypes conf file.
Set terms_url in galaxy.yml. This value is used in account registration emails.
=> Add extra datatypes conf to dev and set terms_url

aarnet_playbook.yml, staging_playbook.yml
the restart handler is no longer triggered with the updated galaxyproject.galaxy role
=> Add `listen: restart galaxy` to staging and aarnet playbook restart handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
pulsar-nci-training needs to be able to run a job that would have gone to high-mem if the user were not in the training queue.
=> training pulsar should tolerate high-mem tag

jenkins/update_labels/hidden_tools.yml
Requested by Igor.  sra_pileup is in the hidden tools list but it needs to cover all versions.
=> Hide any version of sra_pileup

templates/galaxy/config/aarnet_job_conf.yml.j2
The key `user_total_concurrent_jobs` should be `destination_user_concurrent_jobs`, this mistake has been copied over from the pawsey job conf. Set alphafold limit to 2 concurrent jobs per user.
=> Fix user limits for pulsar-azure-gpu and pulsar-QLD

host_vars/pulsar-QLD/pulsar-QLD.genome.edu.au.yml, roles/pulsar-post-tasks/tasks/main.yml
Add variable pulsar_custom_indices_src_dir, only create symlink if this exists
This also adds it as /mnt/tmp/custom-indices on pulsar-QLD.  Not sure if this fits with the architecture of the DR site.. we may want /mnt/custom-indices to be its own 2T volume instead.
=> Add the option to symlink custom-indices folder in pulsar-post-tasks role

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
mothur-cluster-split jobs would only be able to run on qld-pulsar-high-mem0
=> set phm1 and phm2 online, restrict destinations for mothur_cluster_split

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
Prod TIaaS is not loading static files because the `tiaas_info.domain` variable has been set incorrectly (not your fault really, the name is misleading - fixed in new release).
[Take a look](https://usegalaxy.org.au/tiaas/) and you'll see that static files are not loading. I'm not sure why this stopped working now but this PR should fix it.
=> Fix tiaas vars

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
We set this up a couple of weeks ago so that mothur_cluster_split high mem jobs would go to qld 0.  I forgot that qld 0 was already the sole destination for maxquant test.
Send mothur_cluster_split jobs to phm2 instead.
=> Change only destination for mothur cs from phm0 to phm2

requirements.yml
Update galaxyproject tiaas2 requirement to 2.12.  It's important that we merge this and `ansible-galaxy install -p roles -r requirements.yml -f` before the playbook is next run.  @neoformit would like to be nearby when we run this.
=> Update galaxyproject.tiaas2 requirement

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
@igormakunin detected a cactus job running for >30 days on GA. I ran the same job on HPC and it finished in 3 days but used a lot more RAM than I had configured on GA.
For the record
```
Cores per node: 36
CPU Utilized: 49-05:39:43
CPU Efficiency: 67.84% of 72-13:51:36 core-walltime
Job Wall-clock time: 2-00:23:06
Memory Utilized: 117.82 GB
```
=> cactus needs more ram

roles/common/tasks/machine_users.yml
gxctl no longer works on dev because the bash function is setting GRAVITY_STATE_DIR={{ galaxy_root }}/gravity instead of {{ galaxy_gravity_state_dir }}
=> Use galaxy_gravity_state_dir param in gxctl

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml
msconvert probably doesn't need anything above the default cores/ram but it must run with `docker_enabled: True`
=> Add rule for msconvert

templates/galaxy/config/dev_job_conf.yml.j2
Each destination in dev_job_conf.yml has been given a tag `registered_user_concurrent_jobs_1` except slurm which has been given the tag `registered_user_concurrent_jobs_6`, then the limits are defined as 1 and 6 respectively depending on the tags.  This should mean there is a limit of one job per registered user unless the job is running on the slurm destination, in which case there could be 6.
=> Bypass registered_user_concurrent_jobs on dev using tags

templates/galaxy/config/aarnet_job_conf.yml.j2, templates/galaxy/config/dev_job_conf.yml.j2, templates/galaxy/config/staging_job_conf.yml.j2
The number of retries for InvalidJobException and InternalException defaults to 0, which is why the jobs failed so quickly this morning with this error in the handler logs
```
galaxy.jobs.runners.drmaa WARNING 2022-10-23 21:39:04,495 [pN:handler_0,p:2426728,tN:SlurmRunner.monitor_thread] (4912303/674752) unable to check job status because of InternalException exception for 1 consecutive tries: code 1: slurm_load_jobs error: Resource temporarily unavailable,job_id: 674752
galaxy.jobs.runners.drmaa WARNING 2022-10-23 21:39:04,495 [pN:handler_0,p:2426728,tN:SlurmRunner.monitor_thread] (4912303/674752) job will now be finished OK
```
I've copied params from Galaxy Main's job conf where they set the value to 5 for each kind of error.
=> Error retry values for slurm job runner

templates/galaxy/config/aarnet_job_conf.yml.j2
Remove the limit with type `registered_user_concurrent_jobs` because it is a hard limit to 10 jobs per user no matter what.  Replace it with two limits of type `destination_user_concurrent_jobs` set to 10 for tag `registered_user_concurrent_jobs_10` and set to 25 for tag `registered_user_concurrent_jobs_25`.
The only destination with the `registered_user_concurrent_jobs_25` tag is pulsar-azure-1-gpu.
TODO: make this more abstracted in the job conf: tags and limits could be templated variables.
Also TODO: tags could be set through TPV, I don't think that's possible yet.
=> Set user concurrent jobs through tags on destinations in aarnet job conf

host_vars/aarnet.usegalaxy.org.au.yml
Igor has requested that the restriction on "days until event" to be removed on TIaaS submissions. We frequently have submissions for events that start tomorrow and we're OK with that.
=> Remove notice restriction on tiias application

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
The rule for mothur had the wrong tags, so jobs have been going to all three qphms. Set qphm2 to offline to be rebooted, since nothing is running there.
=> Correct mothur rule, set qphm2 offline to reboot

hosts
w2 is commented out in the host file because its volume cannot be destroyed nor attached to the new instance.
=> Update pulsar-nci-training worker IPs

hosts
w2 needs to be excluded from the workers when the playbook is run, but it must exist in the host file for other parts of the playbook to not fail
=> Include training node w2 in host file, outside nci training workers group

jenkins/update_labels/hidden_tools.yml
Future people will need to either:
* encourage usegalaxy.* and GTN to move away from using mothur_cluster_split or
* unhide this tool with very specific limits in tpv so that jobs fail above the input size used in the GTN tutorial.
=> Add mothur cluster split to hidden tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml
Add a context variable to the default tool `test_cores` which is 1 unless overridden.  There are only two tools I can think of that need this value to be >1
=> Allow setting higher cores/mem for tool tests

files/galaxy/config/user_preferences_extra_conf.yml
Removes the owncloud urls as they need not be user selectable, and don't really have meaning to end-users.
=> Remove owncloud urls as they need not be user selectable

files/galaxy/config/tool_conf.xml
The Send Data -> Send tools is not displaying because the path has changed.
SIFT, PhylOP and aaChanges do not display and cause errors in the logs because their loc files cannot be found.  If we were to point them to the sample loc files from the code base, the tools would show up but they would be unusable because the sample loc files are empty.
=> Change path of Send tool, remove builtin tools causing errors in logs

host_vars/aarnet.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_object_store_conf.xml.j2
This is a routine change to update galaxy to use /mnt/user-data-6 (the new 50T volume) as the primary user data location.
The current volume is approaching 95% capacity.  Once this is merged, we will need to run the full aarnet playbook, restart galaxy and reload nginx. Implementing the change can wait until after today's Galaxy meeting.  I'll go through these changes with @jlqfab.
=> Update object store to use /mnt/user-data-6

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Adjust tpv config so that 0.5-10G flye jobs have 16 cores and the pulsar-training-large jobs are given the minimum of 16 cores and the number of cores they would have outside of training groups.
The pulsar-training-large change from 8 to 16 cores is a temporary fix for today's workshop.  There are ways the roles.yml config could be changed to make it more flexible but I favoured this solution for now because it won't break anything.
=> Adjust flye and training rule

templates/nginx/galaxy-dev.j2, templates/nginx/galaxy.j2
This adds a non-standard header, that was inspired by the Discworld series, and is used on other sites. There a series of towers are used to constantly re-transmit the memory of a lost son, throughout a network. Inspired by this many servers serve a similar header with memories of lost comrades (including Sir Terry Pratchett, the author).
Simon was a huge fan of the Discworld series as well, having read them multiple times over, and I think this is a good way to remember him.
> In Sir Terry's novel "Going Postal", the story explains that the
> inventor of the Clacks - a man named Robert Dearheart, lost his only son
> in a suspicious workplace accident, and in order to keep the memory of
> his son alive, he transmitted his son's name as a special operational
> signal through the Clacks to …
=> Add x-clacks-overhead

dev_update_configs_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Default destination is abstract (jobs cannot go there) and has rules that add params if singularity_enabled is true.
_pulsar_destination is abstract and has rules that add params if singularity_enabled is true.
For some reason the singularity rules for _pulsar_destination were not being applied to the job destination until I commented out the rules for the default destination.  So far I haven't been able to reproduce this in tpv tests, so there might be a typo in this config that I am missing.
=> amendments to dev tpv2 rules

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add bakta and vcf2maf as slurm only for now.  Update rgrnastar to use 12 cores/ 12*3.8G
=> TPV: add bakta and vcf2maf, update rgrnastar

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/destinations.yml.j2
Destinations need to accept `singularity` and `docker` tags because some tools from the shared database require them
=> add docker and singularity tags to all dev destinations, add debug rule to default tool

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Set clinker to singularity enabled (default cores)
Set gtdbtk_classify_wf to 32 cores + singularity enabled
=> gtdbtk and clinker entries for tpv

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
Pulsar-paw needs to be taken offline prior to the Pawsey maintenance beginning Friday 8am AWST.
=> take pulsar-paw offline for Pawsey maintenance

dev_playbook.yml, host_vars/dev.usegalaxy.org.au.yml
Set value for SINGULARITY_CACHEDIR on dev so that space is not taken up in /home/galaxy/.singularity.
Every time a new tool is run with singularity it is causing a fair bit of space to be used on the head node root disk, so if this setup works I'll copy it on staging + production.
path name is '/mnt/singularity_data' so that it sits alongside '/mnt/docker_data' (the place that docker things go to instead of the root disk)
=> galaxy singularity cache data to go to /mnt/singularity_data on dev

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
update alphafold_test tool for new cluster.  `azuregpu0` partition is for regular alphafold jobs and `azuregpu1` is now only for vet school jobs.
=> update alphafold test to use azuregpu0 partition

host_vars/dev-handlers.usegalaxy.org.au.yml
The dev job handlers need to know about the singularity cachedir in order to use it.  I've copied these into the dev-handlers vars with notes on what to keep when rebasing #1110 later on.
=> Copy singularity cache variables to dev-handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There are some jobs running with input size just under 0.2G (the current threshold) and they are running for hours with default resources. They should probably be in the 8 core/8*3.8G mem bracket.
=> Update small job size threshold for unicycler

dev-handler_playbook.yml, dev_playbook.yml
Add singularity cache dir creation to the dev-handlers playbook.  This is just another path on the root disk but will show whether moving the cache works.
Also updated dev and dev-handler playbooks: Reenable handlers, stop cloning galaxy-local-tools, remove check for data_fetch tmp directory as this is not needed, remove post task to set acl in favour of acl-on-startup role
=> Add singularity cache folder creation to dev handlers playbook, clean up post tasks

dev-handler_playbook.yml, dev_playbook.yml, host_vars/dev-handlers.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml
A lot of variables for dev are in two places (host_vars/dev.usegalaxy.org.au and host_vars/dev-handlers.usegalaxy.org.au) and it is difficult to keep these in sync.  This changes host_vars/dev-handlers to be a small file with only what needs to be added/overwritten from the contents of host_vars/dev, then host_vars/dev is included in vars files for the dev-handlers playbook.
=> Dedup dev server variables

one-offs/conda_envs/conda_environments.yml
Add amendment for sam_pileup conda environment to a list of conda environments that require extra packages
=> add sam_pileup to conda environments list

group_vars/aarnet.yml, roles/common/tasks/add_hosts.yml, roles/common/tasks/main.yml
Put the 'add hosts' tasks in their own file and run them twice if a variable 'hosts_template_file' is defined.
=> Add hosts to hosts template file on aarnet VMs

roles/common/tasks/add_hosts.yml
The regex pattern was allowing 'x.x.x.x aarnet.*' to match entries for other hosts such as aarnet-queue
=> fix regex in add_hosts.yml

host_vars/dev.usegalaxy.org.au.yml
this adds the tpv package to `galaxy_additional_venv_packages` to be installed straight after conditional dependencies in the galaxyproject.galaxy role. This means that during the playbook run the tpv version is put down to 1.4.1 then upgraded to 2.0.1 which is uncool but probably harmless.
=> dev tpv: work around galaxy requirement of version <2

roles/common/tasks/main.yml
From official instructions [here](https://github.com/influxdata/telegraf/blob/master/README.md#package-repository) plus Jeff Geerling's [post](https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible) recommended by JL
=> Add apt key for influx to common role

host_vars/aarnet.usegalaxy.org.au.yml
ubuntu_maintenance_key public key has been added to pulsar-azure and this key will only be accepted for aarnet's IP.
=> Add cron job for deleting old jwds from pulsar-azure

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Error is `Read-only file system @ rb_sysopen`.  These tools need `writable-tmpfs`   so their installation directories don't appear read only. We did this on dev too.
https://github.com/usegalaxy-au/infrastructure/pull/1173
=> add writable-tmpfs

host_vars/aarnet.usegalaxy.org.au.yml
There's a draft PR to upgrade to 2.x which is not ready yet. An update to 1.4.1 is needed sooner to fix a bug.
=> upgrade total-perspective-vortex to 1.4.1

roles/common/tasks/machine_users.yml
It is not enough to run /mnt/galaxy/venv/bin/galaxyctl, the venv must be active where galaxyctl is run to pass it onto child processes.
=> Fix gxctl function

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
Slurm destination's max allowed mem in tpv is 121.25, less than 121.6 mem set for a 32 core job (32 x 3.8)
The new value is based on MemAvailable for aarnet-w10
=> Update slurm destination max allowed mem in tpv

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml
pulsar-qld-blast and pulsar-qld-high-mem0 no longer need to be offline.
=> Set pqhm0 and pulsar-qld-blast online, sort out pulsar-blast tag logic

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, group_vars/aarnet_slurm.yml
The slurm partition max_quant_w8 started off as a priority queue for maxquant because no other jobs could run there. When galaxy became more busy, the w8 worker was added to the main queue so it became difficult for maxquant jobs to get a place to run. This PR removes the max_quant_w8 partition and puts some limits on the maxquant tool in tpv to stop it from taking over slurm.
Note: this has no effect the local maxquant_test tool which is subject to different rules.
=> Remove max_quant_w8 partition and limit maxquant in tpv

aarnet-user-nfs_playbook.yml, group_vars/aarnet_workers.yml, host_vars/aarnet-user-nfs.usegalaxy.org.au.yml, host_vars/aarnet.usegalaxy.org.au.yml
Add /mnt/user-data-7 to aarnet-user-nfs and its nfs exports, mount it on aarnet head and workers
When user-data-6 is 90-95% full, user-data-7 should be added as the first entry in the object store config
=> Add user-data-7 to aarnet-user-nfs

group_vars/galaxyservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, roles/slg.galaxy_stats/defaults/main.yml, roles/slg.galaxy_stats/templates/current_stats.sh.j2, roles/slg.galaxy_stats/templates/daily_stats.sh.j2, roles/slg.galaxy_stats/templates/secret.yml.j2
A variable called db_password is being set within the pg-post-tasks role and overriding 'db_password' the stats role variable.
This also adds a commit_id for gxadmin: this can probably be deleted later on or updated every now and then with releases.
=> Give db params in stats role more specific variable names

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add a tag to prevent tools unsuitable for training destinations from being sent there. Instead the destination is unchanged regardless of whether the user is part of a training group.
=> Add training-exempt tag for alphafold and interactive tools

roles/common/tasks/machine_users.yml
Rather than removing the code block that chown's the contents of user directories, simply don't follow symlinks. This prevents the destination of the symlink from being chown-ed.
=> fix issue of destination of symlinks in home directories being chowned

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This still does not work - there is something wrong with the rule for tools with 'pulsar-training-large' and not 'training-exempt', they are left with nowhere to go.
=> Revert roles change

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Pulsar is not transferring all of the files back for quast jobs. This needs further investigation but in the meantime it should not run on pulsar.
=> Make quast a slurm-only tool

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Some tools in tpv-shared-db have high memory and without a pulsar tag won't have anywhere to run. Some can run on pulsar in which case they get a pulsar tag. Some can't in which case they need a lower amount of memory than is set in the shared db.
This is a quick fix. Long term there is interest in using pulsar tags in shared-db.
=> High memory tools from shared db need pulsar tags or lower memory

group_vars/aarnet_slurm.yml, host_vars/aarnet.usegalaxy.org.au.yml
The slurm training queue is full and there is another workshop starting.  Limits can be increased since the capacity of the slurm cluster is much higher than when these were set.
=> Add w10 to training partition and increase concurrent job limit for slurm-training

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Drop AlphaFold version from `v2.3.1_2+` as will be set in tool XML from hereon.
=>  TPV entry for AlphaFold v2.3.1_2+

files/galaxy/config/tool_conf.xml
A user has requested presto tools from IUC. Galaxy Europe does not have these. Galaxy Main does, in their own section named pRESTO.
=> Add pRESTO tool section

group_vars/galaxyservers.yml, roles/common/tasks/main.yml
galaxy release_23.0 requires an upgraded version of gravity that fails to start galaxy without the $GALAXY_CONFIG_FILE env var set.
=> For gravity v1.x galaxy user needs GALAXY_CONFIG_FILE env variable set

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
eggnog db has been copied to /mnt/custom-indices on mel2 and nci-training (it was already on mel3). Test jobs are OK.
=> Allow eggnog to run on pulsar-mel2, pulsar-mel3

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
pulsar on pulsar-mel2 is behaving strangely with eggnog. Each submitted job results in the conda virtual environment being destroyed and recreated. Many jobs are being submitted and the virtual environment is liable to be destroyed at any time, so some of the jobs are failing. Worth debugging later. pulsar-mel3 is fine.
=> Stop sending eggnog jobs to pulsar-mel2

aarnet_update_configs_playbook.yml, dev-handler_playbook.yml, dev_playbook.yml, dev_update_configs_playbook.yml, staging_playbook.yml, staging_update_configs_playbook.yml
For 23.0, everything that restarts galaxy needs `GALAXY_CONFIG_FILE` set
=> Add GALAXY_CONFIG_FILE env var to playbook handlers and gxctl

dev_playbook.yml
this is a quick fix. The proper solution is to have a gravity config file, which has not been an option with previous galaxy versions.
=> override galaxyctl update handler in dev playbook

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Store tmp files in the job working directory for sort1 jobs.
=> Use tmp_dir for sort1 tool

host_vars/staging-db.usegalaxy.org.au.yml
There have been problems with jobs on staging since upgrading to release 23.0. It is difficult to debug because the database  keeps running out of available connection slots.
=> Increase max_connections for staging db

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
An IMPORT_HISTORY job has filled up the temp volume on one of the workers, so it needs to use the job working directory for temp space instead.
=> IMPORT HISTORY tool needs tmp_dir: true parameter

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add singularity_enabled for some smorgasbord tools that have failed to be installed using conda dependencies.
=> add singularity_enabled entries for new gtn tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
snippy can create a bunch of samtools tmp files, too many for the 100G disk
=> set tmp_dir: true for snippy

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
waiting on info about whether the problem jobs work for non-training users
=> Give kraken2 training-exempt tag to allow it to run on slurm or pulsar-mel3

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
conda throws errors when trying to install new conda environments. Existing ones are OK but there are too many job failures from tools running that pulsar-QLD has not seen before, e.g. porechop. It seems that Galaxy is not too busy to take this offline overnight.
=> Set pulsar-QLD to offline

host_vars/dev.usegalaxy.org.au.yml
This was working on dev for 6 months or so: some small jobs such as uploads would be handled by celery instead of passed to slurm workers. Switching it off because jobs upload jobs are remaining in new state indefinitely. This is not used on staging/production.
=> disable celery tasks on dev

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
Use process_manager: systemd for staging: no longer using supervisor.
tusd is listed in the gravity section instead of it having a service set up by the ansible role. Gravity sets up the service galaxy-tusd and the old service tusd-main has been stopped and should be removed.
The path for the toolbox_filters folder in the galaxy codebase has changed mid-release.
=> Use process_manager: systemd for staging

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
From a recent bug report it looks like alphafold jobs sometimes run out of space in /tmp on the cyclecloud workers. This change moves temp space to the job working directory in the 1T volume.
=> Set tmp_dir: true for alphafold

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, host_vars/aarnet.usegalaxy.org.au.yml
Send all kraken2 jobs to high memory pulsars because of a large db in cvmfs that is either new or people have only now started using it.
Antismash can run on pulsar and would also go to high memory pulsars.
Reduce allocations for some tools. Tools targeted for this are ones that have had 120 cpu / 2TB allocations. This is not across the board, some have been left as they are. It's necessary to reduce some of these because the high memory pulsars are prone to bottlenecks and a greater number of tools are going to need to run there.
=> Send kraken2 and antismash to high memory pulsars, reduce some high memory allocations

.github/workflows/check_tpv_config.yml
tpv lint commands throws errors, probably due to a new version of galaxy-app released yesterday. Pin it to the previous version.
=> Pin galaxy-app version in linting workflow

files/galaxy/config/themes_conf.yml, group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml
Add themes_conf.yml, copied from the sample file in galaxy code. We might need to edit the rainbow theme to stop the word 'Australia' overlapping with the stripes and being difficult to read.
=> Add themes_conf.yml, enable themes on 23.0

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
A htseq job has filled up /var/tmp on one of the QLD workers. A lot of tool wrappers use `${TMPDIR:-/tmp}` but htseq_count's wrapper has no default.
=> Set TMPDIR environment variable in destinations.yml.j2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Still trying to get TMPDIR set properly in htseq_count. It is running with singularity enabled.
=> Add SINGULARITYENV_TMPDIR to destination env vars

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Previous attempts to fix htseq_count with environment variables have failed. This might work but it is annoying if we can no longer set env variables for singularity jobs.
=> Try setting env var for htseq_count through `singularity_run_extra_arguments`

dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, staging_playbook.yml
It seems that the gie-proxy role is no longer required and gravity will start this up as a service.
=> List gx_it_proxy as a service on dev, staging and reduce number of job handlers on staging

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Get tmp files to be stored in the job working directory for htseq_count. Hopefully this will work. It would be preferable to work out how to set environment variables reliably for singularity jobs, but it is not worth spending any more time on this tool.
=> give up on telling htseq_count where to send its tmp files

aarnet_playbook.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, roles/webhooks/defaults/main.yml, roles/webhooks/tasks/copy_webhooks.yml, roles/webhooks/tasks/main.yml, templates/galaxy/webhooks/subdomain_switcher/config.yml.j2, templates/galaxy/webhooks/subdomain_switcher/styles.css.j2
This PR will deploy the "genomes lab" subdomain, the `webhooks` role and the `subdomain_switcher` webhook (masthead icon) to aarnet/prod. It also applies some updates to these roles on dev and staging.
Run the aarnet playbook with `--extra-vars "certbot_expand=true"` to force certbot to create a new certificate that includes the `genome.usegalaxy.org` domain.
The webhooks role will notify `restart galaxy` - please make sure that galaxy restarts for the `subdomain_switcher` webhook to take effect. It should look like this (live on staging):
=> Deploy genomes lab to AARNet

roles/common/tasks/machine_users.yml
Remove the gxctl function. It was a convenience function for running galaxyctl as the galaxy user with the venv active. It is outdated now with systemd process manager.
=> Remove the gxctl function

scripts/sshg
created standalone Galaxy ssh helper bash script with multiple configurable options and defaults.
based on the `sshy` function developed by @cat-bro for MacOS and adapated to Linux by @neoformit
=> add Galaxy ssh helper bash script to scripts directory

scripts/sshg
Allow users to define default values for destination username, ssh key and infrastructure repo location via exported Bash variables (in .bashrc) rather than requiring direct editing of script or needing to specify as parameters each time the script is run.
=> Sshg use envvars ifset

files/galaxy/config/activation-email.html
Remove broken/redundant gfonts links. Email clients can't use these and it affects spam score.
=> Fix mail template

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, group_vars/pulsarservers.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml, pulsar-QLD_playbook.yml, pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml, pulsar-mel2_playbook.yml, pulsar-mel3_playbook.yml, pulsar-nci-training_playbook.yml, pulsar-qld-blast_playbook.yml, pulsar-qld-high-mem_playbook.yml, roles/common/tasks/main.yml, roles/slg.galaxy_stats/defaults/main.yml, roles/slg.galaxy_stats/templates/get_queue_size.py.j2
Pulsars have been upgraded except for pulsar-QLD, pulsar-qld-blast and pulsar-azure. Blast and azure are less critical because they do not have a wide range of tools running on them.
This PR also uncomments slg.galaxy_stats role on the pulsars.
Pulsar QLD is offline waiting for two long running jobs to finish before we can run the playbook there.
=> upgrade pulsar to 0.15.2

files/galaxy/dynamic_job_rules/load-testing/total_perspective_vortex/testing_tpv_config.yml
native spec now set in destinations, 'partition' needs to be defined in context
=> Modernise default tool in etca tpv config

group_vars/galaxy_etca_slurm.yml, host_vars/galaxy-queue.usegalaxy.org.au.yml
Remove deprecated keys from slurm_config (these will also be removed with Nuwan's change #1374 )
Remove incorrect key for logfile in dbd conf and also override `__slurmdbd_config_default` because SlurmctldPidFile key should not be there and breaks everything.  TODO: figure out under what circumstances that key should not be included and PR a change to the ansible-slurm role.
=> Remove bad config keys from galaxy slurm config

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
pulsar-QLD is offline to be available to Sydney galaxy but Sydney galaxy does not need it this week. This is an attempt to mark some tools as quick so that pulsar-QLD can be brought back to production in a limited capacity, to run jobs that we expect to complete in reasonable time.
=> Add `pulsar-quick` tag to tools where jobs are likely to complete in less than a day

group_vars/all.yml
The key 'SlurmctldPidFile' was not being added to slurmdbd config from the 3-year-old pasted slurm role. It is now being added from the current version of the role. It actually breaks slurmdbd for version 19.05 as well as on the newer version we have installed on the galaxy VMs. Until this is fixed in the role we need to override it.
The default variable coming from the role is
```
__slurmdbd_config_default:
AuthType: auth/munge
DbdPort: 6819
SlurmUser: "{{ __slurm_user_name }}"
SlurmctldPidFile: "{{ __slurm_run_dir ~ '/slurmdbd.pid' if __slurm_debian else omit }}"
LogFile: "{{ __slurm_log_dir ~ '/slurmdbd.log' if __slurm_debian else omit }}"
```
=> Remove SlurmctldPidFile from default slurmdbd config block

group_vars/pulsarservers.yml
There is a bug in the current version (0.15.2) that causes pulsar to stop working every now and then.
pulsar-azure and pulsar-qld-blast are still on the old version (0.14.13) because the 0.14.* -> 0.15.* update needs to happen when no jobs are running.
Updating from 0.15.2 to 0.15.3 is not expected to harm running jobs.
=> Update pulsar-app version to 0.15.3

group_vars/pulsarservers.yml
pulsar-app does not require this but it logs frequent recommendations to update kombu to at least 5.2.0
=> kombu should be greater than 5.2.0 on pulsar

group_vars/aarnet_slurm.yml, group_vars/galaxy_etca_slurm.yml, group_vars/pulsar_QLD/pulsar-QLD_slurm.yml, group_vars/pulsar_mel2/pulsar-mel2_slurm.yml, group_vars/pulsar_mel3/pulsar-mel3_slurm.yml, group_vars/pulsar_nci_training/pulsar-nci-training_slurm.yml, group_vars/pulsar_paw/pulsar-paw_slurm.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml
Based on Tim Wickberg's advice [here](https://bugs.schedmd.com/show_bug.cgi?id=3415) and yesterday's experience, set RealMemory for all slurm workers to something a little less than MemTotal. For the ordinary workers that can be a very round number: 32000, 64000 or 128000. The values have also been lowered a little for the high-memory and training nodes. They will still all have enough stated memory for the jobs being sent to them.
=> Galaxy slurm update and memory corrections

group_vars/pulsarservers.yml
This increases the number of retries to 18 in the hope that a greater number of retries will increase the likelihood of large files being fully transferred back to galaxy.
=> Increase number of postprocessing retries for pulsar

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
To alleviate the blast queue issue.
What we also need potentially is an alternative ranking function for these tools that will send jobs to a second destination *only* if the primary destination is full.
This is related to issue https://github.com/usegalaxy-au/infrastructure/issues/1427 and would be good to discuss with @nuwang and @bgruening
=> Allow pulsar blast jobs to go to pulsar-mel3

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2
Currently a destination with the highest score will always be returned first in ranking, even if it 100% occupied.
=> Remove score from consideration in TPV ranking

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Some local entries are deleted in order to use entries from the shared db.
Some tools have entries added/amended in this PR for the shared db. https://github.com/galaxyproject/tpv-shared-database/pull/37
=> TPV changes in response to oom errors for jobs running on local slurm cluster

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Remove cores/mem entries for macs2, because the local config seems to have been giving the tools more than they need, they are not multithreaded and the entries in the shared_db seem sensible. It is still the case that macs2_callpeak cannot run on pulsar.
Give smudgeplot 500G because it runs out of memory with 60G. If it uses substantially less than 500 this can be reduced.
=> Give big memory to smudgeplot, remove cores/mem for macs2

roles/common/tasks/main.yml
Some VMs (dev) don't have the apport service installed, so need to ignore errors when disabling apport service in common role.
=> ignore missing apport systemd service in common role

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, host_vars/aarnet.usegalaxy.org.au.yml
Increase memory for medium humann jobs to 45 based on sacct data from older jobs. A user has sent in a ticket about a recent job being oom killed.
Remove user limit for jobs on pulsar-QLD.
Stop sending blast jobs to pulsar-mel3.
=> Increase memory for humann

files/galaxy/gxadmin/gxadmin-local.sh
`gxadmin local query-oom-jobs` lists the jobs with `This job was terminated because it used more memory than it was allocated.` in job.info or 'Killed' in job.tool_stderr.
=> add oom query to gxadmin local

dev_playbook.yml
task `usegalaxy_eu.galaxy_subdomains : Create main site` is broken in galaxy release_23.1 due to `static/style/base.css` no longer existing.
=> disable galaxy subdomains for dev release 23.1

dev_playbook.yml
missing base.css file in release_23.1
`TASK [galaxyproject.tiaas2 : Copy Galaxy's stylesheet]` fails with error:
`Source /mnt/galaxy/galaxy-app/static/style/base.css not found`
=> dev disable tiaas2 missing css release 23.1

host_vars/aarnet.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_object_store_conf.xml.j2
This can't be merged yet. Still to do:
(1) Set object store IDs for datasets and metadata files for all 'store_by="id"' backends (so far this has only been set for perthNFS1-4)
(2) Update aarnet-user-nfs playbook to create new folder `data008` alongside user-data5 and user-data7 in /mnt directory on aarnet-user-nfs and a new subdirectory `data009` of /user-data6
(3) Update aarnet and aarnet_workers shared_mounts variables to mount the new folder /mnt/data008
To switch to using this configuration:
Stop galaxy.
Set all dataset ids and metadata_file object_store_ids created since August to aarnetNFS7
Run aarnet_update_configs playbook
Start galaxy
=> Distributed object store conf for aarnet

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
may as well, since it only accepts quick running jobs and can be taken offline tomorrow
=> put pulsar-QLD online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
mothur jobs will fail if any file in the working directory is bigger than 470G. It will also fail if too many pids are created.
[EDIT]: I previously wrote that this would not work if the  tool ID was not in our local config - have since tested this with dry run and it should work either way.
=> run mothur with docker for safety

host_vars/aarnet.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_object_store_conf.xml.j2
This switches the object store to write to data08 and updates nginx config so that the upload_store is within /mnt/data08 w.r.t. aarnet VM.
In the near future (maybe today) this needs to be merged, aarnet_playbook run and "sudo systemctl reload nginx" on aarnet.
=> switch back to data08

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Memory adjustments for some tools showing up from the 'gxadmin query oom-jobs' query. Most of these haven't had entries in the past (in local or shared db).
=> More memory for some tools

group_vars/galaxyservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Set galaxy_additional_venv_packages within galaxyservers.yml instead of host variables. Add 'watchdog==2.2.1' since the job handlers on etca had a memory leak with the latest version (3.0.0)
=> declare additional packages in galaxyservers and pin watchdog

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
All abyss jobs fail. Test jobs fail with 62GB RAM. Test jobs used to pass on nodes that had no more than 62GB total RAM so allowing all jobs to run on high memory pulsar with 320GB probably won't even help but it's worth a try.
=> Remove all file size rules for abyss

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, templates/galaxy/toolbox/filters/ga_filters.py.j2
This means nobody without a VM login (machine_users in all.yml) and members of the Fgenesh/cellranger groups can see these tools. The TPV rule is more strict and will not allow anybody outside the Fgenesh group to run fgenesh.
=> Add toolbox filters for fgenesh and cellranger

host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml
The new pulsar-high-mem1 and pulsar-high-mem2 VMs have NVME ephemeral volumes attached to /dev/vdb and mounted as ext4 on /mnt. For this reason the `attached-volumes` role and `attached_volumes` host_vars need to be removed.
=> dont attach volumes to phm1 and phm2

files/galaxy/config/tool_data_table_conf.xml
Column names for getorganelle need to be 'value, name, path, db-version' because these are coming from the tool repository - each time a new revision of getorganelle is installed, the shed tool data table conf gets another entry with these column names.
=> fix column names for getorganelle

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Both pulsar-mel3 and pulsar-mel2 now offline. That leaves only pulsar-QLD for regular-sized slurm jobs for 20 or so tools (pulsar-quick tag), the rest will have to run on slurm for now.
=> set pulsar-mel2 offline

roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
The `galaxy-backup-db.sh` script is currently exit-failing on swift errors. This appears to be due to `set +e` only being applied to `swift delete` and not `swift upload`. `slg.db-backup` has been modified to prevent `swift upload` from causing the backup script to exit prematurely. Additionally, logging errors in local deletes (if any).
=> dont abort on swift upload fail

files/galaxy/dynamic_job_rules/load-testing/total_perspective_vortex/testing_tpv_destinations.yml.j2, host_vars/pulsar-QLD/pulsar-QLD.genome.edu.au.yml
add pulsar-QLD to ETCA galaxy as an active destination for load testing. Note that it has already been set offline in the aarnet TPV.
=> add pulsar-QLD to ETCA for load testing

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Needed for 23.1.
Also set minimum singularity version for fastqc and keep using conda for older versions.
=> Do not import packaging version in tpv

group_vars/galaxy_etca.yml, roles/attached-volumes/tasks/set_up_volume.yml, roles/mounts/tasks/main.yml
Add 'opts' to ansible mount tasks.
So far we've been dealing 2-VM galaxy issue by setting actimeo=2 for the user data mount on the galaxy VM. This is not the only thing we could do here - we could be using noac and there are probably other options as well. I'm still curious as to how the current deployment doesn't have issues caused by nfs cache time, but then maybe it does, and some of the nfs/io bottlenecks are due to this.
=> Add opts to roles that mount volumes

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
snippy jobs run quickly but the tool requires data from custom indices which is not on pulsar-QLD or pulsar-high-mem2.
Add singularity_enabled for bwa and bwa_mem
=> Remove pulsar-quick tag from snippy

group_vars/galaxy_etca_slurm.yml, host_vars/galaxy.usegalaxy.org.au.yml
Try out selenium testing without galaxy-handlers VM for comparison. There are 4 blocks commented out or uncommented to enable this. I think that's all that is needed.
We then need to run galaxy_update_slurm_playbook and galaxy_playbook.
=> etca single galaxy VM

group_vars/galaxyservers.yml, requirements.yml
tiaas and subdomains roles refer to a base.css file that is no longer part of the codebase. The tiaas role has a way of parameterising this but it will never be fixed in the subdomains role* so we are using my fork of it for now.
*galaxyproject.galaxy role will absorb functionality of subdomains role instead.
=> update variables and roles for release 23.1

host_vars/galaxy-db.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml
Production galaxy is at release 23.1 so new galaxy needs this too. Selenium tests are leading to the current max_connections value of 200 to be exceeded. This seems to be an issue specific to the selenium test users with hundreds of concurrent logins so a bandaid solution is ok: set max_connections to 300.
=> update galaxy to 23.1 and increase db connections

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Give some tools more memory. Give wig_to_bigWig the 'training-exempt' tag so that these jobs will not be treated as training jobs and will have enough memory to run.
=> TPV adjustments

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add entries for some more tools that have been using default allocations.  Remove entry for krona_text to use shared-db entry instead.
Update unicycler and stack2_ustacks entries. stacks2_ustacks does not need a concurrency limit anymore.
=> Updates for oom tools (19/10/23)

galaxy_playbook.yml
The miniconda role can take a long time and is not really needed once it has been run once. It needs refactoring to prevent it from taking so long. Leave it out of the playbook roles until.
=> comment out miniconda role

galaxy-user-nfs_playbook.yml, group_vars/galaxy_etca.yml, host_vars/galaxy-user-nfs.usegalaxy.org.au.yml
Do not attach volumes in playbook because this once went wrong years ago, even though the role has now been fixed.
Export the 3 volumes as /mnt/volA, /mnt/volB, /mnt/volC to be attached to galaxy, handlers and workers as /mnt/user-data-volA etc so we don't end up with arbitrarily many mounted subfolders.
=> galaxy user nfs update

galaxy_playbook.yml
Note that postfix-mail-relay role utilises variables defined in `host_vars/galaxy.usegalaxy.org.au.yml`. These were defined in PR [#1572](https://github.com/usegalaxy-au/infrastructure/pull/1572). The variables for the slg.galaxy_stats roles, also defined in `host_vars/galaxy.usegalaxy.org.au.yml `were done in PR [#1422](https://github.com/usegalaxy-au/infrastructure/pull/1422)
=> [moving day] enable postfix-mail-relay and slg.galaxy_stats roles in galaxy playbook ready for move to production

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
All versions of mummer tools on GA are OK with singularity. This will fix a problem on pulsar-mel3 where one of them is failing with the conda environment.
=> Singularity for mummer tools

host_vars/galaxy-handlers.usegalaxy.org.au.yml
docker-data has been going to /mnt/docker-data which is just part of the root disk on the galaxy-handlers VM. Move it to /pvol which is larger.
=> move docker-data to attached volume on galaxy-handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
The 20T volume attached to pulsar-QLD-job-nfs needs to be migrated to a new volume. In the meantime, stop jobs going to pulsar-Qld.
=> offline pulsar-QLD for volume migration

galaxy_update_configs_playbook.yml
This is for safety while restart speeds are unresolved. This playbook is run when tpv changes are merged.
=> Don't let jenkins trigger a job handler restart with TPV changes

host_vars/galaxy.usegalaxy.org.au.yml
Restarts of gunicorn processes regularly take more than 10 minutes, causing the "galaxyctl graceful" rolling restart to return a bad value which stop the playbook.
=> increase timeout for gunicorn restarts from 10 to 30 minutes

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
A number of kraken jobs are failing due to running out of memory. Slurm cluster is very busy so it makes sense to give kraken a high memory allocation.
=> send kraken to high memory pulsars

group_vars/galaxy_etca_slurm.yml
If the 3 32 CPU slurm workers have different weight, this might reduce the queue time for large jobs, since jobs would be sent to w8 and w9 before w10.
=> updates weights for galaxy_etca_slurm

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add memory as a linear function of input size for iuc tools anndata_inspect and scanpy_plot
=> more scanpy scaled rules

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml
the pulsar test users are set up to run only toolshed tools on the pulsars and all other jobs go to local slurm. phm2 test user needs a workaround so that fgenesh it runs go to phm2.
=> let phm2 test user run fgenesh on phm2

group_vars/galaxy_etca.yml
we're adding the noatime option manually so we can do so without unmounting, adding it here for future rebuilds etc
=> galaxy etca noatime

group_vars/pulsarservers.yml, host_vars/galaxy.usegalaxy.org.au.yml
If a pulsar is not a production pulsar it can have `sentry_dsn: ''` which is OK - tested on pulsar-nci-test.
=> pulsar sentry dsn default to empty string + reinstate sentry_dsn on galaxy

host_vars/galaxy.usegalaxy.org.au.yml
lots of nfs errors from pawsey-user-nfs in galaxy logs, and galaxy has been down for a couple of hours it looks like. The nimbus dashboard will not load and I can't ssh to the VM.
=> pawsey file mounts unavailable

galaxy-handlers_playbook.yml, galaxy-workers_playbook.yml, galaxy_playbook.yml, group_vars/galaxy_etca.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
The state of a mount point for an unavailable mount should be 'absent_from_fstab', controlled by the booleans `qld_file_mounts_available` or `pawsey_file_mounts_available`. These mount points need to move for better job safety (see issue #1660 ), so this PR is also creating empty folders for the mount points.
=> external volume refactor part 1

.gitignore, ansible.cfg, requirements.yml, roles/mounts/tasks/main.yml
Add a collection to the requirements file, so that appropriate mount options are available.  To install collections and roles together:
`ansible-galaxy install -r requirements.yml`
and they will go to the right places as specified in ansible.cfg.
This probably destroys the update-roles module and it will need to be repaired later on.
=> Use ansible posix mount

Makefile, scripts/ansible-find-upgrades.py, scripts/update_roles.py
Adding collections to requirements.yml had broken some processes since the file is now a yaml dict instead of a list.
Add `install-requirements` and `force-install-requirements` and remove `run-dev`, `run-staging` and `run-prod` since these are covered in the extremely useful catchall `run`.
=> update Makefile and role scripts

galaxy_update_configs_playbook.yml
This is mostly used by jenkins_bot for tpv changes but it's also useful when run manually for things like object store and other galaxy config files changes. It needed some updates to allow for restarting galaxy processes across the galaxy/galaxy-handlers VMs.
=> fix galaxy update configs playbook

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, jenkins/update_labels/tool_labels.yml
Galaxy EU are currently using this container, as per https://github.com/usegalaxy-eu/infrastructure-playbook/blob/949da8e677b491508a6622f370e671de4e1733a9/files/galaxy/tpv/tools.yml#L1043
@cat-bro the toolshed has braker3 3.0.6_galaxy2, which i haven't tested on GA. Will it autoupdate once the test label is removed?
=> braker3 change container and remove test label

hosts
This removes the aarnet pmla hosts and reorders the file, mostly grouped by tenancy
=> Reorder hosts file and remove entries post PMLA

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
node is draining and new jobs keep going there because it is least busy
=> pqhm1 offline

group_vars/galaxy_etca.yml
Remove /mnt/files and /mnt/files2 file mounts - these are now mounted within /mnt/user-data-qld.
Closes #1660
=> update file mounts in galaxy_etca.yml

templates/galaxy/config/staging_object_store_conf.xml.j2
Switch staging object store from hierarchical to distributed to assist with debugging an error with some tool outputs.
=> staging distributed object store

dev_playbook.yml, host_vars/dev.gvl.org.au.yml
- Re-enable subdomains role in dev playbook
- Add `proteomics.dev.gvl.org.au` to `certbot_domains`
- Remove redundant `tool_sections` declaration in proteomics lab subdomain conf
=> More proteomics lab configuration

requirements.yml
galaxyproject.galaxy role has a [change](https://github.com/galaxyproject/ansible-galaxy/compare/0.10.15...0.10.19) which is the ability to use the role for subdomains, deprecating the usegalaxy_eu.subdomains role.  I'm assuming that this is backwards compatible and we can keep using the subdomains role for now.
galaxyproject.pulsar [changes](https://github.com/galaxyproject/ansible-pulsar/compare/1.0.8...1.0.11) not much: config files are no longer read-only by default and restart handlers should work now.
=> Update ansible role versions for galaxyproject.galaxy and galaxyproject.pulsar

roles/common/tasks/main.yml, roles/slurm-post-tasks/tasks/main.yml
`sudo sacct` is available to all machine users, not just sudo users, on any VM with slurm installed (galaxy VM, worker nodes, all pulsar machines etc) but the environment variable setting the output to a useful format format has only been set on slurmcontroller VMs and has been missing from workers and galaxy web/handlers servers.
=> move SACCT_FORMAT for root user to common role

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Taking pulsar-QLD offline so that its underlying host can have updates applied.
=> pulsar-qld offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Taking pulsar-qld-blast offline so that its underlying host can have updates applied.
Redirect blast jobs to pulsar-mel3
=> send blast to pulsar-mel3 and offline pulsar-qld-blast

pulsar-QLD-job-nfs_playbook.yml
the job working directories should be owned by ubuntu user. remove the recursive chown to pulsar which breaks jobs trying to be run on pulsar-QLD.
=> remove recursive chown from pulsar-QLD-job-nfs playbook

roles/attached-volumes/tasks/set_up_volume.yml
move 'mount volume' task outside of block that requires attached_volume.partition to exist
=> update attached volumes role

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is to stop kraken jobs running on the larger slurm workers
=> make kraken require pulsar

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
It looks like helixer tries to write to $HOME, can I set it like this? Or should I add a `docker_volumes` ?
```
Traceback (most recent call last):
File "/usr/local/bin/fetch_helixer_models.py", line 32, in <module>
main(args.lineage, best_only=not args.all)
File "/usr/local/bin/fetch_helixer_models.py", line 21, in main
fetch_and_organize_models(models)
File "/usr/local/lib/python3.8/dist-packages/helixer/core/data.py", line 22, in fetch_and_organize_models
os.makedirs(model_path)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/usr/lib/python3.8/os.py", line 223, in …
```
=> helixer tries to write to home

roles/slg.db-backup/defaults/main.yml, roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
Currently galaxy database backups are kept on local disk and swift cloud storage until the configured backup expiry is reached, then both are deleted. As the size of galaxy database backups has increased, we are no longer able to keep all of the backups on local disk, but would like to still keep them on cloud storage.
This PR utilises marker files on local disk to indicate that these backups are stored on cloud. Local disk backups can be expired sooner (1 week) to keep the local disk from filling up, while cloud-based backups can be kept for the desired amount of time.
Note that prior to changing the current backup scheme, swift marker files for the existing database backups will need to be generated with timestamps matching the backups. This can be done manually as per the following …
=> manage galaxy backups with markers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
To prevent too much traffic to pulsar in the short term.
=> temporarily direct all fastqc jobs to slurm

group_vars/all.yml, group_vars/pulsarservers.yml, host_vars/dev-queue.gvl.org.au.yml, host_vars/galaxy-queue.usegalaxy.org.au.yml, host_vars/pulsar-QLD/pulsar-QLD-queue.genome.edu.au.yml, host_vars/staging-queue.gvl.org.au.yml
The slurmdbd configs for phm1 and phm2 were slightly wrong, resulting in no slurmdbd log files. It turns out that all of the VMs using slurmdbd can use the same config block so this is moved to all.yml along with MariaDB config which is the same everywhere.
=> slurmdbd refactor

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
limiting smudgeplot jobs to 50G. The allocation/limits can be reviewed over time but at the moment very large job will use a lot of resources for data transfer, run for ages then be oom-killed.
=> Add size limit rule for smudgeplot

roles/slg.db-backup/templates/galaxy-backup-db.sh.j2
move search for files over a certain age to after database backup and swift upload so that files are not kept an extra day due to files being created later in the day than the search for files that have expired
=> check file ages after db and swift backup

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
update memory for snippy_core, seurat and cdhit. roary can run on pulsar.
=> tpv mem updates 20240123

requirements.yml
update galaxyproject.galaxy role between releases because there is a commit that fixes the problem of themes disappearing.
=> update galaxy role pre release

galaxy-workers_playbook.yml, pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml, pulsar-mel2_worker_playbook.yml, pulsar-mel3_worker_playbook.yml, pulsar-nci-training_workers_playbook.yml, pulsar-paw_worker_playbook.yml, pulsar-qld-high-mem_playbook.yml
there is an ansible template containing literal "{{}}" [here](https://github.com/usegalaxy-au/infrastructure/blob/master/roles/clean-tmpdisk/templates/clean_tmpdisk.py.j2#L72), which to ansible means it should contain a variable to substitute. Needs fixing.
=> comment out clean-tmpdisk role, needs more work

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/staging_destinations.yml.j2
For GA this fixes a bug with samtools_split and a couple of other tools https://github.com/galaxyproject/galaxy/issues/17208 though it's still a Galaxy bug that postprocessing fails for those tools with the default metadata_strategy.
This parameter can't be set for pulsar destinations unless the destinations have a galaxy code directory - something for later.
=> Set `metadata_strategy: extended` on slurm destinations in tpv

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Allow only quick jobs on pulsar-mel2 so that it can be taken offline at some point
=> Require pulsar-quick tag on pulsar-mel2

host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Since updating dev to release_23.2 interactive tools are being mapped to < some uuid >.ep.interactivetool.dev.gvl.org.au instead of < some uuid >.interactivetoolentrypoint.interactivetool.dev.gvl.org.au.  After creating a new CNAME record for dev and updated the certificate to include the new pattern, ITs are working on dev. I could be missing something about how ITs are supposed to work post 23.2.
=> new interactive tool urls

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is temporary for the purpose of stopping the slurm cluster becoming blocked by medium sized jobs
=> reduce fgenesh and allow maxquant to run on fgenesh VM

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
override shared db 50G mem allocation for filtlong, most jobs use far less than this
=> Create tpv entry for filtlong

host_vars/galaxy.usegalaxy.org.au.yml
The current batch of credits runs out at the end of this month (Feb 2024) so the increase in limits is an attempt to spend these.
=> Increase limits for alphafold

group_vars/galaxy_etca.yml
There is a problem with tool installation where some job/web handlers cannot find the tool even after a delay of 5 minutes. This might be due to cache delay.
=> set actimeo=0 for /mnt/tools

.github/workflows/check_tpv_config.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is unpleasant but it seems to work
=> Stop linting workflow from breaking by pinning every galaxy package

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There is a user with large reference genomes from history and all of their bwa_mem jobs are failing. Nate has set up a rule to estimate memory requirements based on the size of the reference genome from history. They are setting the max value as 120G RAM. This would not work for the GA user whose jobs are being killed with 250G. This PR adds Nate's rule with a max value of 480 which still might not be enough.
Lint is still failing due to an inconsistency in galaxy-app requirements so I'm not merging this.
=> Use Galaxy Main's mem formula for bwa_mem2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is for a user who has 100s of new bwa_mem2 with a very large reference genome from history
=> bwa_mem2: raise maximum memory to 900 and decrease concurrent jobs per user

group_vars/pulsarservers.yml
To address jobs with large input failing because the data does is not transferred in time
=> Increase pulsar preprocess_action_max_retries from 20 to 30

group_vars/galaxyservers.yml
Some VGP jobs are failing because the output datasets are over 120GB and galaxy won't accept them
=> Increase nginx client_max_body_size from 120g to 240g

host_vars/pulsar-high-mem1/pulsar-high-mem1.yml
After rebuild of pulsar-high-mem1 it has less free memory than what is specified by slurm's `RealMemory` which prevents slurm from utilising the node. Reducing `RealMemory` to match what's now available.
=> reduce phm1's RealMemory for slurm to match available memory after rebuild

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This rule is borrowed from Galaxy Main. Some bwa_mem2 jobs have failed with OOM error when the reference genome is very small compared to the rest of the input data. It is also more likely to run out of memory with compressed fastq input.
It's a shame to remove this because it is nice to calculate memory needs rather than giving every job 250G. I'll make an issue with examples of cases where the calculated memory has been too low.
=> Remove bwa_mem2 history reference rule

host_vars/galaxy.usegalaxy.org.au.yml
When it's busy, the jobs that are queued and not running tend to be higher-cpu jobs. If enough of them are in the queue the limit (55) is reached and this can block smaller jobs that would be able to run immediately from joining the queue.
=> Allow 80 jobs in queued/running state for slurm (up from 55)

group_vars/galaxyservers.yml, host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml, templates/nginx/galaxy.j2
This ensures weight is a non-zero integer and removes the num_gunicorn_processes variable. The format of galaxy_config.gravity.gunicorn needs to be a list across all dev/staging/galaxy for this to work.
=> fix nginx template upstream section

group_vars/galaxy_etca.yml
The reason we started setting actimeo at ETCA was that files created and shown as available in the history panel would not become available until 10-20 seconds later. From memory, using actimeo=2 for the user volumes was adequate. I don't know if we have a use case for setting actimeo=0 on /mnt/tmp - switching to default is worth a try to see if it will improve performance.
=> Change mount settings

host_vars/galaxy.usegalaxy.org.au.yml
with this setting, all celery tasks will run from the galaxy handlers VM. Currently they are divided between galaxy and galaxy-handlers.
=> disable celery on galaxy web server

group_vars/galaxy_etca.yml, host_vars/galaxy.usegalaxy.org.au.yml
Only the galaxy VM needs actimeo set for the user data volumes. It doesn't make sense that any of the other VMs would need this.
These volumes are mounted on 12 clients. Is there any difference between all 12 of them having actimeo set, or only one of them? If not, this change is not helpful and this PR can be closed.
=> Less nfs caching of user data mounts

dev_playbook.yml, group_vars/galaxyservers.yml
This is a setup for dev to see if it has the desired result.
Two weeks of nginx logs is 1.1GB in size so keeping them forever on the root disk is not an option.
There is a lot of space on /mnt on the galaxy VM so we could probably keep them for several years or just this year to get access data. This is a few lineinfiles on the nginx logrotate conf that adds a date to the files, stores them in an olddir which has to be on the same device (apparently logrotate will protest if it is not) and copies the files to a directory on /mnt where they will not be rotated out but accumulate instead.
If this is approved and works on dev I'll want to put it on production (and remove it from dev where space on /mnt is not abundant).
before:
```
/var/log/nginx/*.log {
daily
missingok
rotate 14
compress …
```
=> vary nginx logrotate file to keep logs forever (dev)

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
hisat2 is filling up a worker tmpdisk. It creates too many intermediate files.
=> tmp_dir: true for hisat2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is not multithreaded but needs lots of memory. It is running out of memory frequently with 24G. With mem set to 70 it can run on high memory pulsar.
=> get_organelle_from_reads to pulsar

group_vars/pulsarservers.yml
This is necessary for the 164GB datasets coming from VGP training and hopefully will be enough.
It will also mean that for all pulsar jobs if there is a preprocessing error, jobs will take ages to fail.
=> Update pulsar preprocessing retries from 30 to 50

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This will increase queue times for data fetch when it's busy, on the other hand no upload job should fail so the change is necessary.
=> raise mem for DATA_FETCH to 12

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There are a bunch of freebayes jobs running with 7.6GB RAM and some are failing with oom errors.
=> update bounds for small freebayes jobs

group_vars/all.yml
For issue https://github.com/usegalaxy-au/infrastructure/issues/1849
Slurm nodes go into drain state due to jobs not ending with signals. The UnkillableStepTimeout defaults to 60 seconds. Hopefully raising it to 180 will stop the slurm nodes going into drain state as frequently.
=> set unkillablesteptimeout in slurm conf

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
@mthang has noticed that some qiime errors might be due to a temporary folders being given the same name
=> give all qiime tools `tmp_dir: true`

group_vars/pulsarservers.yml
pulsar-qld-gpu1 had the same problem with cert location as pulsar-high-mem1. I've downgraded pycurl to 7.45.2 and now it's OK. For now this will need to be pinned.
There is a bug report but I didn't find it last week - only saw it just now by specifically searching for pycurl 7.45.3 errors https://github.com/pycurl/pycurl/issues/834
=> pin pycurl for pulsar

host_vars/galaxy-queue.usegalaxy.org.au.yml
The max allowed size for rabbit messages defaults to 128MB but used to be much higher and has been reduced over time. The max they allow now is 512MB. This change will allow some pulsar jobs to finish.
=> increase max size for rabbitmq messages

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml, scripts/create_test_users.py
adjust tpv rules for alphafold and helixir to allow members of a group 'pulsar_gpu_test' or the pulsar test users to send alphafold/helixir jobs to qld instead of azure. Add a script for creating the pulsar users
=> alphafold helixir to qld

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
scheduling of alphafold jobs is broken because user does not have name. If user doesn't have username either I'll revert this and the previous one.
=> replace user.name with user.username in tools.yml

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
For @mthang : this means all maxquant jobs will run on the qld high memory pulsars which all have max_map_count set to 1000000
=> maxquant to run on qld hm pulsars

group_vars/galaxy_etca_slurm.yml
it makes sense for training jobs to be able to use all of the slurm workers. At the moment only galaxy-w7 is available to training because the others are fully allocated with long running non training jobs
=> more nodes for slurm training

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This tool seems to be using too much memory but until it can be fixed, it should be accommodated
=> more ram for stacks_tsv2bam

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Hopefully this will not put too much pressure on galaxy with pulsar transfers. The slurm queue is overloaded at present.
=> put fastqc back on pulsar for now

dev_playbook.yml, requirements.yml, staging_playbook.yml
Update galaxyproject.galaxy role to the latest
Also skip 'attached-volumes' on dev and staging for the same reason as pulsar-mel2 and pulsar-mel3 https://github.com/usegalaxy-au/infrastructure/pull/1897
=> update ansible galaxy role

requirements.yml
We can't make configuration changes in rabbitmq unless the config key is hard coded in the config file template, hence adding 'max_message_size' is not possible with their role. I'd like to fix this in the usegalaxy-eu role. In the meantime I have a fork with 'max_message_size' in the template.. we could use this for now.
=> Use fork for eu-rabbitmq role

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Hi @neoformit , we have a flag set for alphafold `tmp_dir: true` which should mean anything that would be written to `/tmp` will be written to `<jwd>/tmp` instead. It might be the case that this 'docker_volumes' entry has priority over that, and everything goes to /tmp which is not big enough in a handful of cases.
[EDIT: the mapping means that everything from /tmp goes to /mnt/scratch which is 60G as also too small]
=> no redirect for /mnt/scratch in alphafold jobs

host_vars/galaxy.usegalaxy.org.au.yml
Galaxy head node's root partition is filling up due to excessive Galaxy logging (currently at `log_level: TRACE`). Set log level to `INFO` to reduce size of log files.
=> Set galaxy head node log level to INFO

roles/slg.galaxy_stats/templates/get_queue_size.py.j2
This script was throwing an exception every time it encountered  a pulsar-qld-gpu1 job when 'pulsar-qld-gpu1' was not in the dests array.
=> stop get queue size breaking with unexpected destination names

group_vars/galaxyservers.yml
store the 1000s of temporary files on the floor of /mnt/tmp in /mnt/tmp/scratch so that they are easier to clean up.
We don't need to create /mnt/tmp/scratch in advance - galaxy will create this.
=> move tmp files within mnt tmp

templates/nginx/galaxy.j2
EU and main both have this. I'm wondering if a recent problem with content-length not being defined things sent to pulsar might have to do with the absence of this in our own config.
=> add headers to /_x_accel_redirect/ block in nginx template

pulsar-mel2_playbook.yml, pulsar-mel3_playbook.yml
The attached_volumes role is broken for legacy cases where no partition is set
=> skip attached volumes role on pmel2, pmel3

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
morpheus can run on pulsar. It is getting its cores/mem from the shared db as 1c/64gb. Because of the memory requirement it will almost always be better off on pulsar. Jobs like this with low CPU count and high memory are not handled well by the ranking function that sends the job to the destination with the lowest %CPUs allocated.
=> add tpv entry for morpheus

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
remove requirement for pulsar-quick tag from pulsar-QLD
=> Allow all pulsar jobs to run on pulsar-QLD

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml, group_vars/galaxy_etca_slurm.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
Add test user, test object store backend and test partition
This doesn't include mounting /mnt/scratchtest on galaxy, galaxy-handlers and galaxy-w3
=> production scratch test

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Since a recent update these tools do not write their temporary files to jwds automatically which is good, but today writing to jwds is good for scratch testing
=> switch on tmp_dir: true for sra tools

group_vars/galaxy_etca_slurm.yml
the scratch_test partition will still work, but star@email.com will be competing with other users
=> add galaxy-w3 back to main slurm partition

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
Add another zero-weight object store backend with `store_by="uuid"`. I'll keep the first one for comparison but I've moved it to a different path
=> scratch test2 object store ID

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Hi @neoformit, this should work to allow members of an extra group to run alphafold with bigger inputs. They would have to be members of the base 'Alphafold' group as well as 'Alphafold_plus' (or whatever name) and the new group would need to have an associated role. Pick whatever number is suitable for the aa length max in the new group.
=> make max length and db path context variables for alphafold so that max length can be extended for group members

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
ok for all versions of most snpeff tools. One of the snpeff tools passes its tests with conda, fails jobs and tests with singularity.
=> singularity enabled for snpeff

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_destinations.yml.j2
add tpv_cores, tpv_mem and tpv_gpus to params in dev default destination. This will become part of the default destination in shared db, this change is useful in order to start writing queries using these values
=> dev destination params in advance

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
This replaces the TPV's API call to the stats server with a database query. Destinations are still being ranked by the metric of %cpu used and future changes will consider memory as well. The result will be different because a job is counted in the query as soon as it has been queued, rather than as soon as it is running at the destination.
This is the first step in updating the ranking and we can observe whether it significantly increases the load on the database. Further changes will involve considering memory, and considering the quantity of resources available at various destinations instead of the proportion. I'd like to address the edge cases of low CPU high memory jobs that sometimes get stuck in the slurm queue when better destinations are immediately available.
Partly addresses …
=> replace production tpv api call with database query

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
At the moment only pulsar-QLD and pulsar-nci-training have to full set of funannotate reference data, so funannotate will only be allowed to run on slurm and these pulsars.
=> singularity + pulsar for funannotate

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
both have conda envs that fail on newly rebuilt pulsar-mel2
=> singularity for circos and augustus

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
picard_FastqToSam can use a lot of space, this is probably true of other picard converter tools
=> Set tmp_dir: true for all picard tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2
Add some more log statements to ranking function: what is being ranked and what the final ordered destinations are. Log space on galaxy-handlers has not been an issue.
Add function to replace destination_usage_proportion. destination_availability_score(destination) will return the maximum number of jobs of the type that could be scheduled given available resources at the destination. It is an attempt to improve the scheduling of jobs that have a high memory requirement compared to number of CPUs. Up to this point ranking has always considered only CPUs.  This is commented out so that I can collect some logs from the previous method before switching them.
=> Add tpv availablity score ranking but do not enable it yet

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Some tools had 'require: pulsar' because they have low CPU and high memory and jobs would get stuck in the slurm queue for long periods of time. The adjusted ranking function should remove the need for 'require' here.
=> remove some cases of 'require: - pulsar' in tools.yml

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
porechop needs more memory. The wrapper does not use $GALAXY_SLOTS, it only needs memory.
=> Update rules for porechop as it is not multithreaded

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
allow pulsar-high-mem1 to run out of jobs so it can be rebooted
=> set phm1 offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
not particularly fair on pqhm2, but better than it being able to break all of them
=> stop mothur_cluster_split running anywhere except pqhm2

hosts, pulsar-qld-gpu_playbook.yml
Rebuild pulsar-qld-gpu1 with Nvidia kernel modules, drivers, utils and nvidia-container-toolkit pre-installed; and MIG mode disabled to work with Cuda/Tensorflow.
=> rebuild pulsar-qld-gpu1

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add a function to TPV ranking that ranks destination A ahead of destination B only when the tool and destination A have a common 'prefer' category tag.
Also remove all prefer: pulsar tags from tools.yml with a view to adding them automatically later on.
=> Add prefer score to tpv ranking

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tool_pulsar_scores.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_job_conf.yml.j2
tool_pulsar_scores.yml contains a score for each tool, provided enough data. If a tool does not have a score, there will be no effect on ranking.
Scores have been calculated from an adjusted CPU-time heuristic * walltime / total input and output size for jobs.
If the tool has a score > 10 and is allowed to run on pulsar, the job will be preferentially sent to a pulsar destination.
If the tool has a score < 0.3 and is allowed to run on pulsar, the job will be preferentially sent to slurm.
Between these thresholds, jobs will continue to go to wherever has the highest availablity, slurm or pulsar.
Calculations based on past job data suggest that this will reduce the file traffic to/from pulsar while directing high resource-time tools away from the local cluster.
=> Add tool_pulsar_scores.yml to TPV config, defaults and rules to default_tool.yml.j2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tool_pulsar_scores.yml
something in new default tool rules is causing an illegal comparison between an int and a string, only for funannotate_sort
=> remove pulsar score entry for funannotate_sort

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2
At the point of applying tool rules, entity.mem might be an expression such as 'cores * 3.8'. It's a shame to skip these tools, maybe there is a way to evaluate the expressions here. For now this will prevent the rule causing an jobs to fail.
=> skip rule to add 'prefer: slurm' tag if entity.mem is not a number

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tool_pulsar_scores.yml
Reverts usegalaxy-au/infrastructure#2013
put this back and see if funannotate_sort is OK now
=> Revert "remove pulsar score entry for funannotate_sort"

pulsar-qld-gpu_playbook.yml, roles/nvidia-ctk/defaults/main.yml, roles/nvidia-ctk/tasks/main.yml
`nvidia-detector` only tested if nvidia GPU present, changed to using `nvidia-smi `which will fail of the one-offs hasn't been run.
`nvidia-ctk` role fixed - need to use a .asc extension rather than .gpg for repo key, this means that don't need to add an additional gpg dearmor step.
=> fixes to pulsar-qld-gpu playbook and nvidia-ctk role

host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Replace old lab landing page iframe URLs with new exported lab URLs:
https://site.usegalaxy.org.au/lab/export?content_root=https://site.usegalaxy.org.au/static/home/labs/genome/main.yml
https://site.usegalaxy.org.au/lab/export?content_root=https://site.usegalaxy.org.au/static/home/labs/proteomics/main.yml
The old pages at `/landing/<labname>` are no longer maintained and will be taken down soon.
=> Update lab urls with new exported lab pages

host_vars/galaxy.usegalaxy.org.au.yml
Initial testing on pulsar-qld-gpu 1-4: change `registered_user_concurrent_jobs_10` to `registered_user_concurrent_jobs_25` leaving `destination_user_concurrent_jobs` untouched for later stress testing.
=> change pulsar-qld-gpu limits for testing

files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
The dorado wrapper is ready to go onto production with a test label.
I'm trying to send jobs to the new GPU runners.
I've put the wrapper at /mnt/galaxy/local_tools/dorado.
=> Test dorado on prod

files/galaxy/config/tool_data_table_conf.xml
This is currently at `/mnt/galaxy/local_tools/dorado/tool-data/dorado_models.loc.sample`, so someone with sudo would also need to cp it to `/mnt/tools/tool-data/dorado_models.loc`
=> Add dorado_models loc file

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
add parentheses to expression though these should be redundant. anndata_import job has run with far too little memory (277m), the lowest value possible ought to be 2gb
=> Update anndata import rule

files/galaxy/config/local_tool_conf.xml, files/galaxy/config/tool_data_table_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, jenkins/update_labels/tool_labels.yml
Dorado's been tested and I've put it on the toolshed so we can remove it from local_tools.
I'm not sure if the change to `files/galaxy/config/tool_data_table_conf.xml` is necessary. If it's not we don't need commit 95eeb9d2e6b5d13faa8eab8afd4b96f53eb13cb1.
If the loc files need to be removed from `/mnt/tools/tool-data/`   someone with sudo would have to do that too.
Thanks!
=> Remove test dorado

one-offs/ubuntu-updates_playbook.yml
To address OpenSSH vulnerability [CVE-2024-6387](https://ubuntu.com/security/notices/USN-6859-1)
=> create one-offs ubuntu system updates playbook

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Underlying hypervisor has developed a hardware fault. Taking offline for maintenance.
=> set pulsar-qld-high-mem0 offline for hypervisor maintenance

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add a rule for > 200GB input, to run with higher memory (2TB) on pulsar-high-mem1 since that VM has more memory per CPU than the others
=> Update hifiasm memory rules, add rule for very large input

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
I have braker3 failing when I re-run a job that previously succeeded. Not sure if this will fix it. Error is
```
ERROR in file /opt/BRAKER/scripts/braker.pl at line 5893
Failed to create new species with new_species.pl, check write permissions in /usr/share/augustus/config//species directory! Command was /usr/bin/perl /usr/share/augustus/scripts/new_species.pl --species=cladocopium_goreaui --AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config/ 1> /dev/null 2>/mnt/pulsar/files/staging/9192576/working/braker/errors/new_species.stderr
```
`a6e389a98c2d167882357d636876289a (21677419)`
`a6e389a98c2d16788e014074d44a804a (19931009)`
=> writable-tmpfs for braker?

files/galaxy/config/tool_panel_filters/proteomics.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
- Add proteomics tool panel view to staging/prod
- Minor tweaks to tool panel view for proteomics lab
FYI there still seems to be issues with panel_views. The fundamentals work, I can select the "Proteomics" toolbox on https://proteomics.dev.gvl.org.au and the tool panel changes.
Sections from default panel are displayed correctly:
```yml
- sections:
- getext
- send
- ...
```
But none of the custom labels/sections are displayed:
```yml
- id: proteomics_section
type: label
text: Proteomics
- type: section
id: databases
name: Databases
items:
- type: tool
id: toolshed.g2.bx.psu.edu/repos/galaxyp/custom_pro_db/custom_pro_db
```
I'm unsure if this is something to do with dev, but this PR will let us see if it's working on Staging/Prod.
These features all seems to be working on …
=> Fix proteomics lab tool panel

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
there is a user sending 250GB files out to pulsar and the jobs fail with OOM errors which is a shame
=> increase memory for some bio3d tools

host_vars/galaxy.usegalaxy.org.au.yml
Same block on line 190 of this file. Ansible ran with this hosts file without issue, but vscode is protesting.
=> remove repetition of themes_by_host in host_vars/galaxy

dev-handler_playbook.yml, group_vars/galaxyservers.yml
the latest fs.dropboxfs is version 1.0.4 and needs python3.11.
galaxy pins it to be at version >1.  version 1.0.1 is ok.
Also update tpv version to 2.4.0
=> Pin fs.dropboxfs on our side

pulsar-qld-gpu_playbook.yml
exclude pulsar-qld-gpu-dev from pulsar-qld-gpu_playbook as it is a member of pulsar_qld_gpus but has its own playbook to give devs sudo
=> exclude pulsar-qld-gpu-dev from pulsar-qld-gpu playbook

group_vars/pulsar_qld_gpus.yml
Fixing issue raised by @neoformit whereby current mount results in the wrong path to Alphafold database `/data2/alphafold/2.3/2.3/<dbs>` when it should be `/data2/alphafold/2.3/<dbs>`.
=> correct mount path of updated alphafold DBs on pulsar-qld-gpus

group_vars/galaxyservers.yml, host_vars/dev.gvl.org.au.yml, host_vars/galaxy-handlers.usegalaxy.org.au.yml
To fix the issue when the first run of a tool fails after the container has been auto fetched. SINGULARITY_CACHEDIR needs to be off the root disk and the path needs to exist on the workers so it may as well be common. On production galaxy it will be /mnt/tools/singularity_data.
This change will improve the tool installation process and make it easier to mark existing tools as singularity enabled.
[EDIT] I mistakenly wrote /mnt/galaxy/singularity_data
=> galaxy singularity common cache

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2
@jlqfab this is meant to send the dorado jobs to `pulsar-qld-gpu-dev`
=> Send dorado jobs from dev to qld gpu dev

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Fix the destination docker volume for new prod AF DBs
`/data/alphafold_databases` -> `/data/alphafold`
=> Fix _pulsar_qld_gpu destination alphafold docker volumes

files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is redundant now. Will also remove `alphafold_test_2` tool which was for testing the AF DBs mounted at `/data2/`.
=> Remove alphafold_db_test rule

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reserve pulsar-qld-gpu VMs 1-3 for alphafold with up to 4 jobs running at a time and add a user limit of 2 concurrent alphafold jobs. Set cores/mem for alphafold to 16/130.
dorado and helixir can go to VMs 4 and 5. @TomHarrop I haven't changed the resources for these tools and they can still run 6 per VM, but this could be altered
=> use qld pulsars for alphafold

jenkins/update_labels/hidden_tools.yml
I'm concerned about whether this tool is working correctly. It's been outputting AGP that isn't formatted correctly and sometimes even when it runs it spits out errors but exits cleanly, e.g.
```
bedfile loaded
Traceback (most recent call last):
File "/mnt/tools/tool_dependencies/_conda/envs/mulled-v1-497196df66fa9a9ec7ca5cd006fec337d10a3922853cc6022890faf95ba41dcf/bin/correct.py", line 70, in <module>
oline += str(contig2new[attrs[0]] +'\t'+attrs[1]+'\t'+attrs[2]+'\t'+attrs[3]+'\n')
KeyError: 'chr1'
```
Apart from jenkins salsa has been run 88 times between 2021-07-22 and 2024-04-05.
=> Hide salsa?

host_vars/galaxy.usegalaxy.org.au.yml
Remove 25 job limit from destinations, this has been in place for testing GPU pulsars.
Increase concurrent job limit for users from 10 to 12. Increase concurrent job limits on the slurm destination from 5 to 6. pulsar-mel2 and pulsar-mel3 do not need to have concurrent job limits for users.
=> update job conf limits

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
bowtie2: 4 jobs per user
hisat2 and spades tools: 3 jobs per user
=> add some user limits for popular tools

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
The current user-data volume, `user-data-volB`, is running low on space. Create `data21` on `user-data-volC`.
NOTE: This is not to be merged, and galaxy playbook run to update object store, until `volB` is close to full, as `volC` has limited space available.
=> create data21 on user-data-volC

group_vars/galaxy_etca.yml
pawsey-user-nfs is back after migration to another host.
=> put pawsey-user-nfs back online

roles/common/tasks/machine_users.yml
Since some versions ago we have been using 'sudo galaxyctl' instead of this
=> Remove task for gxctl bash function

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
These can create a lot of temporary files if there is sorting involved and for the most part they clean up but not if the job is cancelled by the user
=> Set `tmp_dir: true` for built-in converter tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
these jobs are queueing for ages and they don't need that much memory
=> reduce excessive allocation for humann1

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
For tools PR https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/1130
Set singularity_enabled: true for all tools owned by ecology or galaxyp. For galaxyp there are some exceptions such as msconvert where docker_enabled is true and singularity_enabled is now set to false.
=> singularity for some GTN tools + all of ecology and galaxyp owned tools

dev_playbook.yml, host_vars/dev.gvl.org.au.yml, templates/galaxy/config/dev_object_store_conf.yml.j2
This is not production ready and I've kept some of Galaxy Main's text as a placeholder
This adds 'dev_scratch' to the object store and and removes 'dev_objects_scratch_test' (which is not needed and had nothing to do with the current work, despite the similar name).
=> dev: Add scratch to dev object store

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
No need to merge before the end of the day
=> pulsar-nci-training offline for maintenance Thursday-Friday

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Pulsar jobs have been using `4.1.5--pl5321hdfd78af_1`, this PR is to override it with `4.1.5--pl5321hdfd78af_0`. According to Nate's comment [here](https://github.com/galaxyproject/usegalaxy-playbook/blob/7d649a3d41a2a987bb8edadf34039e79d803b3ad/env/common/templates/galaxy/config/tpv/tools.yaml.j2#L269), this is the good version of the container.
=> Try overriding the singularity container ID for repeatmasker

galaxy-handlers_playbook.yml, host_vars/galaxy-handlers.usegalaxy.org.au.yml
Add a temp directory for celery. Found an example of this while trawling through Galaxy Main's gravity configuration. If it works, it would prevent galaxy-handlers' root disk filling up like it did last night.
=> galaxy celery tmp

group_vars/all.yml, roles/common/tasks/main.yml
the Ubuntu package `libgl1-mesa-glx` is obsolete since 23.10. Replace this on Ubuntu 24.04 with `libgl1` and `libglx-mesa0` packages which provide equivalent behaviour.
=> common packages deal with ubuntu 24.04 differences

.gitignore
Rather than ignoring the installed geerlingguy roles on a one by one case, ignore all of them by default.
=> ignore all geerlingguy roles - installed via requirements.yml

host_vars/jenkins-2024.yml
Additional plugins used by Jenkins jobs from 2018 server need to be installed. Also adding jenkins server hostname.
=> add plugins and hostname to jenkins playbook

group_vars/jenkins.yml, jenkins-2024_playbook.yml
The github Hub package is now included in the standard Ubuntu Apt repos, installing via `common` role with `group_packages`.
=> install github hub package for jenkins server

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
set 8GB for mirdeep2 tools and 28GB for mirdeep2_mapper. This doesn't need cores because the wrapper doesn't use the GALAXY_SLOTS variable
=> more memory, fewer cores for mirdeep2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2204
=> Revert "limit gtdbtk destinations while dbs are copied"

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml
Update galaxy-user-nfs ansible to include new disk (already manually mounted in fstab by UUID), and add NFS export.
=> add new disk to galaxy-user-nfs

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml.j2, host_vars/galaxy.usegalaxy.org.au.yml
Rearrange slurm_singularity_volumes etc to be context variables on the default tool instead of hard coding them on destinations. This makes it possible for an aws gateway user to have '/mnt/aws_gateway:ro' appended to volume strings for their jobs.
@jlqfab @nuwang from a dry run this appears to just work.
=> make singularity volumes overridable context variables

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This includes an increase for bowtie2 from 8c/31g to 12c/46g. A lot of jobs were running out memory with 31
=> oom updates 2024-10-03

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Set dorado mem the same as alphafold mem so that not too many jobs will run at once
=> reduce concurrency of dorado jobs

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Increase the RAM for dorado so that slurm is unable to schedule more than one at a time
=> run dorado jobs one at a time

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Every job on pulsar-qld-gpu3 has failed since about this time last month. Some jobs are failing with the error: "INTERNAL: Failed to launch CUDA kernel". This error has not been seen on any of the other pulsars while they have been in production.
=> set pqgpu3 offline

dev_playbook.yml, host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml, roles/webhooks/tasks/main.yml, templates/galaxy/webhooks/toolmsg/config.yml.j2, templates/galaxy/webhooks/toolmsg/script.js.j2
I wrote a webhook plugin that allows us to define tool-specific messages. 
Just [deployed on dev](https://dev.gvl.org.au/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fabyss%2Fabyss-pe%2F2.3.4) last night.
This config in `dev.gvl.org.au.yml`:
```yml
toolmsg_messages:
- tool_id: toolshed.g2.bx.psu.edu/repos/iuc/abyss/abyss-pe
message: A custom message for ABySS!
class: danger
```
Results in:
The `toolmsg_messages` schema:
```yml
- tool_id: message will display if current_tool_id.startsWith(tool_id)
message: A custom message to be displayed for this tool (text only, no HTML currently)
class: bootstrap class - must be one of [primary, info, success, warning, danger]
```
=> toolmsg webhook plugin on dev + prod

templates/galaxy/config/galaxy_job_conf.yml.j2
ready_window_size has been set to 120 for two hours and I can't see any problems arising from it in terms of handler/db CPU or memory use.
This mitigates https://github.com/usegalaxy-au/infrastructure/issues/2254 for now but there needs to be a better solution for this issue.
=> set ready_window_size to 120

templates/galaxy/config/galaxy_object_store_conf.yml.j2
This is trying to be like Galaxy Main's entry here: https://github.com/galaxyproject/usegalaxy-playbook/blob/33fac17ea40efe05a11e68204f1d5f079b5ed775/env/main/group_vars/all/galaxy_config_vars.yml#L181-L203
=> use type: swift instead of type: boto3 for nectar_test in object store

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
this tag means a helixir job is treated the same as if it were not being run by a training user.
=> Add training-exempt tags for helixer and fgenesh_annotate

templates/galaxy/config/galaxy_object_store_conf.yml.j2
These have been commented out on galaxy due to an unhandled botocore exception with the minio backend causing every single slurm job to fail. For now these should not be in the object store conf.
=> remove test object store backends

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Hypervisor maintenance completed. GPU 4 and 5 can go back online. GPU 3 (replaced) needs to be tested first.
=> pulsar-qld-gpu4 and gpu5 online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Hypervisor maintenance for pulsar-QLD-w5 and pulsar-QLD-w6 completed. Workers put back online.
=> revert pulsar-QLD capacity back to full capacity

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Fix issue for EBI SCXA Data Retrieval where get the following error: `wget: unable to resolve host address 'ftp.ebi.ac.uk'`. This appears to be caused by running the tool within singularity.
=> disable singularity for retrieve_scxa

host_vars/stats.usegalaxy.org.au.yml
galaxy_etca influx database has manually had a "forever" retention policy applied to it, to keep monitoring of etca tests. This change prevents the usual default retention of 14 days being applied when the stats playbook is run. When this data is no longer required, this change can be reverted and the retention policy changed to the standard 14 days.
=> remove galaxy etca from influxdb 14d retention policy

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There is capacity to increase this - if the queue gets busy it can go down to 2 or 3 again
=> increase concurrent alphafold jobs per user

templates/galaxy/config/galaxy_object_store_conf.yml.j2
Some of the interstate folders are nested. It would be better if (a) no object store folder is within another object store folder and (b) an object store folder is within a volume rather than being the volume
This needs to be merged/deployed when there are not running jobs using QLD/WA data, folders moved and paths carefully checked
=> unnest object store folders

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml.j2
Get storage test user pulsar jobs to go exclusively to pulsar-mel2. It's quiet enough that pulsar-mel2 can be used only for these jobs.
=> restrict pmel2 to test users

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
this is not multithreaded and it runs out of memory for large inputs
=> update memory for fasta_stats

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, group_vars/galaxyservers.yml
There has been an error in gunicorn logs coming from the tool predictions API:
```
Dec 03 00:01:47 galaxy galaxyctl[2118437]:   File "h5py/h5f.pyx", line 102, in h5py.h5f.open
Dec 03 00:01:47 galaxy galaxyctl[2118437]: OSError: Unable to synchronously open file (file locking flag values don't match)
```
From a google search I found recommendations to use `HDF5_USE_FILE_LOCKING: "FALSE"`. Checked out EU and Main infrastructure playbooks and found that they are already using this, and they have adopted it recently. (https://github.com/galaxyproject/usegalaxy-playbook/commit/3724a136012c3846a869a74df26b99f64d002e9e#diff-68bca5ccf2e9695dcca9925b36cce7bb8e7bd223d9c6531649be01986c661020R31)
I'm not sure if this means instances are individually compensating for something that has gone wrong in …
=> disable HDF5 file locking

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Allow pulsar-mel2 to run user jobs again, and add 'require: pulsar-quick' to pulsar-mel3 so that it can only run jobs from tools with that tag.
=> prepare pmel3 for shutdown

jenkins/check_data_tables/check_data_tables_for_duplicates.sh, jenkins/check_data_tables/check_data_tables_for_dups.py, jenkins/check_data_tables/requirements.txt, jenkins/utils.sh
If a data table is added to cvmfs with an entry that matches an existing one from GA's custom indices data, jobs will fail and users won't report it for ages. This has happened recently with interproscan, eggnog and bwameth.
Jenkins can run this script every day and post an alert if there are dupicate keys.
=> jenkins script to check for duplicate data table entries

roles/common/templates/bashrc/get_jwd_path_galaxy.py.j2
it wasn't working on staging where IDs of jobs have 6 digits: path for job 116740 is /mnt/galaxy/tmp/job_working_directory/000/116/116740 instead of /mnt/galaxy/tmp/job_working_directory/116/116740
=> fix get path logic for short job ids

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
GPU is available after applying updates and rebooting to get kernel modules, device drivers, etc in sync
=> pulsar-qld-gpu3 online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
these tools have been failing with conda envs on pulsar-mel3. All are good to go with singularity_enabled for all versions
=> singularity for all ivar and lastz

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Set a minimum of 2c/10GB because there have been OOM errors from stacks jobs with default params
=> Set baseline mem for all stacks tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Java options might not be being passed through the normal `_JAVA_OPTIONS` environment variable.
I doubt this will fix pilon but this should be tried first
=> extra environment variable for pilon

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
a bunch of pilon jobs failed because the tool had the `_JAVA_OPTIONS` environment variable but not the `SINGULARITYENV__JAVA_OPTIONS` environment variable.
All tools can have java options set - they won't be used if it's not a java tool anyway. The lack of propagation of regular environment variables for container jobs is annoying but easy enough to get around if the variable can be put on the default tool like this.
=> All tools can have _JAVA_OPTIONS

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There is probably a reason data managers are never scheduled to pulsar, but this job needs more memory than it can have anywhere else, so worth a try
=> bwa_mem2 data manager to run on pulsar-qld-high-mem1

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Update mem values in destinations.yml.j2 so that the max allowed is the amount allowed in the slurm scheduler for the normal-sized VMs (32000/64000/128000 MB limits, corresponding to 31.25/62.5/125GB). Some were set higher than the slurm limit, some lower.
Revert scheduling of bwa_mem2 data manager since it cannot run on pulsar and enable singularity for all data managers.
=> update max mem for some worker VMs

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-qld-gpu3 needs to be taken offline so that Nvidia updates can be applied.
=> put pulsar-qld-gpu3 offline for nvidia updates

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There is a TODO here to account for reference genome size in history allocation. Both EU and Main do this for reference genome from history but not built in reference.
=> bwa_mem2 jobs need lots of memory always

templates/galaxy/webhooks/toolmsg/config.yml.j2
This one was easier - it still works on 24.2 but I changed it to `type: onload` to get rid of the blank button in the masthead.
=> Switch toolmsg to type 'onload'

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
looking into the possibility that data managers have been nerfed by singularity volume rules. Trying to override these at the tool level has not worked.
=> disable singularity for sam data manager

host_vars/dev.gvl.org.au.yml
Sorry, I called it `microgalaxy` instead of `microbe`
=> Fix subdomain name typo

host_vars/galaxy.usegalaxy.org.au.yml
This ensures that if there are local changes to WALLE's checksums.yml file (which there shouldn't be on prod), it will still be downloaded/updated from the global "intergalactic most wanted" repo. If we want to add checksums to prod WALLE, the correct approach is to add them to the IGMW list.
=> Force update local WALLE DB

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
because the mem/cores ratio is most suitable for the allocation
=> super huge hifiasm jobs prefer pulsar-high-mem1

host_vars/dev.gvl.org.au.yml, host_vars/galaxy-handlers.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml, templates/nginx/galaxy-handlers.j2, templates/nginx/galaxy.j2
Rolling restarts stopped working with release 24.2 and the galaxy and galaxy_update_configs playbooks have been broken as a result. Switching to using ports instead of sockets fixes this.
This also adds an extra gunicorn on dev
=> use ports instead of sockets for nginx bind

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
At the moment it's breaking because the `_days` variable is undefined, so the error message is 'unhandled exception while caching dynamic rule'
=> fix interactive tool restriction error message

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2
This is ugly but I can't think of another way to manage this. There are jobs with mem values that are high but not too high to run on slurm. Under some circumstances slurm will be chosen for these jobs and if the large workers are jammed with long running blast jobs, they will have nowhere to go. It's better to send them to high memory pulsar instead of slurm if pulsar is an option.
=> remove slurm from candidate destinations when mem is high and there are other options

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Let pulsar-qld-high-mem1 run "quick" jobs while it waits for the last job to finish.  The tools tagged with pulsar-quick that can run there are bwa_mem2 and minimap, better than nothing.
=> pulsar-quick for pqhm1

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
mothur_cluster_split jobs rarely use over 100GB
=> medium sized rule for mothur_cluster_split

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
pulsar-QLD needs an outage for various restarts, so it may only run quick jobs for now. This could be efficient if we could find enough job types to add the 'pulsar-quick' tag to.
Limit braker3 to 2 jobs per person
=> tpv prep for QLD outages

group_vars/galaxyservers.yml
GA does not need this container resolver option is never used - from handler logs it is the order of trying resolvers is clear and it never gets as far as build_mulled_singularity.
=> remove build_mulled_singularity from container resolvers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
For QLD hypervisor maintenance
pqhm1 -> offline. Current jobs will be finished by tomorrow and I can let them know.
pqhm0 -> require 'pulsar-quick' so this can be then next one to take offline.
=> Set pqhm1 to offline and pqhm0 to pulsar-quick

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_destinations.yml.j2, host_vars/dev.gvl.org.au.yml
Test overriding the job_working_directory job working directory for pulsar jobs only. All jobs have a JWD on galaxy, including pulsar ones. The location of the galaxy JWDs can be tricky when job outputs are being posted back to galaxy by via the upload store.
=> Dev: Set job_working_directory in TPV for all remote pulsar destinations

hosts
rebuilt VM pulsar-qld-blast. New IP addresses added to inventory. Note that `internal_ip` here refers to the `qld-data` network.
=> update pulsar-qld-blast IP address

host_vars/galaxy.usegalaxy.org.au.yml
Since a bug has been fixed, there are no longer lots of error messages in the gunicorn logs, everything is smaller and we can have log_level: TRACE again, as set in group_vars/galaxyservers
=> Do not override log_level in host_vars/galaxy

host_vars/galaxy.usegalaxy.org.au.yml
daily stats collection is running all of the influx friendly queries in gxadmin for time window since the beginning of time. Recently there has been a daily spike of ~15GB of database disk use at about the time that the daily stats script is run
=> disable daily stats collection for now

host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/pulsar-qld-blast.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml
even with 250GB of cache space available, pqhm1 is cleaning out its cache several times a day. Making space for this seems more pressing than space for files. If file space becomes an issue this can be revisited.
=> really big cvmfs caches for high mem and blast

host_vars/galaxy.usegalaxy.org.au.yml
I have tried all of the slurpable values and cannot find one that causes a big spike. It isn't the jobs query. Grafana stats including GA landing page are missing values from these queries.
=> add_daily_stats true again

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
The aim is to direct kraken2 training jobs with minikrakendb to pulsar-nci-training and let other kraken2 training jobs run as regular jobs.
The parameters are too specific to test with `tpv dry-run`. If it passes lint, I'll merge it, see what happens and revert if need be.
=> training destination for minikraken2 kraken2 jobs

README.md
This also caused me an issue with `python==3.12`:
`'_AnsiblePathHookFinder' object has no attribute 'find_spec'`
=> README - add python version requirement

group_vars/galaxy_etca_slurm.yml
For the older version of msconvert on GA (3.0.20287.2), jobs are failing on workers 4-6 because the .wine directories have 1777 perms instead of 0700.
=> add a slurm partition for msconvert-friendly workers

dev_playbook.yml, templates/nginx/galaxy-dev.j2, templates/nginx/galaxy.j2
Add some filtered Nginx log files for Galaxy Labs usage reporting. These log statements will allow us to capture visits and tool clicks in each Galaxy Lab.
See `/var/log/nginx/labs-welcome.access.log` on dev.gvl.org.au for an example log file. This file receives one log line per Galaxy Lab welcome page load:
```
cameron@dev:/var/log/nginx$ cat labs-welcome.access.log 
1.128.110.63 - - [08/Apr/2025:03:51:13 +0000] "GET /welcome HTTP/1.1" 302 281 "https://genome.dev.gvl.org.au/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36"
```
And  `/var/log/nginx/labs-tools.access.log` receives two lines (GET + POST) per tool form load in a Galaxy Lab:
```
cameron@dev:/var/log/nginx$ cat labs-tools.access.log 
1.128.110.63 - - [08/Apr/2025:03:50:45 …
```
=> Collect labs logs

host_vars/galaxy-misc-nfs.usegalaxy.org.au.yml
New 4TB volume is replacing the 3TB volume but has the placeholder name `indices2` in the meantime.
We sync old to new and switch them on an early morning when there are no jobs running using the data. No hurry.
Then the old volume is recycled and there is volume matter that can be used to expand /mnt/tools
=> mount new custom indices volume on misc

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
stop long running helixer jobs from blocking dorado jobs
=> send dorado to gpu5 only, helixer to gpu4 only

templates/galaxy/config/galaxy_object_store_conf.yml.j2
Remaining perth NFS dirs are available on the QLD volume
Enable a test object store backend (pawsey_nfs_test) so that data can be purged from galaxy. I'll remove this afterwards.
=> read perthNFS2 and perthNFS4 from qld

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This has persisted in the configuration because Simon made a local alteration to the phyml wrapper to allow it to run with multiple threads. This was during pawsey times and we no longer have that wrapper, so phyml is single threaded.
=> remove large cpu/mem allocation for phyml

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Allow pulsar-qld-high-mem0 to take some of the bigger small-medium jobs
=> lower the min_accepted_mem to 50 on pqhm0

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, group_vars/galaxy_etca_slurm.yml, host_vars/galaxy.usegalaxy.org.au.yml
galaxy-w6 becomes training only
reduce concurrent slurm destination limit per user from 6 to 5
set limit per user to 2 for freebayes, sortmerna and some deeptools tools. This is too low and will need to be increased again, or maybe some of these tools are OK on pulsar.
=> update slurm conf and limits

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Allow the 8 cpu 32GB jobs to go to high memory pulsars as well, this should be fine except for eggnog
=> reduce min mem for pqhm0 and pqhm1

files/galaxy/gxadmin/gxadmin-local.sh
add uuid and object_store_id to `gxadmin local query-job-input-datasets <job_id>` and add equivalent query for output datasets
=> improve gxadmin local dataset queries

files/galaxy/gxadmin/gxadmin-local.sh
If a user starts a job running on a collection of datasets, then deletes the output data collections, the jobs are not terminated and go on and queue and run as usual. This is a bug - for jobs with dataset outputs, trashing all output datasets will delete the job.
This query is to detect those jobs that should not be running for a user ID. It might have been better use of time to write up a github issue to galaxy about the bug.
=> gxadmin local query for deleted collection jobs

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-nci-training online
pulsar-mel3 no longer training only
pqhm0 can still accept medium-sized jobs (30G+ RAM) including bakta and eggnog
pqhm1 can run jobs with 60G+ RAM
=> pulsar-nci-training online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
As a first pass, check that lotus2 is not quietly failing to allocate memory
=> override lotus2 small input rule from shared db

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There may be more we have to do to get the dbs into the right spot in the conda environment, provided that they are small. Tools should not be like this.
=> singularity_enabled: false for lotus2

roles/galaxy_labs_engine/handlers/main.yml, roles/galaxy_labs_engine/tasks/main.yml
I added a handler that calls the new `manage.py update_cache` command if the code has changed.
This clears the cache and re-renders and caching all entries that have been viewed in the last 30 days.
It prevents old lab pages from being served from the cache, especially following UI modifications.
=> Labs engine update cache handler

files/galaxy/config/tool_conf.xml
There is a toolshed tool that does the same thing and looks identical in the panel. This is being hidden instead of removed so that existing workflows using the built-in tool are unaffected.
=> hide the builtin sort tool

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There are a lot of OOM jobs for these tools. This PR copies Galaxy Main’s memory allocation rule for bigwig that scales memory with file size. It would increase the mem allocation for most of the jobs that have run out of memory.
=> copy Galaxy Main’s scaling rule for bigwig converters

roles/slg.db-backup/defaults/main.yml
Every morning usage of `/mnt` on galaxy-backup spikes above 90%, let’s keep fewer of these on disk. JL is this the right way?
=> reduce retention_disk variable in galaxy db backup from 7 to 5

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_vortex_config.yml
Galaxy Main assigns memory to kraken2 jobs based on the size of the reference file using os.path.getsize() on the file path it gets from the job params.
=> test galaxy main kraken2 rule on dev

group_vars/pulsar_QLD/pulsar-QLD_workers.yml, group_vars/pulsar_mel3/pulsar-mel3_workers.yml, group_vars/pulsar_nci_training/pulsar-nci-training_workers.yml
Small/medium workers that have 200GB mounted disks can use 100GB for cvmfs cache
=> bigger cvmfs caches for small workers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Borrow an alphafold pulsar for dorado. gpu4 and gpu5 both have long running helixir jobs. I’ll merge this quick before users turn up with alphafold jobs.
=> unjam dorado queue

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.yml.j2
read user-data-7 from the 2nd volume attached to exports, and call it aarnetNFS7 to be consistent with other folder names
=> move user data 7 to qld

templates/galaxy/webhooks/toolmsg/script.js.j2
Code on usegalaxy.org.au client looks fine - diann tool ID should be matching the configured toolmsg. Maybe debug logs will help me understand.
=> Enable toolmsg debug console logs

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
metaphlan and metaphlan2 are overrepresented in OOM jobs
=> more memory for metaphlans

galaxy-db_playbook.yml, group_vars/all.yml, replicant-galaxy-db_playbook.yml
Using a replication slot runs the risk of db disk at ETCA filling up with WALs if the replication db stalls. Without the replication slot there is a risk of the replica falling behind, but this seems like good trade-off.
=> do not use replication slot on galaxy db

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
picard does not honour ‘tmp_dir: true’, apparently it doesn’t respect the $TMP_DIR environment variable and JAVA_OPTIONS is the way to go. Should resolve issues from the past few days with worker disks filling up.
=> picard tmp

host_vars/replicant-galaxy-db.yml, replicant-galaxy-db_playbook.yml
This was supposed to be a replica, for now it's just a VM running postgres with a backup. It needs its own host_vars file because declaring host_machine_users inline didn’t work.
=> replicant galaxy db changes

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Mem is being set to 20 from shared_db and not only is this unnecessary, this tool seems to need far less than the default.
‘gxadmin local query-tool-memory mothur_venn’ shows no job from the past year that used more than 1GB.
=> reduce mem to 2 for mothur_venn

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Hello! This is a non-urgent request for more RAM for large RagTag jobs.
I tried to do a whole genome alignment with two genomes of around 2 Gigabases each and ran out of RAM (GA job 4043685).
I don't know how much RAM is enough, I haven't tested it locally  
Thanks :)
=> More RAM for large RagTag alignment

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Years ago we tried using singularity containers from CVMFS. There were performance issues on pulsar-nci-training in particular, where test jobs for busco were taking hours to run. It may be different now because Steele and Alex fixed the stratum 1 server and because the CVMFS caches are bigger on the worker nodes.
It would be very good :crossed_fingers: if this were to work out because with the current configuration, galaxy needs to contact quay.io for every single pulsar singularity job and this has been timing out lately.
There is an explanation of `cache_directory_cacher_type: dir_mtime` here: https://github.com/galaxyproject/galaxy/blob/da7fdc814d94a795f50de6856c9b86086c0baac8/doc/source/admin/container_resolvers.rst#parameters
=> try out cvmfs singularity on pulsar nci training

group_vars/pulsarservers.yml
I think pulsar "ghost jobs” (jobs running in galaxy but long since finished on pulsar) could be coming about sometimes when pulsar sends the acknowledgment while the job’s handler is restarting.
=> update amqp max retries for pulsar

templates/galaxy/config/galaxy_job_conf.yml.j2
Whatever is holding the handlers up apparently comes from DATA_FETCH jobs.  These have been restricted to run on handler_0 only which simplifies things a bit. handler_0 is being restarted regularly and the other handlers are fine now.
=> restrict DATA_FETCH to handler_0

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml.j2
Test users can put ‘singularity’ in their history tags to run tools with singularity even if they are not configured to do so. There is no equivalent for disabling singularity and this would be useful.
=> give test user ability to test tools without singularity

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
I’ve added a long comment here too because this flies in the face of what we are trying to do. The latest version of this tool has issues running in the singularity container (previous versions were fine) and even though it’s a good pulsar tool, conda envs on pulsar are harder to maintain.
=> Change tpv entry for mummer_nucmer: no singularity, no pulsar

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
The local TPV ranking function looks at the resources used as a proportion of total resources at a destination. When the slurm-training destination is in use the jobs do not count towards the slurm destination’s resource use but they should. If the training jobs are not accounted for, the slurm destination appears to be be more available than it is, so it gets too many jobs.
=> Update destination scoring

roles/galaxy_labs_engine/handlers/main.yml
Prevent task SSH timeout as this task can run for over a minute:
```
RUNNING HANDLER [galaxy_labs_engine : update labs cache] ***********************
fatal: [galaxy-labs]: UNREACHABLE! => {
"changed": false,
"unreachable": true
}
MSG:
Failed to connect to the host via ssh: Shared connection to 138.44.7.160 closed.
```
=> Make long running task async

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Overriding the pulsar_docker_volumes context variable should be enough without overriding rules, if it isn’t I will revert this.
=> take overridden rules out of destinations.yml.j2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
When most of the high memory pulsars were offline, pulsar-qld-gpu3 was diverted to running normal jobs. This is no longer needed.
=> return pqgpu3 to regular schedule

galaxy_update_configs_playbook.yml, jenkins/phone_in_utils/run_galaxy_update_configs.sh
Add a clause for jenkins_bot to be able to run all of the tasks in the galaxy_update_configs playbook and a script for jenkins to run this on demand (not connected to a trigger or cron)
=> jenkins task to run galaxy update configs playbook

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
I’ll merge this right away to check that jenkins still only runs the tpv tasks (not the other tasks in galaxy_update_configs)
=> extra memory for coverm_ tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is not fair on pqhm2 but is better than it filling up galaxy jwds
=> make gffread go to pqhm2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
broken gffread jobs can do less damage here. Increased memory requested to match destination requirements.
=> send gffread to pulsar-qld-high-mem2 with mem to match destination rule

roles/common/tasks/main.yml
I think `common` role is the right place to do this, that's where `apt update` runs (and fails).
=> Remove old CVMFS GPG key before it breaks `apt update`

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
As per request:
Could the memory allocated be increased for the tool Optitype
(OptiTypeHLA genotyping predictions from NGS data(Galaxy Version 1.3.5+galaxy0))?
The proteomics researchers that we are helping with workflows are finding that it fails
due to "job was terminated because it used more memory than it was allocated". -- however
it works on Galaxy Eu where its max memory usage was 83 GB
`gxadmin local query-tool-memory optitype` shows that jobs failed with 57GB input size, while most jobs have inputs < 1M and these succeed.
EU allocates 12 cores and 256G RAM in their TPV: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/tpv/tools.yml
Dropping this to 8 cores and 120G for inputs larger than 1G and allowing to run on pulsar. This may need further …
=> optitype tool requires more memory for large inputs

templates/galaxy/webhooks/tips/script.js.j2
So Galaxy tips are working on prod, but I didn't realise we actually have the tool recommendation feature turned on! I guess it only displays for tools that it has data for.
It think both are nice features, so for now I've added a bit of code to the webhook that will show either a Galaxy Tip, or the tool recommendations thing.
This is the current weird experience:
[Screencast from 2025-08-22 06-35-48.webm](https://github.com/user-attachments/assets/a2a72fff-408b-46ef-8dde-4a87acb08711)
=> Show 50/50 either tips or tool recommendation

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Juypter notebook being used to run crypto miners
=> disable juypter notebook

galaxy-workers_playbook.yml
On new VMs (still ubuntu 22.04) the `dj-wasabi.telegraf` role breaks due to the repo key not being dearmored. Existing VMs that have already added the telegraf repo don't appear to be affected, possibly due to the key already existing in the global keyring `/etc/apt/trusted.gpg`.
This workaround does what the `dj-wasabi.telegraf` role should do: download and dearmor the key (now to `/etc/apt/keyrings/` instead of `/usr/share/keyrings/` as recommended best practice). It then passes the location of the dearmored repo key via a variable `telegraf_repository_params`.
This approach has been manually tested on the new galaxy workers. This serves to make the workaround more permanent and documented.
@cat-bro For noting on new VMs.
=> workaround for broken apt-key in dj-wasabi.telegraf

roles/pulsar-post-tasks/tasks/ghost_jobs_functions.yml
Check that the jwd is there before retrying job preprocessing. If the wrong job ID is provided, that job will be set to error state in galaxy.
=> safety for retry ghost jobs function

jenkins/check_data_tables/check_data_tables_for_dups.py
The check_data_table_for_dups.py script is looking at data table entries and checking for duplicate values within a table. The point of this is to detect when reference data GA has in custom-indices is added to /cvmfs with the same key. If the duplicated values both comes from cvmfs they can be ignored.
=> add exception for data table check

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Built in tools CONVERTER_gff_to_fli_0 and CONVERTER_gff_to_interval_index_0. It seems suspicious that these would fail for files as small as 80MB.
=> increase mem for gff converter tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2
Tools with a score under the pulsar score slurm threshold have a ‘prefer: slurm’ tag added which means that if slurm is in the candidate destinations, this is where they will go, even if they are pulsar-able.
If this is set to 0.25 instead of 0.3, some jobs will be mapped according to destination availability instead of sent straight to slurm, such as fastqc jobs.
=> update pulsar score slurm threshold
