usegalaxy-au/infrastructure

.gitignore, requirements.yml
these are the same as in ansible-galaxy-test-server except for certbot
=> add requirements.yml, add entries to gitignore for the roles

hosts
ansible-playbook . . . . --private-key <path to key>
=> Add galaxyservers and dbservers, remove ssh path

dev_playbook.yml
=> [WIP] beginning of dev playbook with pre_tasks to mount volume

dev_playbook.yml, group_vars/galaxyservers.yml
This has been run, seems OK.  The playbook can be run repeatedly with ansible reporting changes=0
=> Finish the pre-tasks for dev_playbook

ansible.cfg, dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, requirements.yml, roles/common/tasks/main.yml, templates/galaxy/static/welcome.html.j2
This is a WIP of settings for galaxy composed of the base settings for certbot, wsgi, nginx defined in the tutorial and production config settings.
It looks like we don't need the uchida.miniconda role at all since conda_autoinit is set to true.
There are a bunch of settings in here that are commented out because they still need checking/revising.  There are some setting values that will be set as default by the role or by galaxy, so we probably only need some of these.
=> [WIP] group variables for galaxy

.gitignore, dev-queue_playbook.yml, dev-workers_playbook.yml, dev_playbook.yml, group_vars/all.yml, group_vars/dev_workers.yml, group_vars/galaxyservers.yml, host_vars/dev-db.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, requirements.yml
=> add cvmfs role to dev and dev workers

host_vars/staging.usegalaxy.org.au.yml
This reflects the current job_conf.xml on staging
=> comment out pulsar in job_conf

files/galaxy/config/nagios_tool_conf.xml, files/galaxy/config/tool_conf.xml, files/galaxy/config/user_preferences_extra_conf.xml, group_vars/galaxyservers.yml
This is a combination of release_20.05's tool_conf.xml.sample and our tool section names and ordering.  Defining the layout here saves us from having to rearrange entire sections in integrated_tool_panel.xml.  This is a [WIP] because there may be galaxy builtins that we use that are missing from the sample and need to be added in.
=> Tool conf for galaxy laying out section order

dev-db_playbook.yml, dev-pulsar_playbook.yml, dev-queue_playbook.yml, dev-workers_playbook.yml, dev_playbook.yml, group_vars/all.yml, group_vars/dev.yml, group_vars/nfs_servers.yml, group_vars/pawsey.yml, group_vars/staging.yml, host_vars/pawsey-job-nfs.usegalaxy.org.au.yml, host_vars/pawsey-misc-nfs.usegalaxy.org.au.yml, host_vars/pawsey-user-nfs.usegalaxy.org.au.yml, pawsey-db_playbook.yml, pawsey-job-nfs_playbook.yml, pawsey-misc-nfs_playbook.yml, pawsey-user-nfs_playbook.yml, pawsey_playbook.yml, staging-db_playbook.yml, staging-pulsar_playbook.yml, staging-queue_playbook.yml, staging-workers_playbook.yml, staging_playbook.yml
These need a bit of re-factoring to make them a bit more generic but this will do for now.
=> Initial scripts for pawsey-nfs servers

group_vars/galaxyservers.yml, templates/nginx/galaxy.j2
based on https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/roles/geerlingguy.nginx/templates/nginx.conf.j2, this is probably what it needs
=> add 'sendfile on' to nginx conf

files/galaxy/config/tool_conf.xml
This file was generated from the tool_conf.xml.sample.  Add anything that was in our tool_conf.xml previously and is not here
=> add tools to tool_conf.xml

group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
These were being set based on the value of use_cloudstor_conf but they need to be set independently
=> set git_repo and git_commit_id in host_vars, set dev git_commit_id to release_20.09_cloudstor

group_vars/all.yml, group_vars/pawsey.yml, group_vars/pulsar_mel3/pulsar-mel3.yml, group_vars/pulsar_paw/pulsar-paw.yml
Define telegraf_agent_version in all.yml, also move galaxy_cvmfs_server_urls, grafana_server_url, telegraf_agent_package_method, telegraf_agent_hostname to all.yml.
This also adds cvmfs_cache_base to pulsar-paw, same value as for mel3.
=> update telegraf_agent_version to 1.17.2, put this in all.yml with some other common variables

dev-queue_playbook.yml, pawsey-queue_playbook.yml, roles/common/tasks/machine_users.yml, staging-queue_playbook.yml
Also add `validate: /usr/sbin/visudo -cf %s` for steps that change sudoers
=> Allow all users to run `sudo sacct`

group_vars/pulsarservers.yml
from
https://github.com/galaxyproject/usegalaxy-playbook/blob/e8f57398058fcc313308dca25e864583550e2233/env/common/host_vars/jetstream-iu0.galaxyproject.org.yml#L77
=> Add some pulsar retry parameters copied from usegalaxy-playbook

terraform/aarnet-dev/instances.tf, terraform/aarnet-dev/networks.tf
Added terraform used to provision dev instance at AARNet.
=> add terraform for aarnet dev infrastructure

scripts/install_builtin_dependencies.py
we may be able to automate this in the ansible by writing a gxadmin query that creates a user and returns its api key
=> add script for installing galaxy built-in tool dependencies

group_vars/galaxyservers.yml
=> leave out outputs_to_working_directory for now

group_vars/galaxyservers.yml, host_vars/aarnet-dev.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, templates/galaxy/config/oidc_backends_config.xml.j2, templates/galaxy/config/reports.yml.j2
Fix the issue with galaxy_config across the vars files.
Marking this as draft so I can test it out more tomorrow
=> change __galaxy_config to host_galaxy_config, galaxy_config to group_galaxy_config and combine the two

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
This reverts commit 1439a414b74df0cb49a9f77eb7e78130e184845c.
=> Revert "move pulsar-mel jobs (#199)"

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
This reverts commit f82330d806216400871c538ce983799903696f0c.
=> Revert "no jobs for pulsar-mel3 (#207)"

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
move small spades, small trimmomatic and medium bowtie2 from pulsar-mel3 to slurm
=> move some smaller jobs back to slurm

roles/slurm-post-tasks/tasks/main.yml
there was an uncommitted change
=> fix slurm-post-tasks role

files/galaxy/dynamic_job_rules/aarnet-dev/dynamic_rules/tool_destinations.yml, host_vars/aarnet-dev.usegalaxy.org.au.yml
+ add mid and big dests for nci
=> remove dev pulsar from aarnet dev

files/galaxy/dynamic_job_rules/staging/dynamic_rules/tool_destinations.yml, host_vars/staging.usegalaxy.org.au.yml
need slurm1 dest on staging for #240
=> give staging job conf a slurm1 destination

jenkins/update_labels/update_tool_labels.sh, jenkins/update_labels/update_tool_labels_playbook.yml
This has been running after weekly tool updates but only on staging, seems fine
=> Uncomment jenkins running of update labels playbook on production

host_vars/pawsey.usegalaxy.org.au.yml, roles/remote-pulsar-cron/README.md, roles/remote-pulsar-cron/templates/remove_pulsar_jwds.py.j2
It needs a connection string when not being run locally
=> Fix cron role last time

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
send circos to the local runner for a test, I'll revert this afterwards
=> temporary circos rule

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
This reverts commit fdbe2c49dbc71d2b8f12f31d683a2db4a49d443f.
=> Revert circos rule

scripts/install_builtin_dependencies.py
This should be only for built-in tools by default.
=> update the script that installs dependencies for built-in tools

terraform/aarnet-prod-pulumi/README.md, terraform/aarnet-prod-pulumi/__main__.py
Added pulumi python code for deploying VMs and a short README/intro to starting with Pulumi. Code has been tested working on our Openstack instance.
If you'd like to try this out yourselves, the only things that should need to be changed are the UUIDs at the very top, and the dictionary describing the VMs.
=> aarnet-production infrastructure deploy

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
jobs above > 100MB go to pulsar-mel3_mid
=> update khmer_abundance_distribution_single rule

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
megahit passes all of its tests on pulsar
=> megahit to pulsar

host_vars/aarnet-db.usegalaxy.org.au.yml, host_vars/dev-db.usegalaxy.org.au.yml, host_vars/pawsey-db.usegalaxy.org.au.yml, host_vars/staging-db.usegalaxy.org.au.yml
=> give reader permission to delete tiaas roles

group_vars/galaxyservers.yml
=> put back '/config' in paths

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml
there was an undefined var in host_vars for this role
=> replace undefined variable for galaxy_stats

host_vars/dev.usegalaxy.org.au.yml
dev is already on 21.05, update this in host_vars
=> update to 21.05 for dev in host_vars

host_vars/pawsey-user-nfs.usegalaxy.org.au.yml, pawsey-user-nfs_playbook.yml
@Slugger70  I've put this at ground level: /user-data-2 on the VM but can move it.  This has not been run.
=> add new volume for pawsey-user-nfs

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/destination_mapper.py, files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml, host_vars/pawsey_job_conf.yml
This is so I can temporarily attached Pulsar Pawsey to the new AARNet server for testing purposes.
=> Temporarily removed pawsey from pulsar destinations

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
updates for all users
we could add user-specific rules here or do something in the destination_mapper script
=> pulsar-mel3 destinations for racon, medaka_consensus_pipeline, medaka_variant

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
>5GB input to pulsar-mel3_big
add user rule
=> alter rule for minimap2

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
Revert this when mel3 is up again.
Some have
`fail_message: This job cannot run at this time, please check again tomorrow`
=> Send mel3 things to mel2 or fail destinations

aarnet_playbook.yml
=> skip slg stats for now

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/destination_mapper.py, files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/pawsey_job_conf.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au.yml, host_vars/pulsar-paw/pulsar-paw.genome.edu.au.yml
Baseline changes to dtd, there will be another commit to take out mel3 for the time being
=> pawsey job conf and tool destination changes

host_vars/pawsey.usegalaxy.org.au.yml
from looking at this pr https://github.com/usegalaxy-au/infrastructure/pull/300 looks like we only need to add these 3 lines
=> add file sources conf to pawsey host_vars

host_vars/pawsey.usegalaxy.org.au.yml, roles/nginx-upload-module/defaults/main.yml, roles/nginx-upload-module/tasks/cron_delete_files.yml, roles/nginx-upload-module/tasks/main.yml
Add optional daily job to delete files from upload_store/uploads and upload_store/job_files with mtime +1
=> Cron job for upload store

host_vars/pawsey_job_conf.yml
keep the user limit the same (4)
=> Allow 12 concurrent jobs on pulsar-mel3_mid

jenkins/update_labels/update_tool_labels_playbook.yml
=> copy the hidden tools file

group_vars/all.yml, roles/common/tasks/machine_users.yml
+ allow more characters for node name in sinfo
=> copy .bashrc vars to ubuntu

files/galaxy/dynamic_job_rules/pawsey/dynamic_rules/tool_destinations.yml
added a missing line to mimodd_align
=> Igormakunin patch 1

files/galaxy/dynamic_job_rules/dev/dynamic_rules/destination_mapper.py, files/galaxy/dynamic_job_rules/dev/dynamic_rules/tool_destinations.yml, host_vars/dev.usegalaxy.org.au.yml
To test the latest maxquant (not installed on galaxy yet) with as close as possible conditions to those on staging
=> give dev a 1-core slurm destination

host_vars/pawsey.usegalaxy.org.au.yml
add high mem pulsars and pulsar-paw to pulsar cron job list and increase the frequency of jobs on pulsar-mel2
=> add pulsar-paw and high mem pulsars to rpc_pulsar_machines

dev_playbook.yml, pawsey_playbook.yml, roles/galaxy-pg-cleanup/defaults/main.yml, roles/galaxy-pg-cleanup/tasks/main.yml, roles/galaxy-pg-cleanup/templates/run_cleanup.sh.j2
Cron job for galaxy to run the run_cleanup.sh script on Mondays and Thursdays at 6am AEST
=> role for adding run_cleanup.sh script

files/galaxy/config/object_store_conf.xml, group_vars/pawsey_workers.yml, host_vars/pawsey-user-nfs.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, pawsey-user-nfs_playbook.yml
add variables for a new volume on pawsey-user-nfs.  Marking this as a draft since I haven't created the volume.
=> add variables for pawsey user-data-3

files/galaxy/config/object_store_conf.xml, host_vars/pawsey.usegalaxy.org.au.yml
after running the playbook with this change nginx needs to be reloaded
=> change file path and object store to write to user-data-3

roles/galaxy-pg-cleanup/tasks/main.yml
I've fixed this up manually on galaxy's crontab..
=> add cron minute to galaxy pg role

host_vars/dev.usegalaxy.org.au.yml, scripts/convert_job_conf.py, templates/galaxy/config/dev_job_conf.yml.j2
yaml job conf for dev, seems to work
=> dev job conf yml

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Update import in rule: this is not a functional rule in the dev tpv but is good as a sample rule.
=> fix high-mem rule in dev tpv config

host_vars/pawsey-db.usegalaxy.org.au.yml
already deleted from the conf file on db
=> switch off pawsey-db logging

host_vars/dev.usegalaxy.org.au.yml, scripts/convert_job_conf.py, templates/galaxy/config/dev_job_conf.yml.j2
currently config breaks galaxy on dev
=> update handling block in dev job conf: handling.processes is not a list

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Argument-based rule for tpv.  This is mostly code copied from dynamic_destinations.py in galaxy.  Code for this could be added to total-perspective-vortex as a helper function.
=> send paired fastq bwa_mem jobs to pulsar on dev

host_vars/pawsey.usegalaxy.org.au.yml, templates/galaxy/config/pawsey_job_conf.yml.j2
This should be a direct translation from what is currently being templated to xml.  A similar config is working on dev.  I'll check that the limits are understood by galaxy before I take [wip] off this
=> pawsey job conf yaml

group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
Update dev server to galaxy release 21.09.  I haven't altered the file sources conf file but there are probably some new options that could be included from https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/file_sources_conf.yml.sample.  
There are some new galaxy.yml options but probably none that need non-default values.
=> Update dev to release 21.09

dev_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, host_vars/dev.usegalaxy.org.au.yml
install tpv with commit id rather than force reinstalling it each time
add a rule to limit concurrent running of a tool overall or per user
=> dev tpv: parameterise commit id, limit by tool

files/galaxy/config/object_store_conf.xml, host_vars/pawsey.usegalaxy.org.au.yml
=> switch pawsey object store to put user-data first

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/default_tool.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, staging_playbook.yml, templates/galaxy/config/dev_job_conf.yml.j2, templates/galaxy/config/staging_job_conf.yml.j2
Move tpv rules to /mnt/galaxy/dynamic_job_rules/total_perspective_vortex.  Very soon there will be logic in the ansible-galaxy role to copy templates using this structure.
Add tpv config for staging
=> move tpv files and add tpv to staging

pawsey_update_job_conf_playbook.yml
=> update update_tool_destinations playbook

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
Add high mem rules for tools that had user-specific high mem rules
=> add more high mem rules

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/default_tool.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
update tpv on slurm so that it can use 3 slurm cores concurrently (up from 2)
=> update dev tpv config to make it easier to use

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
There are conda errors in the logs from the last few days and `conda install` is failing.
=> take pulsar-high-mem1 offline to sort out conda issue

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
send hisat2 jobs with inputs over 20GB to high mem pulsars.
=> send large hisat2 jobs to high mem

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/users.yml
Allow pulsar users to run jobs even when the destinations are marked as offline.
Add the large training tag to some pulsar compatible tools.
=> update pulsar users and training tools

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
add tools to dev tpv for pulsar azure testing
=> Dev tpv updates 20211207

jenkins/update_labels/hidden_tools.yml, jenkins/update_labels/update_tool_labels_playbook.yml
add vlefort owned phyml to this list
add a commit from a branch that stops the playbook exiting too early
=> hide vlefort phyml

group_vars/galaxyservers.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-nci-test/pulsar-nci-test.usegalaxy.org.au.yml, pulsar-high-mem1_playbook.yml, pulsar-nci-test_playbook.yml, requirements.yml
This works but it needs a change in ansible-miniconda to be able to install mamba into conda's base environment.  https://github.com/galaxyproject/ansible-miniconda/pull/2
=> mamba for pulsar-nci-test and pulsar-high-mem1

pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml, pulsar-mel2_playbook.yml, pulsar-mel3_playbook.yml, pulsar-nci-training_playbook.yml, pulsar-paw_playbook.yml, pulsar-qld-high-mem_playbook.yml
the pulsar playbooks fail without this
=> add the vault file for maintenance_key to production pulsars

dev-workers_playbook.yml, group_vars/dev_slurm.yml, group_vars/dev_workers.yml, terraform/dev/dev-initial.tf
Add a 100G volume for dev w1 and update RealMemory for the slurm node based on MemTotal in /proc/meminfo
=> add a volume to dev w1

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml
set pulsar-high-mem2 to offline so queued jobs can be restarted
=> phm2 offline again

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, templates/galaxy/config/dev_job_conf.yml.j2
There are some unknown values such as the number of cores/mem the azure destination can have and the name of the partition
=> set alphafold destination in dev tpv

dev-workers_playbook.yml, dev_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, group_vars/dev_workers.yml, host_vars/dev.usegalaxy.org.au.yml, requirements.yml
TODO: add singularity to dev-pulsar, pulsar-nci-test
Also TODO: see whether the singularity path needs to be moved to somewhere on the worker tmp disk
Ready to merge with todos, it is needed for tool development.  Singularity and golang are already installed on dev and dev-w1.
=> Add singularity to dev and dev worker

files/galaxy/config/local_tool_conf_dev.xml, templates/galaxy/config/dev_job_conf.yml.j2
update dev_job_conf.yml.j2
update local_tool_conf_dev.xml (file has moved back to /mnt/galaxy/local_tools)
=> re-sync dev playbooks

group_vars/pawsey_slurm.yml
This will require running: pawsey-queue, pawsey and pawsey-worker playbooks to take effect
=> Restored training partition in slurm

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/users.yml
jenkins_bot maxquant jobs have been going to the maxquant partition and holding up tool tests
=> send all jenkins_bot jobs to main partition

host_vars/pulsar-high-mem1/pulsar-high-mem1.yml
`mamba install` throws an error.  I've spent about half an hour trying to fix this but have not found a solution.
=> use conda as conda_exec on pulsar-high-mem1

dev_update_configs_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/interactive_tools.yml, host_vars/dev.usegalaxy.org.au.yml, templates/galaxy/config/dev_job_conf.yml.j2
Add interactive tools to dev tpv and remove the mapping from dev_job_conf.yml.j2.
=> add interactive tools to dev tpv and add dev_update_configs_playbook.yml

host_vars/pawsey-misc-nfs.usegalaxy.org.au.yml, pawsey-misc-nfs_playbook.yml
This adds the new volume at /custom-indices on pawsey-misc-nfs.
=> update misc nfs playbook to add custom-indices volume

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/interactive_tools.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/interactive_tools.yml, templates/galaxy/config/pawsey_job_conf.yml.j2
The reason it is broken is that the jobs have not being going to interactive_pulsar
=> fix typo in tool id for interactive_tool_cellxgene

files/galaxy/config/local_tool_conf_dev.xml
Hi @cat-bro , can I install cactus from /home/tom for testing?
I also removed LINKS since it's in toolshed / tools-iuc now - but not sure about this.
=> Install cactus 

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml
update pilon rule to use 9 cores
=> try giving pilon more cores/mem

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/destinations.yml, templates/galaxy/config/pawsey_job_conf.yml.j2
=> slurm-training destination

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, jenkins/update_tool_destinations.sh
update_tool_destinations.sh does not work for dev, this should fix it
=> double quote grep expression in jenkins script

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
@TomHarrop I'm wondering if this might be ok without binding /etc/exports because of `docker_set_user: 1000`
=> send cactus to pulsar with docker and maximum memory, add cvmfs to volumes

ansible.cfg, group_vars/galaxyservers.yml, templates/galaxy/static/welcome.html.j2
Put GMS into production by updating `welcome.html.j2` and `galaxy_australia_website` variable.
=> Switch all landing pages to GMS

terraform/aarnet-prod-pulumi/__main__.py
I've pulled this out into a separate PR, can be merged as long as it is ok with aarnet
=> 50G volume for ghost galaxy app

aarnet-db_playbook.yml, host_vars/aarnet-db.usegalaxy.org.au.yml
+ add a note that the instance might need rebooting at the end of the playbook
=> update aarnet db settings to be like pawsey's

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
switch to singularity bc of /etc/passwd issue
=> try cactus again on new dev-w1 with more ram

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
=> put aa limits on alphafold to test

aarnet-user-nfs_playbook.yml, files/galaxy/config/aarnet_object_store_conf.xml, group_vars/aarnet_workers.yml, host_vars/aarnet-backup.yml, host_vars/aarnet-job-nfs.usegalaxy.org.au.yml, host_vars/aarnet-misc-nfs.usegalaxy.org.au.yml, host_vars/aarnet-user-nfs.usegalaxy.org.au.yml, host_vars/aarnet.usegalaxy.org.au.yml
use aarnet_object_store_conf.xml with just one uncommented entry for /mnt/user-data-test
=> add /dev/vdbs, edit shared mounts for aarnet and aarnet workers

pawsey_playbook.yml
these were updated for aarnet last year because there were some things missing
=> update lsync steps in pawsey playbook

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/users.yml
only the top user is counted because of an indentation error
=> fix alignment in users.yml

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Test maxquant using pulsar node (dev-pulsar)
=> Add local maxquant to vortex_config.yml

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
fixed spaces in the vortex_config.yml
=> fixed spaces in vortex_config.yml

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Same problem as https://github.com/usegalaxy-au/infrastructure/pull/770 and https://github.com/usegalaxy-au/infrastructure/pull/790. Only the Docker container works.
=> more protk tools that need the docker container

files/galaxy/dynamic_job_rules/aarnet/total_perspective_vortex/aarnet_tools.yml, files/galaxy/dynamic_job_rules/aarnet/total_perspective_vortex/aarnet_tpv_config.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/interactive_tools.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/interactive_tools.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/users.yml, scripts/convert_dtd.py
xref: https://github.com/galaxyproject/total-perspective-vortex/pull/18
=> Rename match clause to if in TPV

dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/dev.usegalaxy.org.au.yml, requirements.yml, templates/nginx/galaxy.j2
Add role and variables for galaxyproject.tusd.  This includes adding a block to `templates/nginx/galaxy.j2`
=> enable tus on dev

files/galaxy/dynamic_job_rules/pawsey/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml, jenkins/update_tool_destinations.sh, staging_update_configs_playbook.yml
Include staging in Jenkins' copy of tpv files so that docker/singularity params can be more easily set on staging.
Set autodock_vina and chemfp tool wrappers to singularity_enabled.
=> enable singularity for some tools, extend CI tpv config copy to staging

files/galaxy/config/aarnet_object_store_conf.xml, host_vars/aarnet.usegalaxy.org.au.yml
last minute change for file path, currently using `/mnt/tmp/temporary-user-data` , will switch to `/mnt/user-data-5`
=> [do not merge][MOVING DAY] object store and galaxy_file_path change

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
phm1 seems to have gone read-only
=> set phm1 to offline

group_vars/all.yml, roles/slurm-post-tasks/tasks/main.yml
MaxRSS and NodeList need more space
=> update sacct format

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> Set singularity_volumes without qld for autodock_vina

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
cactus installation requested here: https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/735
=> Job rules for cactus

aarnet_update_configs_playbook.yml, host_vars/aarnet.usegalaxy.org.au.yml, jenkins/update_tool_destinations.sh, templates/galaxy/config/aarnet_object_store_conf.xml.j2
- Set a variable to control whether /mnt/files, /mnt/files2 are included in the object store and singularity/docker volumes
- Move aarnet object store to templates
- Add task for templating object store to aarnet_update_configs_playbook.yml
=> parameterise availability of object store volumes

aarnet_playbook.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, staging_playbook.yml
Set branch to release_22.01 + add tusd role and configuration to staging and aarnet
=> Staging and aarnet to 22.01

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
update maxquant_test job destination (TPV)
=> update job destination for maxquant_test

jenkins/update_labels/update_tool_labels.sh
=> Update jenkins tool labeller to run on aarnet

dev_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Send dev __DATA_FETCH__ temp files to /mnt/galaxy/tmp on dev to test this rule out for production.  I've created the dir /mnt/galaxy/tmp/data_fetch on dev.
=> Set dev env variable for __DATA_FETCH__ tmp

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> Add repeatmasker and repeatmodeler to tpv

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
not sure how much memory to give these
=> Add user, dest and rule for new pulsar azure user on dev

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
this is useful for testing some required_files rules for tools running on pulsar
=> extend test user on dev to require pulsar if history has pulsar tag

templates/galaxy/config/aarnet_job_conf.yml.j2
Turns out this was wrong in many places in the job conf
=> param should be docker_set_user

files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml
set staging tpv config to use singularity for cactus.
=> enable singularity for cactus on staging

host_vars/aarnet.usegalaxy.org.au.yml
switch qld files out in object store
=> switch legacy_file_mounts_available to False

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml
modify 'test_user' entity in users.yml
=> add dependency_resolution: none to singularity test params

files/galaxy/config/pawsey_object_store_conf.xml, host_vars/pawsey.usegalaxy.org.au.yml
added object store entry for the test folder
=> pawsey object store testing

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
@cat-bro trying cactus without `$defaults`
=> try removing volume specification for cactus tools

aarnet_update_configs_playbook.yml, files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
WIP until wrapper is on aarnet machine and scheduling details are confirmed
=> [WIP] add maxquant_test to local tool conf and add entry in tpv

dev-workers_playbook.yml, group_vars/dev_slurm.yml, group_vars/dev_workers.yml, hosts, terraform/dev/dev-initial.tf
Add dev-w2 and give slurm 2 additional partitions. Partitions now are
```
main: dev-w1
cvmfs: dev-w1
s3fs: dev-w2
```
=> add new dev worker and slurm partitions s3fs and cvmfs

dev_playbook.yml, group_vars/dev_workers.yml, host_vars/dev.usegalaxy.org.au.yml
+ comment out s3fs in dev playbook
=> mount the aws volume in dev and dev worker playbooks

group_vars/pulsar_mel3/pulsar-mel3_slurm.yml
pulsar-mel3-w3 and pulsar-mel3-w4 were resized a month ago. w4 was updated in the slurm config (#922), we were waiting for a job to finish on w3 to update this as well.
=> Update memory in slurm conf for pulsar-mel3-w3

templates/nginx/galaxy.j2
I thought single equal was right for this but ansible templating failed.  It worked when changed to == and the resulting file on dev looks right
=> Change = in galaxy.j2 template to ==

host_vars/staging.usegalaxy.org.au.yml, requirements.yml, templates/galaxy/config/staging_job_conf.yml.j2
Do not merge yet. We will go through this at 1pm
=> Changes for staging 22.05

aarnet_update_configs_playbook.yml, staging_update_configs_playbook.yml
Change the handlers in aarnet and staging update configs playbooks to use galaxyctl graceful.
=> Switch to galaxyctl graceful in restart handlers in update configs playbooks

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
This reverts commit 28922de8d95d87b3d762f53d0f61fbc7179d71f6.
=> Revert "set phm1 offline"

host_vars/dev.usegalaxy.org.au.yml, requirements.yml
Also added a new version of the cvmfs role that doesn't have "-" in the task names
=> Added fixes for dev web server gunicorn path

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml
from CH request in infrastructure channel
=> Add line to tiaas extra config

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
Revert "Set training pulsar offline and send training jobs to pulsar-mel2"
This reverts commit 65b641cd38b23293a6f275b657b10c7dedbade85.
=> set pulsar-nci-training to online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, host_vars/dev-queue.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_job_conf.yml.j2
Alphafold group jobs go to pulsar-azure-gpu with partition azuregpu0.  Vet school alphafold job go to pulsar-azure-1-gpu destination with partition azuregpu1.  The two destinations use the same job runner and everything runs on the same cluster.
=> new rules for alphafold

templates/galaxy/config/dev_job_conf.yml.j2
Raise destination registered_user_concurrent_job limits on dev, these were low because they were being tested
=> Raise concurrent job limits on dev

one-offs/conda_envs/aarnet_conda_playbook.yml, one-offs/conda_envs/conda_create_update.yml, one-offs/conda_envs/conda_environments.yml, one-offs/conda_envs/dev_conda_playbook.yml, one-offs/conda_envs/pulsar-QLD_conda_playbook.yml, one-offs/conda_envs/pulsar-mel2_conda_playbook.yml, one-offs/conda_envs/pulsar-mel3_conda_playbook.yml, one-offs/conda_envs/pulsar-nci-test_conda_playbook.yml
Maintain a yaml list of conda environments that differ from what is built from the recipe.  This includes old versions of multiqc, old versions of bowtie and environments that depend on old bowtie. We can use ansible to iterate through the list of environments, preinstall those that do not exist and fix those that do.
=> one-off task for updating conda environments

group_vars/aarnet_workers.yml, host_vars/aarnet.usegalaxy.org.au.yml
Add user-data-6 to shared mounts (not object store yet)
=> Add user-data-6 to shared mounts on aarnet and workers

group_vars/pulsarservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, hosts, pulsar-azure_playbook.yml, roles/slg.galaxy_stats/defaults/main.yml, roles/slg.galaxy_stats/templates/get_queue_size.py.j2, roles/slg.galaxy_stats/templates/secret.yml.j2
Update get_queue_size.py and secrets.yml templates
Update SINFO to allow 24 chars for hostnames
Update pulsar-azure in hosts and playbook to comment out everything but pulsar and slg.galaxy_stats roles
=> Update stats role and pulsar-azure IP

group_vars/aarnet_slurm.yml, hosts
Add the 2 new aarnet worker nodes aarnet-w9 and aarnet-w10.
=> add aarnet-w9 and aarnet-w10

terraform/dev/dev-initial.tf, terraform/pulsar-mel3/pulsar-mel3-initial.tf
- Import dev-handlers machine to dev's terraform state
- Update flavours for two pulsar-mel3 workers that were resized earlier in the year
=> Terraform updates

host_vars/dev.usegalaxy.org.au.yml
Update dev host vars to target branch `neoformit/release_22.05_login_flow`
=> Change galaxy repo to login flow branch

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
pulsar-qld-high-mem2 is ready to accept jobs, but reject all busco jobs
=> Put pqhm2 online reject busco

files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, jenkins/update_labels/tool_labels.yml
GTDB-Tk wrapper has been manually downloaded to prod server `local_tools`
=> Add gtdbtk v2.1.1 test local tool

group_vars/all.yml
for details on package, see: https://nicolargo.github.io/glances/
=> add glances CLU monitoring tool to common_packages

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> Fix gtdbtk_database_installer rule

files/galaxy/config/local_tool_conf_dev.xml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Need more cores to test this than I have on my dev VM. Thanks!
=> add cores for metawrap test

files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
I think my test job ran out of RAM. The same job completes on my desktop which has 64 GB.
=> add memory

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Getting errors on prod that don't happen when I run `planemo test` locally so I'd like to try the biocontainer.
=> use singularity for metawrapmg

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/pawsey.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, requirements.yml
We just need to wait for a new certbot role release from EU
=> Cloudflare certbot update

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
Hey @cat-bro can we replace this conf on Dev so I can test this with Maker? I think it will break it but I'd like to see the error.
=> Add maker mpi env on Dev

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml
See if this fixes Maker vortex conf
=> Set env var to string

host_vars/aarnet.usegalaxy.org.au.yml, templates/galaxy/config/aarnet_object_store_conf.xml.j2
Add `pawsey_file_mounts_available` var to host_vars/aarnet, same logic as legacy_file_mounts_available used for qld data
=> Pawsey online var for object store and volumes

aarnet_playbook.yml, dev-handler_playbook.yml, dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, staging_playbook.yml
Add SINGULARITY_CACHEDIR to aarnet and staging, reenable the change handlers in playbooks
=> Add singularity vars to aarnet + staging and reinstate handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/vortex_config.yml
Not sure if you can do this? :shrug: 
We want to singularity-enable all `ebi-gxa/scanpy*` tools right?
=> Param singularity on ebi-gxa scanpy tools

roles/install-tpv/tasks/main.yml
small fix needed for galaxy playbooks, will merge straight away
=> remove extra } from install-tpv role

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, host_vars/dev.usegalaxy.org.au.yml
@nuwang can you please check the change to destinations.yml.j2? By chaging max_accepted_cores/max_accepted_mem to max_cores/max_mem should jobs with larger cores/mem be scaled down to what is available?
=> Update dev tpv to version 2.0.1

files/galaxy/config/local_tool_conf.xml, files/galaxy/config/local_tool_conf_dev.xml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/vortex_config.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
metawrap is on the toolshed. Tool install request [here](https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/870).
=> remove local metawrap installation and update rules for toolshed

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Set database path for specific versions of alphafold
=> Version specific ALPHAFOLD_DB

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Set Melbourne high memory pulsars to online.
Divert pulsar blast jobs to pulsar-mel3.
=> Set all qld destinations offline in TPV

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
These tools were tested with Singularity on dev last year, but I never got around to requesting them once Singularity became available on prod.
=> Protk tools main

group_vars/galaxyservers.yml, templates/nginx/galaxy.j2
=> use galaxyproject.galaxy's errordocs feature

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add some TPV conf that will hopefully make gtdbtk test tool work.
(Upgrading GTDB-Tk to v2.3.3)
=> Gtdbtk upgrade

pulsar-qld-high-mem_playbook.yml
Since pqhm0 is out of order, switch maxquant_test machine to pqhm1.
=> update max_map_count for maxquant on pqhm1

aarnet_playbook.yml, host_vars/aarnet.usegalaxy.org.au.yml, pulsar-paw_playbook.yml, roles/slg.galaxy_stats/defaults/main.yml, roles/slg.galaxy_stats/tasks/main.yml, roles/slg.galaxy_stats/templates/current_stats.sh.j2, roles/slg.galaxy_stats/templates/daily_stats.sh.j2, roles/slg.galaxy_stats/templates/get_queue_size.py.j2, roles/slg.galaxy_stats/templates/secret.yml.j2
Update stats role so that it can be included in playbooks. Also fix db connection string in another role that was requesting data from aarnet-db's public IP.
=> Update stats role

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml
=> pulsar-high-mem2 offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/roles.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This reverts commit 5902e8051aae70396e869097ea63311c76c245a1.
=> Revert "Add training-exempt tag for alphafold and interactive tools"

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_destinations.yml.j2, host_vars/dev.usegalaxy.org.au.yml, templates/galaxy/config/dev_job_conf.yml.j2
This is a model for production destinations which have similar tags.
=> Put dev destination tags in host variables to be used by tpv and job conf

Makefile, scripts/ansible-find-upgrades.py
Add script from this gist: https://gist.github.com/hexylena/c60fe949dd76ce8e3116d2c745bfeb63
It goes through requirements.yml and for each role reports if there is a new version available.
=> Add Helena's script for finding updated versions of ansible roles

terraform/pulsar-QLD/backends.tf, terraform/pulsar-QLD/providers.tf, terraform/pulsar-QLD/pulsar-QLD.tf
Add pulsar-QLD terraform config
=> Import pulsar-QLD to terraform

host_vars/staging.usegalaxy.org.au.yml, roles/postfix-mail-relay/defaults/main.yml, roles/postfix-mail-relay/tasks/main.yml, staging_playbook.yml
New ansible role for installing and configuring postfix as a mail relay using smtp2go. Playbook and host_vars updated to test on staging.
=> Postfix install config staging

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Update `alphafold_test` tool with new `ALPHAFOLD_DB` param.
=> Update alphafold_test params

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_vortex_config.yml
Add cellranger to the TPV with singularity enabled
=> update dev TPV

files/galaxy/config/local_tool_conf.xml
Tool XML is here: [interactivetool_lfqanalyst.xml](https://github.com/usegalaxy-au/tools-au/blob/master/tools/interactivetool_lfqanalyst/interactivetool_lfqanalyst.xml).
=> lfqanalyst as interactive local tool on prod?

host_vars/staging.usegalaxy.org.au.yml
This belongs in a PR from last week. Is there an easy way to see all files in vscode with unsaved changes? It is too easy to miss these.
Original PR: https://github.com/usegalaxy-au/infrastructure/pull/1301
=> staging reports unsaved change

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
There have been a couple of bug reports overnight indicating conda problems.
=> Temporarily set pulsar-mel2 offline

aarnet_playbook.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, staging_playbook.yml, templates/galaxy/webhooks/subdomain_switcher/config.yml
FYI this will be the first time that a subdomain has been deployed to prod with this role.
=> Deploy genomes lab to aarnet

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, host_vars/aarnet.usegalaxy.org.au.yml
This solves the problem of the temp files not going to /tmp.
=> Add /tmp:rw to docker and singularity volumes

aarnet_playbook.yml, aarnet_update_configs_playbook.yml, group_vars/galaxyservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml
This is scheduled for Thursday morning.
=> Production 23.0

aarnet_playbook.yml, aarnet_update_configs_playbook.yml, dev_playbook.yml, dev_update_configs_playbook.yml, handlers/galaxy_handlers.yml, staging_playbook.yml, staging_update_configs_playbook.yml
each playbook with galaxy handlers includes `handlers/galaxy_handlers.yml`.  Tested with dev_update_configs_playbook.yml
=> Put galaxy handlers in their own file

files/galaxy/config/local_tool_data_table_conf.xml, host_vars/dev.usegalaxy.org.au.yml
Add custom database for dev machine
=> add local_tool_data_table_conf.xml

aarnet_playbook.yml, dev_playbook.yml, files/galaxy/config/activation-email.html, files/galaxy/config/activation-email.txt, group_vars/galaxyservers.yml, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/dev.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, templates/galaxy/config/oidc_backends_config.xml.j2
=> More for email activation template and variables

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
The pulsar update seems to interfere with some of the running jobs.
=> Set pulsar-QLD, pulsar-high-mem2 and pqhm0 offline temporarily for pulsar update

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> pqhm1 online, pqhm2 offline

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
Requires [CNAME DNS record](https://github.com/usegalaxy-au/operations/blob/main/head_node/subdomains.md)
and run `ansible-playbook` with `--extra-vars "certbot_expand=true"` to force new SSL cert generation.
See also https://github.com/usegalaxy-au/galaxy-media-site/pull/57
=> Deploy proteomics lab

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml
- Fix subdomains CSS to change masthead background colour
- Add required var `tool_sections`
Ready to run on prod once this is merged and DNS records are set.
=> Fix subdomains css and tool_sections

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.usegalaxy.org.au.yml, templates/galaxy/webhooks/subdomain_switcher/config.yml.j2
- Some vars/logic to allow subdomains to be hidden from site switcher
- Hide proteomics lab
=> Hide proteomics link from subdomain switcher

aarnet_playbook.yml, dev_playbook.yml, staging_playbook.yml
Also change role order so webhooks runs after galaxyproject.subdomains
=> Remove handlers from galaxy playbooks

host_vars/dev.usegalaxy.org.au.yml
=> Add /mnt/galaxy/local_tools:ro to singularity_volumes on dev

templates/galaxy/config/tool_conf_interactive.xml.j2
Switching on RStudio for the R-Basics session at GCC. LMK if i need to do anything else.
=> Enable RStudio for GCC

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, host_vars/aarnet.usegalaxy.org.au.yml, host_vars/pulsar-QLD/pulsar-QLD.genome.edu.au.yml, host_vars/pulsar-paw/pulsar-paw.genome.edu.au.yml, pulsar-QLD_playbook.yml
Based on the last couple of weeks of job running, pulsar-QLD and pulsar-paw will not be missed from production at this time of year. We can return them to production at any time if galaxy is busy.
=> Lend pulsar-paw, pulsar-QLD to etca

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> phm2 offline

host_vars/aarnet.usegalaxy.org.au.yml
Fixing the casing/spelling of "Genome lab"
=> Fix genome lab brand

galaxy_playbook.yml, group_vars/all.yml, group_vars/galaxyservers.yml, roles/nginx-upload-module/tasks/build_module.yml
Add option to download a compiled version of nginx_upload_module. Add miniconda_installer variable to all.yml.
=> Allow nginx upload module to be downloaded for a URL

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Recent tpv changes have not been copied to galaxy servers
=> add change in tpv config to trigger jenkins process

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
sortmerna is failing silently for many jobs. This may or may not help.
=> Update resource allocation for sortmerna

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
These tools currently getting stuck in slurm queue and have passed tests on pulsar.
=> pulsar tag for 2 tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Not sure how high to go for this tool. It does an all vs all alignment of contigs so it could potentially use a lot of memory
=> mem for funannotate_clean

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> set phm1 offline

templates/galaxy/config/aarnet_object_store_conf.xml.j2
ahead of pawsey outage. I'll rebase the other object store PR
=> correct pawsey clause in object store conf

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
trying to reduce oom errors for flye which are regularly occurring for the 8CPU and 16CPU allocations
=> change file size thresholds for flye

host_vars/aarnet.usegalaxy.org.au.yml
Pawsey outage today - taking pawsey mounts offline
=> pawsey outage take pawsey mounts offline

group_vars/aarnet_workers.yml, host_vars/aarnet.usegalaxy.org.au.yml
and permanently remove a temporary entry
=> temporarily remove pawsey mounts

group_vars/aarnet_workers.yml, host_vars/aarnet.usegalaxy.org.au.yml
pawsey user data back online. commit also includes undoing some temporary commenting out of pawsey mounts in shared_mounts
=> pawsey outage recovery bring pawsey mounts online

host_vars/aarnet.usegalaxy.org.au.yml
restarted pawsey-user-nfs - put all pawsey mounts back online
=> pawsey outage recovery put pawsey mounts back online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
interproscan is not cleaning up its temp folders
=> interproscan needs tmp_dir: true

templates/galaxy/config/aarnet_object_store_conf.xml.j2
Change path on object store from /mnt/user-data-6 to /mnt/user-data-6/user-data-6
and change weight of data09 so that /mnt/user-data-6/data09 can be written to at twice the rate of /mnt/data08
=> object store change user-data-6 path

templates/galaxy/config/aarnet_object_store_conf.xml.j2
Stop writing to 150T disk for now
=> switch weight to 0 for data08

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, host_vars/aarnet.usegalaxy.org.au.yml
Also move fastq_groomer away from pulsar
=> Shift upload store path

files/galaxy/gxadmin/gxadmin-local.sh
Add a query for looking at recent max memory metrics from completed jobs
=> add tool memory query to gxadmin.local.sh

hosts
phm1 and phm2 VMs have been rebuilt. updated IP addresses.
=> update IPs for phm1 and phm2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, jenkins/update_labels/tool_labels.yml
For https://github.com/usegalaxy-au/usegalaxy-au-tools/pull/970
Björn showed me this method of running braker3 with the Braker's dev's container instead of the biocontainer (see [Galaxy EU's TPV](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/tpv/tools.yml#L1012))
=> Rules for braker3 

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
also add singularity_enabled for fastqc and hybpiper
=> set pulsar-mel2 pulsar-mel3 online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
snippy is failing with new conda installations on pulsar
=> singularity_enabled for snippy

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Hopefully this is enough for griffith own cloud users
=> Raise mem to 8 for data fetch

one-offs/migrate-tools/reconstitute_conda_envs_playbook.yml, one-offs/migrate-tools/setup_tool_migration_playbook.yml, one-offs/migrate-tools/templates/tool_migration_rsync_script.sh.j2, one-offs/migrate-tools/vars.yml
go back to exporting conda envs and rsyncing the .yml files. Rearrange order of items to rsync.
=> update tool migration script

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml
Not sure if we should merge this without testing first. But I'm not sure how to test this?
=> Enable subdomain cookie-sharing on prod

host_vars/aarnet.usegalaxy.org.au.yml
phm2 is being used for regular sized jobs
=> set pulsar-high-mem2 job limit to 30

host_vars/aarnet.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml, templates/galaxy/config/oidc_backends_config.xml.j2
Add some keys to oidc backends config flagged by @neoformit
=> upgrade aarnet to release 23.1

group_vars/galaxy_etca_slurm.yml, host_vars/galaxy.usegalaxy.org.au.yml
This reverts commit 502f9acf798d5c1695eb1c62e195748dbe08427b.
=> Revert "etca single galaxy VM"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Stopping scheduling to phm2 for now
=> switch phm2 off

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml
=> update galaxy-user-nfs host vars

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add singularity_enabled for some tools. Separate spades tools into distinct definitions because some have minimum singularity version and others can have singularity enabled for all versions.
=> Singularity update 20231024 1

galaxy_update_configs_playbook.yml
playbook for galaxy-handlers to update job conf/tpv conf
=> Add galaxy_update_configs_playbook

files/galaxy/config/local_tool_conf_dev.xml
Working on this IT and need to test it somewhere. Have manually copied across the tool XML as it doesn't seem like they're kept in the playbook.
=> Add ena upload interactive tool to dev

host_vars/galaxy.usegalaxy.org.au.yml
galaxy.yml is missing `tool_data_table_config_path`
=> tool data table config path

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
results are the same as with a conda environment
=> singularity_enabled for ena upload

galaxy-db_playbook.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/pulsar-QLD/pulsar-QLD.genome.edu.au.yml, host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml, host_vars/pulsar-mel2/pulsar-mel2.genome.edu.au.yml, host_vars/pulsar-mel3/pulsar-mel3.genome.edu.au.yml, host_vars/pulsar-nci-training/pulsar-nci-training.usegalaxy.org.au.yml, host_vars/pulsar-paw/pulsar-paw.genome.edu.au.yml, host_vars/pulsar-qld-blast.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml
update tiaas_galaxy_db_host to use internal IP and change "from" for ubuntu_maintenance_key on pulsars
=> Fix pulsar keys and typos

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add singularity_enabled for a number of tools have difficult conda environments. I've also run 'tpv format' on tools.yml which resulted in some lost comments that did not seem worth preserving.
=> Format tpv config and add more singularity tools

galaxy_update_configs_playbook.yml, host_vars/galaxy.usegalaxy.org.au.yml
Waiting on a change to fix the startup logs
=> No sentry on galaxy for now

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
picard and abricate do not need to go to pulsar because the jobs are generally quick
=> run picard and abricate only on local slurm, maker can run on pulsar

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
this tool creates too many large tmp files on the worker volume
=> use tmp_dir for encyclopedia searchtolib

files/galaxy/config/tool_conf.xml, files/galaxy/config/tool_panel_filters/proteomics.yml, host_vars/dev.gvl.org.au.yml
Just want to try this on dev.
Described in [this Galaxy PR](https://github.com/galaxyproject/galaxy/pull/12327)
=> Proteomics panel view

templates/galaxy/config/tool_conf_interactive.xml.j2
=> Enable pavian IT

group_vars/galaxy_etca.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
Update pawsey mount points so that when they are remounted they are within /mnt/user-data-pawsey. Update object store conf for new paths, and singularity_volumes.
=> volume refactor part 2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add stacks denovomap, add increased memory for some tools, remove cores/mem from rna_starsolo so that it can get those values from the shared db
=> tpv oom tools 20231124

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> change braker3 container

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This is failing with no obvious error message on GA but completing on my desktop.
=> braker3 memory

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#1681
=> Revert "pqhm1 offline"

files/galaxy/config/file_sources_conf.yml, files/galaxy/config/user_preferences_extra_conf.yml
take `cloudstor` key out of file_sources.yml and comment out `owncloud_account` key in user_preferences_extra.conf.yml
=> retire cloudstor

dev_playbook.yml, files/galaxy/config/tool_panel_filters/proteomics.yml, group_vars/galaxyservers.yml, host_vars/dev.gvl.org.au.yml
Hey @cat-bro I just noticed that there is no proteomics lab on dev. I have added one here, and set this funky galaxy.yml variable that should make the proteomics panel view the default:
```yml
default_panel_view_by_host:
proteomics.dev.gvl.org.au: proteomics
```
Is this ok?
=> Proteomics tool panel view

host_vars/dev.gvl.org.au.yml
subdomains role needs tool_sections key to exist
=> update hosts dev galaxy subsites block

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add singularity enabled for peterjc tools except for get_orfs_or_cdss which is failing all tests either way
=> singularity for peterjc tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Something is wrong with pulsar-QLD. It isn't accepting jobs and they are queueing. Taking offline to investigate.
=> pulsar-qld offline for fixes

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> singularity for pharokka

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
fgenesh_merge and fgenesh_split do not
=> fgenesh_annotate inherits fgenesh

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
make repeatmasker pulsar only and increase memory to 80
=> increase memory for repeatmasker

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, jenkins/update_labels/tool_labels.yml
Hi @cat-bro! First attempt, I just copied this from alphafold-test. LMK if anything looks off.
The docker image is specified in the wrapper (https://github.com/genouest/galaxy-tools/blob/66b1967152f63ef95eee2058d768a5ae92502997/tools/helixer/macros.xml#L12). No idea about mem and cores yet, I plan to run some test jobs.
=> helixer rules

host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Get galaxy from 
```
galaxy_repo: https://github.com/usegalaxy-au/galaxy.git
galaxy_commit_id: release_23.1_au
```
=> switch to au galaxy

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
taking pulsar-paw offline in preparation for pawsey outage on monday
=> offline pulsar-paw for pawsey outage

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
add fgenesh_get_mrnas_gc.xml and fgenesh_to_genbank.xml to prod TPV
=> add new fgenesh tools to prod TPV

templates/galaxy/toolbox/filters/ga_filters.py.j2
make all of the fgenesh tools visible to the Fgenesh group
=> add fgenesh tools to ga filters

files/galaxy/config/file_sources_conf.yml
https://github.com/galaxyproject/galaxy/issues/17372
=> Fix for webdav loading files into memory

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Update 120cpu/2T to 60cpu/1T for flye, canu, racon etc
=> Reduce resources for 120 cpu allocations

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#1725
=> Revert "temporarily direct all fastqc jobs to slurm"

dev-workers_playbook.yml, galaxy-workers_playbook.yml, pulsar-high-mem1_playbook.yml, pulsar-high-mem2_playbook.yml, pulsar-mel2_worker_playbook.yml, pulsar-mel3_worker_playbook.yml, pulsar-nci-training_workers_playbook.yml, pulsar-paw_worker_playbook.yml, pulsar-qld-high-mem_playbook.yml, roles/clean-tmpdisk/files/clean_tmpdisk.py, roles/clean-tmpdisk/tasks/main.yml, roles/clean-tmpdisk/templates/clean_tmpdisk_variables.yml.j2
Make script a copied file rather than a jinja template, and store variables in a yaml file
=> fix templating in tmpdisk role

dev_playbook.yml, host_vars/dev.gvl.org.au.yml
uncomment tiaas role and go back to default settings for tiaas_repo and tiaas_version on dev
=> reinstate tiaas in dev playbook

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#1790
=> Revert "set actimeo=0 for /mnt/tools"

files/galaxy/config/tool_data_table_conf.xml
this is a draft because ref data is still being copied around the pulsar VMs
=> Add data table entry for bwa_mem2

group_vars/galaxyservers.yml, host_vars/dev-handlers.gvl.org.au.yml, host_vars/dev.gvl.org.au.yml, host_vars/galaxy-handlers.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
On dev and production separate job handlers from workflow schedulers
=> Separate job handling from workflow scheduling

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
fastqc is contributing to a lot of files being staged to pulsars at the moment
=> fastqc to slurm

files/galaxy/gxadmin/gxadmin-local.sh
Add a query to see latest jobs with data from various object store backend IDs.
Also remove local_query-all-jobs from this file because this has been replaced by 'gxadmin query jobs'
=> gxadmin local query jobs by object store id

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
to reduce quantity of files being staged to pulsar
=> trimmomatic to slurm

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
in response to slurm bottleneck
=> put fastqc back on pulsar

requirements.yml
telegraf won't start without this
=> Update dj-wasabi.telegraf role requirement

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
I'd like to check whether disabling singularity will help
=> try singularity_enabled: false for ena_upload

galaxy_playbook.yml
=> Copy access/error logs to /mnt in nginx postrotate script

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
Adding this early.. we'll probably need to merge it next week
=> add data14 dir

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml, host_vars/galaxy-queue.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_job_conf.yml.j2
scaffolding for queue vhosts, tpv users and one destination to start with in tpv destinations.yml.j2
=> galaxyside additions for gpu pulsars

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> mark _pulsar_qld_gpu as an abstract destination

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
2 tools with increased resources due to oom errors need more resources due to oom errors
=> increase cores/ram breseq stacks2_tsv2bam further

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There are currently too many jobs being queued that will only go to the local cluster.
=> send fastqc to pulsar again

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
bakta jobs are failing on pulsar - need to check ref files on pulsar-mel3
=> stop sending bakta to pulsar

host_vars/galaxy.usegalaxy.org.au.yml
I'll merge this straight away because it is interfering with current running jobs stats collection.
=> add tags for gpu1 in job conf

group_vars/pulsarservers.yml
Set maximum_stream_size in pulsar config. Update pulsar version to 0.15.6.
=> set pulsar max stream size

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#1902
=> Revert "put fastqc back on pulsar for now"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
looks like galaxy-covid-19 tenancy has expired
=> Set pulsar-paw offline

templates/galaxy/config/tool_conf_interactive.xml.j2
re-add cellxgene to tool panel since xml file name has changed
=> both cellxgene versions

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
this needs proofreading but shouldn't be merged until it is time to run the playbook
=> [WIP] data 15 in object store

jenkins/update_labels/tool_labels.yml
remove test label so bracken is available to users
=> remove bracken from test tools

group_vars/pulsar_qld_gpus.yml, host_vars/pulsar-qld-gpu3.yml, hosts, pulsar-qld-gpu_playbook.yml
Add 3rd pulsar to hosts. Add slurm gres things. Omit host_vars/<file> from playbook and use the implicit mappings based on filename for the host specific variables
=> Add pulsar-qld-gpu3 and some slurm settings

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
also add `$job_directory/home:rw` for helixir. This should probably be made writable for all container jobs
=> add qld gpu2, set the others offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> blast pulsar offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
increase mem for arriba, vsearch, gfastats and small metaphlan jobs
=> tpv oom updates 20240424

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#1928
=> Revert "blast pulsar offline"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Requested by Igor for a user who is running out of memory
=> update tpv entry for makeblastdb

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, hosts
update worker IPs and set pulsar-QLD to online
=> update qld worker ips

host_vars/galaxy.usegalaxy.org.au.yml
remove ga_code from galaxy config
=> go away code

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
This will need to be merged on Tuesday afternoon and can be reverted on Friday
=> send training jobs to pmel3 while training pulsar is offline

roles/common/tasks/main.yml
Add a boolean extra variable `skip_upgrade_dist`
=> Extra variable that can be used to skip apt upgrade dist

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#1937
=> Revert "send training jobs to pmel3 while training pulsar is offline"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> increase cores/mem for stacks_denovomap

dev_playbook.yml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_destinations.yml.j2, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_vortex_config.yml, templates/galaxy/config/dev_object_store_conf.xml.j2
Do not merge this because the TPV bits are auto deployed
=> Dev test of tmp scratch test logic

group_vars/galaxy_etca.yml, host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
after this is merged, galaxy_workers playbook needs to be run before galaxy playbook
=> Switch to data17 with job working directories on the scratch volume

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> stop running small, medium hisat2 jobs on pulsar

group_vars/galaxyservers.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
Fix galaxy_job_working_directory value so that IT working directories are on the new disk
=> put interactive tool jwds in /mnt/scratch

group_vars/pulsarservers.yml
there was a problem with 0.15.6 which has been fixed by Marius.
=> Upgrade pulsars to specific commit post 0.15.6

group_vars/all.yml
Anna needs to be added to the Galaxy Admins.
=> add Anna to Galaxy admin group

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/default_tool.yml.j2
This is working on dev now. There was a indentation problem and a couple of other bugs
=> fix default tool

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
vm is experiencing soft lockups caused by mothur jobs, probably needs reboot
=> pqhm0 offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-qld-gpu1 is ready for testing
=> set pulsar-qld-gpu1 online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
canu tests pass on both of these
=> phm1 and pqhm0 online

group_vars/pulsar_qld_gpus.yml, one-offs/initial_nvidia_config_and_disable_cgroups_v2_playbook.yml, pulsar-qld-gpu_playbook.yml, roles/nvidia-ctk/defaults/main.yml, roles/nvidia-ctk/handlers/main.yml, roles/nvidia-ctk/tasks/main.yml
Initial untested commits for configuring Nvidia GPU with docker support for Nectar pulsar-qld-gpu's.
=> [WIP] Add gpu specific requirements to pulsar qld gpu playbook

files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Add `alphafold_test` tool for `v2.3.2` development. The `test` label should hide it from public users right?
```xml
<tool file="/mnt/galaxy/local_tools/alphafold/alphafold.xml" labels="test"/>
```
=> Add alphafold test tool

group_vars/galaxy_etca.yml
=> pawsey-user-nfs unavailable due to Pawsey maintenance

group_vars/galaxy_etca.yml
Pawsey maintenance has completed.
=> pawsey-user-nfs available again

pulsar-qld-gpu-dev_playbook.yml
Devs should have sudo access on development pulsar.
=> create dev playbook for pulsar-qld-gpu-dev

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> online pulsar-qld-gpu 3 and 5

files/galaxy/config/local_tool_conf.xml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Test new databases with additional AF test tool
=> Alphafold test 2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
singularity for all tools owned by ebi-gxa, goeckslab, perssond and imgteam + various other requested tools
=> singularity for requested tools

jenkins/update_labels/tool_labels.yml
Release it into the wild :horse:
=> helixer rm test label

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
oops, the scheduling tags were so permissive that normal jobs are going to the qld gpu pulsars
=> Fix gpu tags

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
I'm assuming input_size is in GB?
=> more RAM for large AGAT jobs

files/galaxy/config/local_tool_conf_dev.xml, host_vars/dev.gvl.org.au.yml, templates/galaxy/toolbox/filters/aagi_filters.j2
Restrict tools with the `aagi` label to users with the `aagi` role
(QCIF project)
=> Toolbox filter on AAGI tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> send training jobs to pulsar-mel3 while pulsar-nci-training is offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Send unicycler and flye 16 cpu jobs to high memory pulsars with 150GB RAM
Other updates based on output of 'gxadmin local query-oom-jobs'
=> oom updates 20240806

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
data19 on `user-data-volA` is running out of space. create data20 on `user-data-volB`.
=> create data20 on user-data-volB

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.xml.j2
The current user-data volume, `user-data-volC`, is running low on space. Create `data22` on `user-data-volA`.
=> create data22 on user-data-volA

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
100G RAM for jobs with 1-2GB input
=> add extra file size rule for bwa_mem2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Hypervisor upgrades required by UoM IT.
=> offline phm1 phm2 for maintenance

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
ref https://github.com/galaxyproject/tpv-shared-database/pull/68
=> Increase memory for lotus2

group_vars/galaxy_etca.yml
taken offline at 12:30 by hand
=> pawsey-user-nfs data offline

group_vars/galaxyservers.yml, templates/galaxy/config/user_preferences_extra_conf.yml.j2
Useful if we want to add things in dev before ready for production, such as openAI key
=> Make user preferences extra a template instead of a file

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2152
=> Revert "pawsey file mounts unavailable"

files/galaxy/config/tool_conf.xml
These are all built ins that are installed on usegalaxy.org, but I haven't tested any of them.
=> Adding builtins for collections based on main

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, galaxy-handlers_playbook.yml, host_vars/galaxy-handlers.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_job_conf.yml.j2
Add gunicorn process to galaxy-handlers and switch one of the pulsars to get files from galaxy-handlers instead of galaxy
=> switch on gunicorn and nginx on galaxy-handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
This pulsar is reading/writing files through nginx-upload-module on the galaxy-handlers VM
=> set pqhm2 to online

files/galaxy/config/local_tool_conf.xml, files/galaxy/config/local_tool_conf_dev.xml, templates/galaxy/config/user_preferences_extra_conf.yml.j2
related to https://github.com/usegalaxy-au/tools-au/pull/123
=> Add AARNet FileSender user preferences for AARNet FileSender Galaxy tool

files/galaxy/gxadmin/gxadmin-local.sh
gxadmin local query-oom-jobs is missing some occurrences on pulsars
=> more oom phrases

group_vars/galaxyservers.yml
When merged I can add this manually to production and restart gunicorn
=> enable notifications for all

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
File size and singularity rules for diffbind, more mem for mirdeep2_mapper which is fine on pulsar. This also adds a bunch of rule IDs where they were missing
=> Diffbind and mirdeep tpv

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml
Allow a test user to bypass `singularity_enabled` and try out the tool's conda environment
=> test user conda tag

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/users.yml
remove the conda tag rule from test_user because it doesn't work. Remove singularity_enabled from verkko instead
=> try verkko without singularity

host_vars/galaxy.usegalaxy.org.au.yml
=> Proteomics lab -> Lab

group_vars/galaxy_etca.yml, templates/galaxy/config/galaxy_object_store_conf.yml.j2
the contents of files2 (~700GB) have been rsynced to files on QLD so we do not need the volume anymore
=> Remove second qld volume and add vol D

host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Hey @cat-bro - this updates all galaxy lab URLs to their final resting place, but depends on this PR being merged:
https://github.com/galaxyproject/galaxy_codex/pull/167
=> Update galaxy lab iframe URLs

host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Reverts usegalaxy-au/infrastructure#2206
=> Revert "Update galaxy lab iframe URLs"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> remove local mem definition for anndata_import

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
update stacks_denovomap to have the same resources as stacks2_denovomap. This isn't configured to run on pulsar but it would be a good one for pulsar if it can run there
=> stacks denovomap memory

files/galaxy/config/local_tool_conf_dev.xml
So that we can test @madsi1m's new version via the toolshed
=> Remove manual install of filesender

host_vars/dev.gvl.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/staging.gvl.org.au.yml
Reverts usegalaxy-au/infrastructure#2218
=> Revert "Revert "Update galaxy lab iframe URLs""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
The container ships an R config file that needs to be updated before running the plot tool.
=> writable tmpfs for plot_ragtag_paf

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2233
=> Revert "writable tmpfs for plot_ragtag_paf"

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2234
=> Revert "Revert "writable tmpfs for plot_ragtag_paf""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2235
=> Revert "Revert "Revert "writable tmpfs for plot_ragtag_paf"""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2236
=> Revert "Revert "Revert "Revert "writable tmpfs for plot_ragtag_paf""""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2237
=> Revert "Revert "Revert "Revert "Revert "writable tmpfs for plot_ragtag_paf"""""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2241
=> Revert "Revert "Revert "Revert "Revert "Revert "writable tmpfs for plot_ragtag_paf""""""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2242
=> Revert "Revert "Revert "Revert "Revert "Revert "Revert "writable tmpfs for plot_ragtag_paf"""""""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2243
=> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "writable tmpfs for plot_ragtag_paf""""""""

files/galaxy/gxadmin/gxadmin-local.sh
Add some new gxadmin local queries
```
gxadmin local query-user-workflow-invocations <username>  # outputs history IDs that can be used in following queries
gxadmin local query-history-job-io <history_id>
gxadmin local query-history-job-output-sum <history_id>
```
These are useful for checking on workflows we have run as selenium test users to see how much data is being generated and how time consuming various steps are
=> New gxadmin local queries

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Hi @jl, I'm testing workflow 5 as myself and it would be handy to see whether extra memory helps with this tool
=> give random_lines1 extra mem

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
checkm tools: 4c 15g -> 8c 31g
repeatmodeler: 16c 36g -> 16c 62g
=> increase resource allocations for checkm and repeatmodeler

jenkins/config_backup/config_backup_playbook.yml, jenkins/config_backup/run_backup.sh
=> update jenkins config backup

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
give checkm a large memory allocation to see if it helps
increase memory for small quast and busco jobs
=> oom updates 20241028

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Not sure if you want this, but since I was here: https://github.com/galaxyproject/tpv-shared-database/pull/72
=> remove clustalw

templates/galaxy/config/galaxy_object_store_conf.yml.j2
This seems like the right move for more testing of flushed data
=> shrink the test caches

templates/galaxy/config/galaxy_object_store_conf.yml.j2
Reverts usegalaxy-au/infrastructure#2268
I'll add this later
=> Revert "shrink the test caches"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
temporarily reduce tpv's understanding of resources available at pulsar-QLD
=> reduce pulsar QLD capacity in tpv

group_vars/galaxy_etca.yml, templates/galaxy/config/galaxy_object_store_conf.yml.j2
keep test paths out of object store for now but add a variable to enable them
=> boolean var to enable test object store paths

files/galaxy/config/local_tool_conf_dev.xml, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_tools.yml.j2
Minor update to deploy another AAGI tool on dev
=> AAGI tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
To be merged prior to hypervisor switch off at 2pm Wed 6th Nov.
=> take pulsar-qld-gpu4 and gpu5 offline for GPU3 replacement

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-qld-gpu3 has a new GPU and has been tested with Alphafold. Ready to be put to work.
=> pulsar-qld-gpu3 is ready for use

host_vars/galaxy.usegalaxy.org.au.yml
@cat-bro or @jlqfab I've discussed this with Gareth and Cam but happy to explain more in this afternoon's meeting. Please also check I've done it correctly!
=> Add AlphaFold2 update tool message

dev-handler_playbook.yml, host_vars/dev-handlers.gvl.org.au.yml, host_vars/dev.gvl.org.au.yml
Setup postfix on dev-handlers to use smtp2go. Also fix host domain for dev - should just be the domain not host+domain.
=> configure dev-handlers postfix to use smtp2go

host_vars/galaxy.usegalaxy.org.au.yml
the link is opening the alphafold tool form in a new tab, this might be the problem
=> remove extra " from alphafold tool message

galaxy_playbook.yml
We could use tags, but might not remember to - I'll revert this next week
=> interim commenting of production walle

galaxy_playbook.yml
Reverts usegalaxy-au/infrastructure#2293
=> Revert "interim commenting of production walle"

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2302
=> Revert "Switch on test object store backends"

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2304
=> Revert "Revert "Switch on test object store backends""

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2306
=> Revert "Revert "Revert "Switch on test object store backends"""

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2308
=> Revert "Revert "Revert "Revert "Switch on test object store backends""""

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2309
=> Revert "Revert "Revert "Revert "Revert "Switch on test object store backends"""""

group_vars/galaxy_etca.yml
Reverts usegalaxy-au/infrastructure#2312
=> Revert "Revert "Revert "Revert "Revert "Revert "Switch on test object store backends""""""

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
=> impose quast limit

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
switch off pulsar-mel3 for rebuild
=> pulsar-mel3 offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Jobs are failing with "docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'+
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown."
=> qld gpu3 offline

roles/common/tasks/bashrc.yml
=> set default for variable

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Hypervisor maintenance scheduled for 29/1/2025
=> reduce pulsar-QLD capacity for hypervisor maintenance

scripts/update_roles.py
this has been bugging out when it encounters a new role in requirements.yml
=> fix update-roles bug

group_vars/galaxy_etca.yml
Hypervisor maintenance scheduled for 29/1/2025
=> qld-exports offline for hypervisor maintenance

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
csvtk isn't from iuc but the tools on a single conda package so this ought to work
=> singularity for csvtk

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
NCI offline Tuesday 4/2/25 from 8am to 6pm
=> send training jobs to pulsar-QLD while pulsar-nci-training is offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-nci-training is back online after NCI maintenance yesterday
=> resume training jobs go to pulsar-nci-training

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> pulsar-qld-gpu1-2 online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Nvidia packages have been updated
=> pulsar-qld-gpu3 online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
latest version only, note to test older versions
=> add quast singularity rule

group_vars/galaxy_etca.yml
Pawsey is back.
@cat-bro DO NOT merge until pawsey-user-nfs has been remounted!
=> pawsey-user-nfs online

host_vars/pulsar-qld-blast.yml
Triple the cvmfs cache size on pulsar-qld-blast
=> increase cvmfs cache size on pqblast

templates/galaxy/webhooks/subdomain_switcher/script.js.j2
Fix click handlers for site switcher, so that it doesn't open with every click event on window (i.e. all the time).
Also refactored for improved robustness in different browsers/computers.
=> Site switcher bug

files/galaxy/config/tool_panel_filters/microgalaxy.yml, host_vars/dev.gvl.org.au.yml
- Add microgalaxy lab on subdomain `microbe.dev.gvl.org.au`
- Add microgalaxy tool panel view
=> Microgalaxy lab on dev

host_vars/pulsar-high-mem1/pulsar-high-mem1.yml, host_vars/qld-pulsar-himem-0.yml, host_vars/qld-pulsar-himem-1.yml, host_vars/qld-pulsar-himem-2.yml
There is room to increase these from 20GB to 250GB on the big pulsars
=> increase cvmfs cache size for pulsars with lots of space

templates/galaxy/config/tool_conf_interactive.xml.j2
Reverts usegalaxy-au/infrastructure#2409
=> Revert "remove jupyter from tool conf"

templates/galaxy/config/tool_conf_interactive.xml.j2
Reverts usegalaxy-au/infrastructure#2414
=> Revert "Revert "remove jupyter from tool conf""

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_default_tool.yml.j2, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_vortex_config.yml
Add a rule that requires a user to be logged in to use ITs on dev
=> dev require login

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
There is something wrong with the container. When running with the container it is not possible to download a file. Is this normal?
=> disable singularity and increase mem for custom_pro_db

host_vars/galaxy.usegalaxy.org.au.yml
Un-commented prod microbiology lab (Codex/Lab PRs have now merged)
=> Enable prod micro lab

host_vars/galaxy-handlers.usegalaxy.org.au.yml
Ensure continuous uptime for web service for pulsar file transfer
=> second gunicorn for galaxy-handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, host_vars/galaxy.usegalaxy.org.au.yml, host_vars/pulsar-high-mem2/pulsar-high-mem2.yml
Add a relief pulsar blast destination on pulsar-high-mem2.
=> pulsar-mel-blast job destination

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#2455
=> Revert "pqgpu1-2 offline"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#2457
=> Revert "pqgpu3 offline"

galaxy-media_dev_playbook.yml, galaxy-media_playbook.yml, group_vars/gms.yml, roles/galaxy_media_site/tasks/main.yml
I found some issue with the postgresql config that needed fixing as this broke gms-dev.
- `postgresql_listen_addresses` is not used - needs to be set in `postgresql_global_config_options`
- The `postgresql_hba_entries` prevented local/peer connection from `postgres` user
=> Fix gms postgres

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-qld-himem0 ready for hypervisor maintenance
pulsar-qld-himem1 completed hypervisor maintenance
pulsar-qld-himem2 prep for hypervisor maintenance
=> pulsar-qld-himem updates 0-offline 1-online 2-quick

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Good opportunity while it's quiet
=> pulsar-QLD offline

jenkins/update_labels/tool_labels.yml
=> give 'test' label to ncbi_fcs_gx

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Hypervisor maintenance completed for these VMs.
=> Pulsar qld himem2 online and pulsar-QLD remove quick tag

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
w5-w6 have an outage next week
=> reduce capacity of pulsar-QLD

galaxy-media_dev_playbook.yml, roles/galaxy_media_site/tasks/main.yml
This seems to be the proper fix for a recent workaround that I made. Tested and working.
=> Flush handlers to prompt postgres restart

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#2480
=> Revert "reduce capacity of pulsar-QLD"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#2494
=> Revert "reenable pulsar nci training for now"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
super old tool might work with this container
=> try to fix ctb_online_data_fetch

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, host_vars/galaxy.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.yml.j2
Create a data27 directory and remove explicit setting of job_working_directory since the default is now the right one in every case.
=> add data27

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> pulsar qld high mems all offline

jenkins/phone_in_utils/restart_galaxy_handers.sh, jenkins/phone_in_utils/restart_galaxy_handlers_playbook.yml
playbook to restart job handlers from jenkins ui
=> jenkins restart handlers

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Copying Galaxy Europe
This is still in 'test' mode because so far it has failed for all user jobs
=> give lots of memory to ncbi_fcs_gx

host_vars/galaxy.usegalaxy.org.au.yml
=> Add a destination_total_concurrent_jobs for pulsar-nci-training

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
try singularity for built in tool qual_stats_boxplot
=> singularity for qual_stats_boxplot

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2527
=> Revert "singularity for qual_stats_boxplot"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Prepare for the possibility that NCI pulsar will not be back this week
=> set pmel3 to training only

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Lower min mem to 39 and add funannotate tag
=> Allow funannotate to run on pqhm0

files/galaxy/config/local_tool_conf.xml
=> Add phyloseq IT as local tool

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
increase sortmerna, freebayes and deeptools limits from 2 to 4
=> increase per user limits for tools

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
add docker_run_extra_arguments
=> add interactive tool phyloseq to tpv

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reverts usegalaxy-au/infrastructure#2540
=> Revert "send dorado to gpu5 only, helixer to gpu4 only"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
We never ran the one-off playbook JL made for these to stop the auto updating.  3 and 5 can be done later.
=> set gpu VMs 1, 2 and 4 to offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> switch offline gpu pulsars

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
all previous things have failed, try lots of memory
=> 31G RAM for lotus2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pmel2 is not busy and is a good place to learn to set up a CVMFS alien cache (common cache)
=> Set pmel2 to offline

roles/galaxy_labs_engine/handlers/main.yml
Add `-y` flag to this command so it doesn't just hang
=> Labs engine cache_update non-interactive

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
This tool has suspected incompatibility with pulsar in some cases
=> no pulsar for kallisto_quant

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
return gpu3 to alphafold group, ensure helixir and dorado do not use the same VMs
=> send helixir and dorado to separate pulsars

group_vars/galaxy_etca.yml
Mount 50TB volume attached to galaxy-aust-exports.
=> new qld files2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
stop small/medium jobs going to high memory for now
=> increase min memory for pqhm0

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
falco, mummer_nucmer and a fasta converter
=> Update TPV to avoid common OOM errors

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Increase from 2 to 5 to assist CVMFS testing
=> let people run more concurrent bakta jobs

templates/galaxy/webhooks/toolmsg/script.js.j2, templates/galaxy/webhooks/toolmsg_24.2/script.js.j2
Stupid syntax error, will need to let EU/main know about this (I can't remember if main is also using this)
=> Fix bug in toolmsg plugin

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
training jobs will run on regular resources
=> Make bwa_mem2 training-exempt

host_vars/galaxy-user-nfs.usegalaxy.org.au.yml, templates/galaxy/config/galaxy_object_store_conf.yml.j2
=> read data22 from volB instead of volA

host_vars/dev.gvl.org.au.yml
This has not been released and there are no release notes as yet. I’ll make this a draft until I have looked at the differences in galaxy.yml.sample files.
=> Update dev to release_25.0

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
things came back from soft reboots
=> pulsar-QLD online

files/galaxy/gxadmin/gxadmin-local.sh
I have been using this local query a lot. This change makes it easier to fit in the terminal.
=> Update gxadmin local session query

host_vars/galaxy.usegalaxy.org.au.yml
since the hostnames of qld high mem pulsars have changed
=> update hostnames in host_vars/galaxy

host_vars/galaxy.usegalaxy.org.au.yml
=> Upgrade Galaxy Australia to release_25.0

templates/galaxy/config/galaxy_job_conf.yml.j2
Reverts usegalaxy-au/infrastructure#2674
=> Revert "restrict DATA_FETCH to handler_0 in tools section of job_conf"

files/galaxy/config/tool_data_table_conf.xml
add fgenesh_db_v2024 to tool_data_table_conf.xml
=> Update tool data conf prod

files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_default_tool.yml.j2, files/galaxy/dynamic_job_rules/dev/total_perspective_vortex/dev_destinations.yml.j2
Update TPV conf on dev in line with changes that have been made on production, and add a rank function so that I can test a change for production.
=> Update dev rank function

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
=> pqgpu3 offline

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Reduce memory and CPU requirements for gffread and send to pulsar-mel2
=> send gffread to pulsar-mel2

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
NCI offline Tuesday 5 August 2025 for Q3 Scheduled Maintenance
=> NCI-training offline tomorrow send training jobs to pulsar-mel3

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
pulsar-qld-himem0 is unreachable
=> pulsar-qld-himem0 offline

templates/galaxy/webhooks/toolmsg/script.js.j2
And woops... not sure how it didn't catch that
=> Fix undefined variable in toolmsg plugin

templates/galaxy/webhooks/tips/config.yml, templates/galaxy/webhooks/tips/script.js, templates/galaxy/webhooks/tips/styles.css
Add the new tips webhook to dev for testing and showcase
=> Add tips webhook to dev

dev_playbook.yml, group_vars/galaxyservers.yml, host_vars/dev.gvl.org.au.yml, roles/webhooks/defaults/main.yml, roles/webhooks/tasks/copy_builtin_webhooks.yml, roles/webhooks/tasks/main.yml
- Refactored webhooks plugin to place webhooks in `galaxy_config_dir` instead of `galaxy_server_dir`
- Added "tips" to dev webhooks list
=> Tips on dev (fix and refactor)

roles/webhooks/tasks/copy_builtin_webhooks.yml, roles/webhooks/tasks/main.yml
This should fix the issue @jlqfab, sorry about that
=> Create webhooks dir before attempt to copy

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
undo [PR #2743](https://github.com/usegalaxy-au/infrastructure/pull/2743)
=> re-enable restrictions on juypter notebook

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Set verkko up to run on pulsar-qld-high-mem1. No idea whether this will work because verkko cannot be tested.
=> verkko scheduling1

jenkins/update_labels/tool_labels.yml, pulsar-qld-high-mem_playbook.yml
also include a task to create the folder where the data goes on pqhm2
=> Remove test label from ncbi_fcs_gx

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2, files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Give jobs with over 200MB of input 100GB of RAM
=> funannotate predict large input rule

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
megahit, plasflow, gmx_em, mummer
=> more oom updates 2025-10-02

group_vars/galaxy_etca.yml
Qld Nectar VMs are reachable again
=> set qld file mounts online

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/destinations.yml.j2
Reverts usegalaxy-au/infrastructure#2804
=> Revert "pqhm0 and pqhm1 offline"

files/galaxy/dynamic_job_rules/production/total_perspective_vortex/tools.yml
Try to prevent bakta jobs from failing by making sure the each one gets a worker node to itself
=> prefer to send bakta to pulsar-QLD
